import type { LinguisticMode } from '@/types';

// ─── Terminology Map ───────────────────────────────────────────────────────
// Maps a term key to its English, Standard and Arabised Maltese equivalents.

export const TERMINOLOGY: Record<string, { en?: string; standard: string; arabised: string }> = {
    // Morphological patterns
    'pattern': { en: 'Pattern', standard: 'Mudell', arabised: 'Wiżen' },
    'patterns': { en: 'Patterns', standard: 'Mudelli', arabised: 'Mudelli' },
    'wizen': { en: 'Wiżen', standard: 'Wiżen', arabised: 'Wiżen' },
    'cv': { en: 'CV', standard: 'CV', arabised: 'CV' },
    'cv-notation-hint': { en: '(v = short, V = long vowel)', standard: '(v = qasira, V = twila)', arabised: '(v = qasira, V = twila)' },
    'invariable': { en: 'No Elative', standard: 'L-ebda Elattiv', arabised: 'L-ebda Elattiv' },
    'cv-pattern': { en: 'CV Pattern', standard: "Mudell ta' CV", arabised: "Mudell ta' CV" },
    'wizen-pattern': { en: 'Wiżen Pattern', standard: "Mudell ta' Wiżen", arabised: "Mudell ta' Wiżen" },
    'demonym': { en: 'Demonym', standard: 'Demonym', arabised: 'Nisba' },
    'root': { en: 'Root', standard: 'Għerq', arabised: 'Ġidra' },
    'weak': { en: 'Weak', standard: 'Dgħajjef', arabised: 'Magħlul' },
    'geminated': { en: 'Geminated', standard: 'Trux', arabised: 'Imżewweġ' },
    'verbal-forms': { en: 'Verbal Forms', standard: 'Forom Verbali', arabised: 'Użien' },
    'lemma': { en: 'Lemma', standard: 'Lemma', arabised: 'Ras il-Kelma' },
    'passive': { en: 'Passive', standard: 'Passiv', arabised: 'Mifgħul' },
    'active': { en: 'Active', standard: 'Attiv', arabised: 'Fiegħel' },
    'noun-type': { en: 'Noun Type', standard: "Tip ta' Nom", arabised: "Għamla ta' Isem" },
    'dialect': { en: 'Dialect', standard: 'Djalett', arabised: 'Ilsejjen' },
    'conjugation-table': { en: 'Conjugation Table', standard: 'Tabella tal-Konjugazzjoni', arabised: 'Tabella tat-Tisrif' },
    'person': { en: 'Person', standard: 'Persuna', arabised: 'Nifs' },
    'imperfect': { en: 'Imperfect', standard: 'Imperfett', arabised: 'Għajr Tmim' },
    'perfect': { en: 'Perfect', standard: 'Perfett', arabised: 'Tmim' },
    'imperative': { en: 'Imperative', standard: 'Imperattiv', arabised: 'Amar' },
    'singular': { en: 'Singular', standard: 'Singular', arabised: 'Fard' },
    'plural': { en: 'Plural', standard: 'Plural', arabised: 'Ġmigħ' },
    'paucal': { en: 'Paucal', standard: 'Pawkal', arabised: 'Pawkal' },
    'augmentative': { en: 'Augmentative', standard: 'Tkabbir', arabised: 'Tkabbir' },
    '1s': { en: 'I', standard: 'Jiena', arabised: 'Jiena' },
    '2s': { en: 'You (singular)', standard: 'Inti', arabised: 'Inti' },
    '3ms': { en: 'He', standard: 'Huwa', arabised: 'Huwa' },
    '3fs': { en: 'She', standard: 'Hija', arabised: 'Hija' },
    '1p': { en: 'We', standard: 'Aħna', arabised: 'Aħna' },
    '2p': { en: 'You (plural)', standard: 'Intom', arabised: 'Intom' },
    '3p': { en: 'They', standard: 'Huma', arabised: 'Huma' },

    // Possessive Pronouns (for Inflection Tables)
    'pos-1s': { en: 'my', standard: 'tiegħi', arabised: 'tiegħi' },
    'pos-2s': { en: 'your (singular)', standard: 'tiegħek', arabised: 'tiegħek' },
    'pos-3ms': { en: 'his', standard: 'tiegħu', arabised: 'tiegħu' },
    'pos-3fs': { en: 'her', standard: 'tagħha', arabised: 'tagħha' },
    'pos-1p': { en: 'our', standard: 'tagħna', arabised: 'tagħna' },
    'pos-2p': { en: 'your (plural)', standard: 'tagħkom', arabised: 'tagħkom' },
    'pos-3p': { en: 'their', standard: 'tagħhom', arabised: 'tagħhom' },

    'polarity': { en: 'Polarity', standard: 'Polarità', arabised: 'Għamudija' },
    'positive': { en: 'Positive', standard: 'Pożittiv', arabised: 'Qagħdi' },
    'negative': { en: 'Negative', standard: 'Negattiv', arabised: 'Ċaħdi' },
    'direct-object': { en: 'Direct Object', standard: 'Oġġett Dirett', arabised: 'Mifgħul bih l-Ewwel' },
    'indirect-object': { en: 'Indirect Object', standard: 'Oġġett Indirett', arabised: 'Mifgħul bih it-Tieni' },
    'derived-terms': { en: 'Derived Terms', standard: 'Termini Derivati', arabised: 'Magħlqat Maħruġa' },
    'verbal-noun': { en: 'Verbal Noun', standard: 'Nom Verbali', arabised: 'Isem Fagħli' },
    'passive-participle': { en: 'Passive Participle', standard: 'Partiċipju Passiv', arabised: 'Mifgħul' },
    'active-participle': { en: 'Active Participle', standard: 'Partiċipju Attiv', arabised: 'Fiegħel' },
    'no-elative': { en: 'No Elative', standard: 'L-ebda Elattiv', arabised: 'L-ebda Elattiv' },
    'usage-example': { en: 'Usage Example', standard: "Eżempju ta' Użu", arabised: "Xbieha ta' Użu" },
    'thesaurus': { en: 'Thesaurus', standard: 'Teżawru', arabised: 'Mifles' },
    'synonyms': { en: 'Synonyms', standard: 'Sinonimi', arabised: 'Mixxibhin' },
    'antonyms': { en: 'Antonyms', standard: 'Antonimi', arabised: 'Mitfirqin' },
    'synonym-abbr': { en: 'syn.', standard: 'sin.', arabised: 'mibb.' },
    'antonym-abbr': { en: 'ant.', standard: 'ant.', arabised: 'mtf.' },
    'gender': { en: 'Gender', standard: 'Ġeneru', arabised: 'Ġens' },
    'feature': { en: 'Feature', standard: 'Karatteristika', arabised: 'Fsurija' },
    'has-inflection': { en: 'Has Inflection', standard: 'Għandu Inflessjoni', arabised: 'Għandu Tisrif' },
    'letter': { en: 'Letter', standard: 'Ittra', arabised: 'Ittra' },
    'rule': { en: 'Rule', standard: 'Regola', arabised: 'Qies' },
    'example': { en: 'Example', standard: 'Eżempju', arabised: 'Xbieha' },
    'assimilated': { en: 'Assimilated', standard: 'Assimilat', arabised: 'Imxebbah' },
    'standard-label': { en: 'Standard', standard: 'Standard', arabised: 'Standard' },
    'sun-moon-letters': { en: 'Sun & Moon Letters', standard: 'Ittri tax-Xemx u tal-Qamar', arabised: 'Ittri tax-Xemx u tal-Qamar' },
    'sun-letters': { en: 'Sun Letters', standard: 'Ittri tax-Xemx', arabised: 'Ittri tax-Xemx' },
    'moon-letters': { en: 'Moon Letters', standard: 'Ittri tal-Qamar', arabised: 'Ittri tal-Qamar' },

    // Parts of Speech
    'verb': { en: 'Verb', standard: 'Verb', arabised: 'Fagħal' },
    'noun': { en: 'Noun', standard: 'Nom', arabised: 'Isem' },
    'nominal': { en: 'Nominal', standard: 'Nominali', arabised: 'Nominali' },
    'adjective': { en: 'Adjective', standard: 'Aġġettiv', arabised: 'Isem Fissieri' },
    'adverb': { en: 'Adverb', standard: 'Avverbju', arabised: 'Għatu' },
    'particle': { en: 'Particle', standard: 'Partiklu', arabised: 'Ntejfa' },
    'preposition': { en: 'Preposition', standard: 'Prepożizzjoni', arabised: 'Ntejfa Ġarrari' },
    'conjunction': { en: 'Conjunction', standard: 'Konġunzjoni', arabised: 'Ntejfa Għaqqadi' },
    'article': { en: 'Article', standard: 'Artiklu', arabised: 'Għodda tat-Tagħrif' },
    'interrogative': { en: 'Interrogative', standard: 'Interrogattiv', arabised: 'Għodda Saqsejja' },
    'pronoun': { en: 'Pronoun', standard: 'Pronom', arabised: 'Dmir' },
    'participle': { en: 'Participle', standard: 'Partiċipju', arabised: 'Xerriek' },
    'numeral': { en: 'Numeral', standard: 'Numerali', arabised: 'Għaddi' },
    'interjection': { en: 'Interjection', standard: 'Interjezzjoni', arabised: 'Tagħġiba' },
    'prefix': { en: 'Prefix', standard: 'Prefiss', arabised: 'Qagħda Quddimija' },
    'suffix': { en: 'Suffix', standard: 'Suffiss', arabised: 'Qagħda Warranija' },
    'masculine': { en: 'Masculine', standard: 'Maskili', arabised: 'Imdakkar' },
    'feminine': { en: 'Feminine', standard: 'Femminil', arabised: 'Immarri' },
    'neutral': { en: 'Neutral', standard: 'Newtrali', arabised: 'Newtrali' },
    'transitive': { en: 'Transitive', standard: 'Tranżittiv', arabised: 'Mitgħaddi' },
    'intransitive': { en: 'Intransitive', standard: 'Intranżittiv', arabised: 'Lieżem' },
    'ditransitive': { en: 'Ditransitive', standard: 'Ditranżittiv', arabised: 'Mitgħaddi lil Mifgħulejn' },
    'both': { en: 'Both', standard: 'It-Tnejn', arabised: 'It-Tnejn' },
    'loan': { en: 'Loan', standard: 'Selfa', arabised: 'Selfa' },
    'loanword': { en: 'Loanword', standard: 'Selfa', arabised: 'Selfa' },
    'source-citation': { en: 'Source Citation', standard: "Ċitazzjoni tas-Sors", arabised: "Stexhid tal-Merġa'" },
    'primary-source-language': { en: 'Primary Source Language', standard: 'Lingwa Sors Prinċipali', arabised: "Ilsien il-Merġa' Ewlieni" },

    // Verb strength
    'strong': { en: 'Strong', standard: 'Sħiħ', arabised: 'Sħiħ' },
    'hollow': { en: 'Hollow', standard: 'Moħfi', arabised: 'Moħfi' },
    'defective': { en: 'Defective', standard: 'Difettuż', arabised: 'Nieqes' },
    'assimilative': { en: 'Assimilative', standard: 'Assimilattiv', arabised: 'Xebbiehi' },
    'doubled': { en: 'Doubled', standard: 'Trux', arabised: 'Imżewweġ' },
    'quadriliteral': { en: 'Quadriliteral', standard: 'Kwadrilitteral', arabised: 'Robgħi' },
    'strong-hybrid': { en: 'Strong-Hybrid', standard: 'Sħiħ Ibridu', arabised: 'Sħiħ Ibridu' },
    'weak-hybrid': { en: 'Weak-Hybrid', standard: 'Dgħajjef Ibridu', arabised: 'Magħlul Ibridu' },
    'mixed': { en: 'Mixed', standard: 'Imħallat', arabised: 'Imħallat' },
    'triliteral': { en: 'Triliteral', standard: 'Trilitteral', arabised: 'Tolti' },

    // Morphosyntactic categories
    'table-of': { en: 'Table of', standard: 'Tabella tal-', arabised: 'Tabella tat-' },
    'conjugation': { en: 'Konjugazzjoni', standard: 'Konjugazzjoni', arabised: 'Tisrif' },
    'syntax': { en: 'Syntax', standard: 'Sintassi', arabised: 'Naħu' },
    'sentence': { en: 'Sentence', standard: 'Sentenza', arabised: 'Sentenza' },

    // Phonology
    'consonants': { en: 'Consonants', standard: 'konsonanti', arabised: 'ħossi' },
    'vowels': { en: 'Vowels', standard: 'vokali', arabised: 'leħni' },

    // Grammar roles
    'subject': { en: 'Subject', standard: 'suġġett', arabised: 'fiegħel' },
    'object': { en: 'Object', standard: 'oġġett', arabised: 'mifgħul' },

    // UI labels
    'search': { en: 'Search', standard: 'Fittex', arabised: 'Fittex' },
    'filters': { en: 'Filters', standard: 'Filtri', arabised: 'Saffajjiet' },
    'show-more': { en: 'Show More', standard: 'Uri Aktar', arabised: 'Idher Iżjed' },
    'definitions': { en: 'Definitions', standard: 'Tifsiriet', arabised: 'Tifsiriet' },
    'etymology': { en: 'Etymology', standard: 'Etimoloġija', arabised: 'Tnissil' },
    'examples': { en: 'Examples', standard: 'Eżempji', arabised: 'Xbihat' },
    'reliability': { en: 'Reliability', standard: 'Affidabilità', arabised: 'Affidabilità' },
    'source': { en: 'Source', standard: 'Sors', arabised: "Mirġgħa" },
    'sources': { en: 'Sources', standard: 'Sorsi', arabised: "Imrieġa'" },
    'arabic': { en: 'Arabic', standard: 'Għarbi', arabised: 'Għarbi' },
    'sicilian': { en: 'Sicilian', standard: 'Sqalli', arabised: 'Sqalli' },
    'italian': { en: 'Italian', standard: 'Taljan', arabised: 'Taljan' },
    'latin': { en: 'Latin', standard: 'Latin', arabised: 'Latini' },
    'french': { en: 'French', standard: 'Franċiż', arabised: 'Franċiż' },
    'english': { en: 'English', standard: 'Ingliż', arabised: 'Ingliż' },
    'feminine-singular': { en: 'Feminine singular', standard: 'Femminil singulari', arabised: 'Femminil singulari' },
    'spanish': { en: 'Spanish', standard: 'Spanjol', arabised: 'Spanjol' },
    'berber': { en: 'Berber', standard: 'Berberu', arabised: 'Berberi' },
    'greek': { en: 'Greek', standard: 'Grieg', arabised: 'Grieg' },

    // Dictionary UI components
    "semitic": { en: 'Semitic', standard: 'Semitiku', arabised: 'Siemi' },
    "romance": { en: 'Romance', standard: 'Rumanz', arabised: 'Rumanzi' },
    "its-audio": { en: 'its audio', standard: 'l-awdjo tiegħu', arabised: 'ħossu' },
    "audio": { en: 'Audio', standard: 'Awdjo', arabised: 'Ħoss' },
    "pronunciation": { en: 'Pronunciation', standard: 'Pronunzja', arabised: 'Tlissin' },
    'entry': { en: 'Entry', standard: 'Entrata', arabised: 'Madħla' },
    'entries': { en: 'Entries', standard: 'Entrati', arabised: 'Madħliet' },
    'form': { en: 'Form', standard: 'Forma', arabised: 'Sura' },
    'surface-form': { en: 'Surface Form', standard: 'Forma Miktuba', arabised: 'Sura Setħija' },
    'form-label': { en: 'FORM', standard: 'FORMA', arabised: 'SURA' },
    'alternative-forms': { en: 'Alternative Forms', standard: 'Forom Alternattivi', arabised: 'Suriet Newwibija' },
    'inflected': { en: 'Inflected', standard: 'Infletta', arabised: 'Imsarrfa' },
    'term': { en: 'Term', standard: 'Terminu', arabised: 'Magħlqa' },
    'class': { en: 'Class', standard: 'Klassi', arabised: 'Taqsima' },
    'random': { en: 'Random', standard: 'Każwali', arabised: 'Kif Ġie Ġie' },
    'information': { en: 'Information', standard: 'Informazzjoni', arabised: 'Tagħrif' },
    'dictionary': { en: 'Dictionary', standard: 'Dizzjunarju', arabised: 'Miklem' },
    'comprehensive': { en: 'Comprehensive', standard: 'Komprensiv', arabised: 'Wesgħani' },
    'digital': { en: 'Digital', standard: 'Diġitali', arabised: 'Għaddieni' },
    'online': { en: 'online', standard: 'online', arabised: 'fuq linja' },
    'researchers': { en: 'researchers', standard: 'riċerkaturi', arabised: 'fittixin' },

    // Advanced Search
    'use-regular-expression': { en: 'Regex Mode', standard: 'Mod ta\' Regex', arabised: 'Mod ta\' Regex' },
    'plural-pattern': { en: 'Plural Pattern', standard: 'Mudell tal-Plural', arabised: 'Sura tal-Ġmigħ' },
    'root-consonants': { en: 'Root Consonants', standard: 'Konsonanti tal-Għerq', arabised: 'Ittri Wieqaf tal-Ġidra' },
    'vowel-set': { en: 'Vowel Set', standard: 'Sett ta\' Vokali', arabised: 'Ġmejgħa ta\' Ittri Miexi' },
    'vowel-set-perfect': { en: 'Vowel Set Perfect', standard: 'Sett ta\' Vokali Perfett', arabised: 'Ġmejgħa ta\' Ittri Miexi Tmim' },
    'vowel-set-imperfect': { en: 'Vowel Set Imperfect', standard: 'Sett ta\' Vokali Imperfett', arabised: 'Ġmejgħa ta\' Ittri Miexi Għajr Tmim' },
    'vowel-set-imperative': { en: 'Vowel Set Imperative', standard: 'Sett ta\' Vokali Imperattiv', arabised: 'Ġmejgħa ta\' Ittri Miexi Amar' },

    // Entry View
    "meaning": { en: 'Meaning', standard: 'Tifsira', arabised: 'Tagħliq' },
    "related-entries": { en: 'Related Entries', standard: 'Entrati Relatati', arabised: 'Madħliet Marbutin' },
    "transitivity": { en: 'Transitivity', standard: 'Tranżittività', arabised: 'Tgħaddija' },
    "phonetics-ipa": { en: 'Phonetics IPA', standard: 'Fonetika AFI', arabised: 'Ħossija AFI' },
    "(past)": { en: '(Past)', standard: '(Passat)', arabised: '(Mgħoddi)' },
    "(present)": { en: '(Present)', standard: '(Preżent)', arabised: '(Maħdur)' },
    "dual": { en: 'Dual', standard: 'Imtenni', arabised: 'Imtenni' },
    "entries-shown": { en: "{count} of {total} entries shown", standard: "{count} minn {total} entrati murija", arabised: "{count} minn {total} madħliet murija" },
    "search-results": { en: "Search results", standard: "Riżultati tat-tiftix", arabised: "Riżultati tat-tiftix" },
    "search-desc": { en: "Find entries and inflections in the dictionary.", standard: "Sib entrati u inflezzjonijiet fid-dizzjunarju.", arabised: "Sib madħliet u tisrifiet fil-miklem." },
    "toggle-picker": { en: "Toggle Maltese character picker", standard: "I togglja l-għażla tal-karattri Maltin", arabised: "I togglja l-għażla tal-karattri Maltin" },
    "search-lemma": { en: "Search lemma", standard: "Fittex fil-lemma", arabised: "Fittex fil-kelma" },
    "search-word-forms": { en: "Search word forms only", standard: "Fittex f'forom tal-kliem biss", arabised: "Fittex f'forom tal-kliem biss" },
    "search-english-gloss": { en: "Search in English gloss only", standard: "Fittex fit-tifsira Ingliża biss", arabised: "Fittex fit-tifsira Ingliża biss" },
    "include-suggested": { en: "Include suggested results", standard: "Inkludi riżultati ssuġġeriti", arabised: "Inkludi riżultati ssuġġeriti" },
    'max-results': { en: 'Max Results', standard: "Massimu ta' Riżultati", arabised: "L-ogħla ta' Ħsiliet" },
    "include-pending": { en: "Include pending entries", standard: "Inkludi entrati pendenti", arabised: "Inkludi entrati pendenti" },
    "include-suggested-desc": { en: "Include suggested results in the filter.", standard: "Inkludi riżultati ssuġġeriti fil-filtru.", arabised: "Inkludi riżultati ssuġġeriti fil-filtru." },
    "no-results-desc": { en: "If you think this is a mistake, feel free to suggest this term into the database.", standard: "Jekk taħseb li dan huwa żball, tħossok liberu li tissuġġerixxi dan it-terminu fid-database.", arabised: "Jekk taħseb li dan huwa għelt, int ħieles biex tissuġġerixxi dan il-magħlqa fid-database." },
    "no-results-found": { en: "No results found for '{q}'.", standard: "L-ebda riżultat ma nstab għal '{q}'.", arabised: "L-ebda riżultat ma nstab għal '{q}'." },
    "no-results-found-empty": { en: "No results found.", standard: "L-ebda riżultat ma nstab.", arabised: "L-ebda riżultat ma nstab." },
    "random-entries-desc": { en: "Showing some random entries to get you started.", standard: "Qed juru xi entrati każwali biex tibda.", arabised: "Qed juru xi madħliet kif ġie ġie biex tista' tibda." },
    "filter-options": { en: "Filter Options", standard: "Għażliet tal-Filtru", arabised: "Għażliet tal-Filtru" },
    "advanced-search-desc": { en: "Utilise our advanced search function to narrow down the search further.", standard: "Uża l-funzjoni tat-tiftix avvanzat sabiex tnaqqas ir-riżultati.", arabised: "Uża l-għan tat-tiftix avvanzat sabiex tnaqqas il-ħsiliet." },
    "eg-headword": { en: "e.g. ktieb", standard: "eż. ktieb", arabised: "eż. ktieb" },
    "eg-consonants": { en: "e.g. k-t-b", standard: "eż. k-t-b", arabised: "eż. k-t-b" },
    "theoretical": { en: "Theoretical", standard: "Teoretiku", arabised: "Ħsibi" },
    "auto-generated": { en: "Auto-generated", standard: "Iġġenerat Awtomatikament", arabised: "Imnissel Għoddi" },
    "hide-theoretical-forms": { en: "Hide theoretical forms", standard: "Aħbi forom teoretiċi", arabised: "أخفِ الأشكال النظرية" },
    "show-theoretical-forms": { en: "Show theoretical forms", standard: "Uri forom teoretiċi", arabised: "أظهر الأشكال النظرية" },
    "no-attested-data": { en: "No attested data for root {q}.", standard: "L-ebda data attestata għall-għerq {q}.", arabised: "M'hemm data attestata għall-ġidra {q} ebda." },
    "view-root-anyway": { en: "Attempt to view root page anyway →", standard: "Ipprova ara l-paġna tal-għerq xorta waħda →", arabised: "Ipprova ara l-paġna tal-ġidra xorta waħda →" },
    "root-search-desc": { en: "Explore the morphological derivation of verbs and nouns from their base triliteral and quadriliteral roots. Enter consonants below to find matching root families.", standard: "Esplora d-derivazzjoni morfoloġika ta' verbi u nomi mill-għeruq bażiċi trilitteri u kwadrilitteri. Daħħal il-konsonanti hawn taħt biex issib familji ta' għeruq kompatibbli.", arabised: "Esplora d-derivazzjoni morfoloġika ta' verbi u nomi mill-ġidriet bażiċi trilitteri u kwadrilitteri. Daħħal il-konsonanti hawn taħt biex issib familji ta' ġidriet kompatibbli." },
    "stem": { en: "Stem", standard: "Sura", arabised: "Sura" },
    "stems": { en: "Stems", standard: "Suri", arabised: "Suri" },
    "stem-search": { en: "Stem Search", standard: "Tiftix tas-Sura", arabised: "Tiftix tas-Sura" },
    "stem-search-desc": { en: "Search for loanword verbs and other stem-based entries in the dictionary.", standard: "Fittex verbi tas-selfa u entrati oħra bbażati fuq sura fil-miklem.", arabised: "Fittex verbi tas-selfa u madħliet oħra bbażati fuq sura fil-miklem." },
    "search-stems-placeholder": { en: "Enter stem or headword...", standard: "Daħħal sura jew lemma...", arabised: "Daħħal sura jew kelma..." },
    "search-another-stem": { en: "Search Another Stem", standard: "Fittex Sura Oħra", arabised: "Fittex Sura Oħra" },
    "no-stems-found": { en: "No stems found matching your search.", standard: "L-ebda sura ma nstabet li taqbel mat-tiftix tiegħek.", arabised: "L-ebda sura ma nstabet li taqbel mat-tiftix tiegħek." },
    "root-radicals": { en: "Root Radicals", standard: "Konsonanti tal-Għerq", arabised: "Ittri tal-Ġidra" },
    "etymological-relationships": { en: "Etymological Relationships", standard: "Relazzjonijiet Etimoloġiċi", arabised: "Relazzjonijiet Etimoloġiċi" },
    "search-roots": { en: "Search Roots", standard: "Fittex l-Għeruq", arabised: "Fittex il-Ġidriet" },
    "clear": { en: "Clear", standard: "Ħassar", arabised: "Ħassar" },
    "edit-root-metadata": { en: "Edit Root Metadata", standard: "Editja l-Metadata tal-Għerq", arabised: "Editja l-Metadata tal-Ġidra" },
    "add-entry": { en: "Add Entry", standard: "Żid l-Entrata", arabised: "Żid il-Madħla" },
    "delete-entry": { en: "Delete Entry", standard: "Ħassar l-Entrata", arabised: "Ħassar il-Madħla" },
    "confirm-delete-entry": { en: "Are you sure you want to delete this entry permanently?", standard: "Żgur li trid tħassar din l-entrata b'mod permanenti?", arabised: "Żgur li trid tħassar din il-madħla b'mod permanenti?" },
    "confirm-unlink": { en: "Are you sure you want to unlink this relationship?", standard: "Żgur li trid tneħħi din ir-relazzjoni?", arabised: "Żgur li trid tneħħi din ir-relazzjoni?" },
    "failed-delete-entry": { en: "Failed to delete entry: ", standard: "Il-ħassir tal-entrata falla: ", arabised: "Il-ħassir tal-madħla falla: " },
    "failed-update-rel": { en: "L-aġġornament tar-relazzjoni falla: ", standard: "L-aġġornament tar-relazzjoni falla: ", arabised: "L-aġġornament tar-relazzjoni falla: " },
    "back-to-root-search": { en: "Back to Root Search", standard: "Irġa' Lura lejn it-Tiftix tal-Għerq", arabised: "Irġa' Lura lejn it-Tiftix tal-Ġidra" },
    "root-not-found": { en: "Root not found", standard: "L-Għerq ma nstabx", arabised: "Il-Ġidra ma nstabitx" },
    "root-not-found-desc": { en: "The root '{id}' ma nstabx fid-database tagħna. Jekk taħseb li dan l-għerq għandu jeżisti, tista' tsuġġerih biex jiżdied.", standard: "L-għerq '{id}' ma nstabx fid-database tagħna. Jekk taħseb li dan l-għerq għandu jeżisti, tista' tsuġġerih biex jiżdied.", arabised: "Il-ġidra '{id}' ma nstabitx fid-database tagħna. Jekk taħseb li din il-ġidra għandha teżisti, tista' tsuġġerilha biex tiżdied." },
    "suggest-adding-root": { en: "Suggest Adding Root", standard: "Issuġġerixxi Żieda ta' Għerq", arabised: "Issuġġerixxi Żieda ta' Ġidra" },
    "search-another-root": { en: "Search Another Root", standard: "Fittex Għerq Ieħor", arabised: "Fittex Ġidra Oħra" },
    "derived": { en: "Derived", standard: "Derivat", arabised: "Imħarreġ" },
    "related": { en: "Related", standard: "Relatat", arabised: "Marbut" },
    "manage-derived": { en: "Manage Derived Terms", standard: "Ġestjoni tat-Termini Derivati", arabised: "Ġestjoni tat-Termini Mħarrġa" },
    "manage-thesaurus": { en: "Manage Thesaurus", standard: "Ġestjoni tat-Teżawru", arabised: "Ġestjoni tat-Teżawru" },
    "link-derived-desc": { en: "Link derived entries to this root. Enter the entry ID and press Enter to confirm.", standard: "Aġġanċja entrati derivati ma' dan l-għerq. Ikteb l-ID u agħfas Enter biex tikkonferma.", arabised: "Orbot madħliet imħarrġa ma' din il-ġidra. Ikteb l-ID u agħfas Enter biex twettaq." },
    "link-thesaurus-desc": { en: "Link synonym and antonym roots. Enter the root consonants and press Enter to confirm.", standard: "Aġġanċja għeruq sinonimi u antonimi. Ikteb l-għerq u agħfas Enter biex tikkonferma.", arabised: "Orbot ġidriet sinonimi u antonimi. Ikteb il-ġidra u agħfas Enter biex twettaq." },
    "new-entry": { en: "New Entry", standard: "Entrata Ġdida", arabised: "Madħla Ġdida" },
    "new-root": { en: "New Root", standard: "Għerq Ġdid", arabised: "Ġidra Ġdida" },
    "cancel": { en: "Cancel", standard: "Ikkanċella", arabised: "Ikkanċella" },
    "save-changes": { en: "Save Changes", standard: "Issevja l-Bidliet", arabised: "Issevja l-Bidliet" },
    "failed-save-rels": { en: "L-isseyvjar tar-relazzjonijiet falla: ", standard: "L-isseyvjar tar-relazzjonijiet falla: ", arabised: "L-isseyvjar tar-relazzjonijiet falla: " },
    "email-placeholder": { en: "name@example.com", standard: "isem@eżempju.com", arabised: "isem@xbieha.com" },
    "back-to-search": { en: "Back to Search", standard: "Irġa' Lura lejn it-Tiftix", arabised: "Irġa' Lura lejn it-Tiftix" },
    "from": { en: "From", standard: "Minn", arabised: "Minn" },
    "edit-entry": { en: "Edit Entry", standard: "Editja l-Entrata", arabised: "Editja l-Madħla" },
    "gloss": { en: "Gloss", standard: "Tifsira", arabised: "Tagħliq" },
    "internal-metadata": { en: "Internal Metadata", standard: "Metadata Interna", arabised: "Metadata Interna" },
    "imala-blocked": { en: "Blocked Imala", standard: "Imala Mblukkata", arabised: "Imala Mblukkata" },
    "yes": { en: "Yes", standard: "Iva", arabised: "Iva" },
    "no": { en: "No", standard: "Le", arabised: "Le" },
    "entry-not-found": { en: "Entry not found", standard: "L-Entrata ma nstabitx", arabised: "Il-Madħla ma nstabitx" },
    "entry-not-found-desc": { en: "The entry '{id}' ma nstabitx fid-database tagħna. Jekk taħseb li din l-entrata għandha teżisti, tista' tsuġġerilha biex tiżdied.", standard: "L-entrata '{id}' ma nstabitx fid-database tagħna. Jekk taħseb li din l-entrata għandha teżisti, tista' tsuġġerilha biex tiżdied.", arabised: "Il-madħla '{id}' ma nstabitx fid-database tagħna. Jekk taħseb li din il-madħla għandha teżisti, tista' tsuġġerilha biex tiżdied." },
    "suggest-adding-entry": { en: "Suggest Adding Entry", standard: "Issuġġerixxi Żieda ta' Entrata", arabised: "Issuġġerixxi Żieda ta' Madħla" },
    "full-entry-view-coming-soon": { en: "Full entry view for {pos} coming soon.", standard: "Il-veduta sħiħa għal {pos} ġejja dalwaqt.", arabised: "Il-veduta sħiħa għal {pos} ġejja dalwaqt." },
    "search-placeholder": { en: "Search...", standard: "Fittex...", arabised: "Fittex..." },
    "toggle-terminology-standard": { en: "Switch to Standard CV terminology", standard: "Aqleb għat-terminoloġija Standard CV", arabised: "Aqleb għat-terminoloġija Standard CV" },
    "toggle-terminology-arabised": { en: "Switch to Arabised وزن terminology", standard: "Aqleb għat-terminoloġija Għarbija وزن", arabised: "Aqleb għat-terminoloġija Għarbija وزن" },
    "toggle-language-mt": { en: "Switch to Maltese language", standard: "Aqleb għal-lingwa Maltija", arabised: "Aqleb għal-lingwa Maltija" },
    "toggle-language-en": { en: "Switch to English language", standard: "Aqleb għal-lingwa Ingliża", arabised: "Aqleb għal-lingwa Ingliża" },
    "toggle-light-mode": { en: "Switch to light mode", standard: "Aqleb għall-modalità ċar", arabised: "Aqleb għall-modalità dawli" },
    "toggle-dark-mode": { en: "Switch to dark mode", standard: "Aqleb għall-modalità skur", arabised: "Aqleb għall-modalità dalmi" },
    "headword": { en: "Headword", standard: "Lemma", arabised: "Ras il-Kelma" },
    "back": { en: "Back", standard: "Lura", arabised: "Irġa'" },
    "suggest-addition": { en: "Suggest Addition", standard: "Issuġġerixxi Żieda", arabised: "Issuġġerixxi Żieda" },
    "type": { en: "Type", standard: "Tip", arabised: "Għamla" },
    "suggest-desc": { en: "Help us improve by suggesting a new entry or root.", standard: "Għinna ntejbu billi tissuġġerixxi entrata jew għerq ġdid.", arabised: "Għinna ntejbu billi tissuġġerixxi madħla jew ġidra ġdida." },
    "additional-notes": { en: "Additional Notes", standard: "Noti Addizzjonali", arabised: "Noti Addizzjonali" },
    "provide-meanings": { en: "Provide meanings, examples, or sources...", standard: "Ipprovdi tifsiriet, eżempji, jew sorsi...", arabised: "Midd tifsiriet, xbihat, jew mirġgħat..." },
    "your-email": { en: "Your Email (optional)", standard: "L-Email Tiegħek (mhux obbligatorja)", arabised: "L-Email Tiegħek (mhux ħtari)" },
    "submit-suggestion": { en: "Submit Suggestion", standard: "Ibgħat is-Suġġeriment", arabised: "Ibgħat is-Suġġeriment" },
    "thank-you": { en: "Thank You!", standard: "Grazzi!", arabised: "Grazzi!" },
    "suggestion-received": { en: "Your suggestion has been received and will be reviewed by our team.", standard: "Is-suġġeriment tiegħek jinwasal u se jiġi rivedut mit-tim tagħna.", arabised: "Is-suġġeriment tiegħek jinwasal u se jrieġa' mill-fariq tagħna." },
    "back-to-home": { en: "Back to Home", standard: "Lura għad-Dar", arabised: "Irġa' lid-Dar" },
    "submit-feedback": { en: "Submit Feedback", standard: "Ibgħat Feedback", arabised: "Ibgħat Feedback" },
    "feedback-desc": { en: "Tell us about bugs, broken links, missing content, or anything else we should improve.", standard: "Għidilna dwar bugs, links miksura, kontenut nieqes, jew kull ħaġa oħra li għandna ntejbu.", arabised: "Għidilna dwar bugs, links miksura, kontenut nieqes, jew kull ħaġa oħra li għandna ntejbu." },
    "feedback-type-general": { en: "General", standard: "Ġenerali", arabised: "Ġenerali" },
    "feedback-type-bug": { en: "Bug / Error", standard: "Żball / Bug", arabised: "Żball / Bug" },
    "feedback-type-content": { en: "Content issue", standard: "Problema fil-kontenut", arabised: "Problema fil-kontenut" },
    "feedback-type-feature": { en: "Feature request", standard: "Talba għal karatteristika", arabised: "Talba għal karatteristika" },
    "feedback-subject-placeholder": { en: "e.g. Search page, an entry, or a button", standard: "eż. il-paġna ta' tiftix, entrata, jew buttuna", arabised: "eż. il-paġna tat-tiftix, madħla, jew buttuna" },
    "feedback-notes-placeholder": { en: "Tell us what happened and what you expected instead.", standard: "Għidilna x'ġara u x'kont tistenna minflok.", arabised: "Għidilna x'ġara u x'kont tistenna minflok." },
    "feedback-received": { en: "Thanks, your feedback has been received and will be reviewed by the team.", standard: "Grazzi, il-feedback tiegħek wasal u se jiġi rivedut mit-tim.", arabised: "Grazzi, il-feedback tiegħek wasal u se jiġi rivedut mit-tim." },
    "feedback-submit-failed": { en: "We could not save that submission right now. Please try again.", standard: "Ma stajniex nissejvjaw din is-sottomissjoni bħalissa. Erġa' pprova.", arabised: "Ma stajniex nissejvjaw din is-sottomissjoni bħalissa. Erġa' pprova." },
    "sign-in": { en: "Sign in", standard: "Idħol", arabised: "Idħol" },
    "toggle-menu": { en: "Toggle menu", standard: "Ittogglja l-menu", arabised: "Ittogglja l-menu" },
    "user-view": { en: "User View", standard: "Veduta tal-Utent", arabised: "Nadar tal-Utent" },
    "admin-view": { en: "Admin View", standard: "Veduta tal-Amministratur", arabised: "Nadar tal-Amministratur" },
    "system-role-admin": { en: "Admin Access", standard: "Aċċess għall-Amministratur", arabised: "Usul għall-Amministratur" },
    "admin-dashboard": { en: "Admin Dashboard", standard: "Dashboard tal-Amministratur", arabised: "Bord tat-Taħkim tal-Amministratur" },
    "tier": { en: "Tier", standard: "Livell", arabised: "Livell" },
    "management-panel": { en: "Management Panel", standard: "Panel tal-Ġestjoni", arabised: "Panel tat-Tmexxija" },
    "live-site": { en: "Live Site", standard: "Sajt Dirett", arabised: "Sajt Ħaj" },
    "root-management": { en: "Root Management", standard: "Ġestjoni tal-Għeruq", arabised: "Ġestjoni tal-Ġidriet" },
    "word-entries": { en: "Word Entries", standard: "Entrati tal-Kliem", arabised: "Madħliet il-Kliem" },
    "content-and-blog": { en: "Content & Blog", standard: "Kontenut u Blogg", arabised: "Kontenut u Mkittba" },
    "quick-search-verification": { en: "Quick Search Verification", standard: "Verifikazzjoni tat-Tiftix Rapidu", arabised: "Verifikazzjoni tat-Tiftix Rapidu" },
    "check": { en: "Check", standard: "Iċċekkja", arabised: "Iċċekkja" },
    "browse-entries": { en: "Browse Entries", standard: "Ibbrawżja l-Entrati", arabised: "Għarbel il-Madħliet" },
    "random-entry": { en: "Random Entry", standard: "Entrata Kazwali", arabised: "Madħla Kif Ġie Ġie" },
    "browse-mode": { en: "Browse mode", standard: "Mod ta' bbrawżjar", arabised: "Mod ta' għarbiel" },
    "browse-by-pos": { en: "Browse by POS", standard: "Ibbrawżja skont il-POS", arabised: "Għarbel skont il-POS" },
    "browse-by-pattern": { en: "Browse by Pattern", standard: "Ibbrawżja skont il-Mudell", arabised: "Għarbel skont il-Mudell" },
    "browse-by-source": { en: "Browse by Source", standard: "Ibbrawżja skont is-Sors", arabised: "Għarbel skont is-Sors" },
    "browse-by-suffix": { en: "Browse by Suffix", standard: "Ibbrawżja skont is-Suffiss", arabised: "Għarbel skont is-Suffiss" },
    "all": { en: "All", standard: "Kollox", arabised: "Kollox" },
    "browse-facets-desc": { en: "Explore the dictionary through morphology and etymology source groupings.", standard: "Esplora d-dizzjunarju permezz tal-morfoloġija u l-gruppi tas-sors etimoloġiku.", arabised: "Esplora l-miklem permezz tal-morfoloġija u l-gruppi tas-sors etimoloġiku." },
    "browse-pattern-summary": { en: "Showing {count} patterns across {groups} groups.", standard: "Qed jintwerew {count} mudelli f'{groups} gruppi.", arabised: "Qed jintwerew {count} wiżien f'{groups} ġabriet." },
    "browse-pattern-empty": { en: "No patterns found for this POS.", standard: "L-ebda mudell ma nstab għal dan il-POS.", arabised: "L-ebda wiżen ma nstab għal dan il-POS." },
    "browse-by-source-desc": { en: "Explore entries by language of origin and jump straight into the related search results.", standard: "Esplora l-entrati skont il-lingwa ta' oriġini u aqbeż direttament għar-riżultati relatati tat-tiftix.", arabised: "Esplora l-madħliet skont l-ilsien tal-oriġini u aqbeż direttament għar-riżultati relatati tat-tiftix." },
    "browse-by-suffix-desc": { en: "Explore entries by inflectional and derivational endings.", standard: "Esplora l-entrati skont it-tmiem inflessjonali u dderivati.", arabised: "Esplora l-madħliet skont it-tmiem inflessjonali u dderivattiv." },
    "browse-suffix-summary": { en: "Showing {count} entries for {suffix}.", standard: "Qed jintwerew {count} entrata għal {suffix}.", arabised: "Qed jintwerew {count} madħla għal {suffix}." },
    "browse-suffix-empty": { en: "No entries found for this suffix.", standard: "L-ebda entrata ma nstabet għal dan is-suffiss.", arabised: "L-ebda madħla ma nstabet għal dan is-suffiss." },
    "browse-by-morphology": { en: "Browse by morphology", standard: "Ibbrawżja skont il-morfoloġija", arabised: "Għarbel skont il-morfoloġija" },
    "browse-view-mode": { en: "Browse view mode", standard: "Mod tal-veduta tal-brawżjar", arabised: "Mod tal-veduta tal-għarbiel" },
    "nominal-suffixes": { en: "Nominal Suffixes", standard: "Suffissi Nominali", arabised: "Suffissi Nominali" },
    "derivational-suffixes": { en: "Derivational Suffixes", standard: "Suffissi Dderivati", arabised: "Suffissi Dderivati" },
    "sound-plural": { en: "Sound Plural", standard: "Plural Sħiħ", arabised: "Ġmigħ Sħiħ" },
    "abstract-nouns": { en: "Abstract Nouns", standard: "Nomi Astratti", arabised: "Ismijiet Astratti" },
    "browse-by-letter": { en: "Browse by Letter", standard: "Ibbrawżja skont l-Ittra", arabised: "Għarbel skont l-Ittra" },
    "all-pos": { en: "All {pos}", standard: "Il-{pos} Kollha", arabised: "Il-{pos} Kollha" },
    "verb-forms-title": { en: "Verb Forms", standard: "Forom tal-Verbi", arabised: "Użien il-Fagħal" },

    // Navbar Specific
    'advanced-search': { en: "Advanced Search", standard: "Tiftix Avvanzat", arabised: "Tiftix Mitqaddam" },
    'root-search': { en: "Root Search", standard: "Tiftix tal-Għerq", arabised: "Tiftix tal-Ġidra" },
    'suggest-entry': { en: "Suggest Entry", standard: "Issuġġerixxi Entrata", arabised: "Issuġġerixxi Madħla" },
    'help': { en: 'Help', standard: 'Għajnuna', arabised: 'Għajnuna' },

    // Home Page
    'dictionary-title': { en: "A Comprehensive Digital Maltese-English Dictionary", standard: "Dizzjunarju u Konjugatur Komprensiv Diġitali Malti-Ingliż", arabised: "Miklem u Sarraf Wesgħani Diġitali Malti-Ingliż" },
    'home-desc': { en: "An ever-growing {online} tool for learners and researchers to the meaning, history, and usage of {count} words in Maltese and its dialects.", standard: "Għodda {online} li dejjem tikber għal dawk li jitgħallmu u għar-riċerkaturi dwar it-tifsira, l-istorja u l-użu ta' {count} kelma bil-Malti u bid-djaletti tiegħu.", arabised: "Għodda {online} li dejjem tikber għal dawk li jitgħallmu u għall-fittixin dwar it-tagħliq, l-oriġini u l-użu ta' {count} kelma bil-Malti u l-lsejnin tiegħu." },
    'ipa-audio-title': { en: "IPA & Audio Pronunciation", standard: "IPA u Pronunzja bl-Awdjo", arabised: "IPA u Tlissin bil-Ħoss" },
    'ipa-audio-desc': { en: "Every term will have its own IPA and audio to help learners.", standard: "Kull terminu se jkollu l-IPA u l-awdjo tiegħu biex jgħin lil dawk li jitgħallmu.", arabised: "Kull magħlqa se jkollha l-IPA u ħossha biex tgħin lil dawk li jitgħallmu." },
    'welcome-admin': { en: "Welcome back Admin {name}!", standard: "Merħba lura Admin {name}!", arabised: "Merħba lura Admin {name}!" },
    'root-mgmt-desc': { en: "Manage your consonants, etymology, and derived roots from one point.", standard: "Immaniġġja l-konsonanti, l-etimoloġija, u l-għeruq derivati tiegħek minn punt wieħed.", arabised: "Immaniġġja l-konsonanti, l-oriġini, u l-ġidriet imħarrġa tiegħek minn punt wieħed." },
    'word-entries-desc': { en: "Add new words, update meanings and IPA in your library of {count} entries.", standard: "Żid kliem ġdid, aġġorna t-tifsiriet u l-IPA fil-librerija tiegħek ta' {count} entrati.", arabised: "Żid kliem ġdid, aġġorna t-tagħliq u l-IPA fil-librerija tiegħek ta' {count} madħliet." },
    'content-blog-desc': { en: "Publish new articles and add usage examples to enhance the user experience.", standard: "Ippubblika artikli ġodda u żid eżempji ta' użu biex ttejjeb l-esperjenza tal-utent.", arabised: "Ippubblika artikli ġodda u żid tixbihat ta' użu biex ttejjeb l-esperjenza tal-utent." },
    'root-mgmt-open': { en: "Open Root Management", standard: "Iftaħ Ġestjoni tal-Għeruq", arabised: "Iftaħ Ġestjoni tal-Ġidriet" },
    'manage-entries': { en: "Manage Entries", standard: "Immaniġġja l-Entrati", arabised: "Immaniġġja l-Madħliet" },
    'edit-blog': { en: "Edit Blog", standard: "Editja Blogg", arabised: "Editja Mkittba" },
    'quick-search-verification-desc': { en: "Quickly search to verify if a word is already in the database before adding it.", standard: "Fittex malajr biex tivverifika jekk kelma hix diġà fid-database qabel ma żżidha.", arabised: "Fittex malajr biex tivverifika jekk kelma hix diġà fid-database qabel ma żżidha." },
    'search-word-placeholder': { en: "Search for a word...", standard: "Fittex kelma...", arabised: "Fittex kelma..." },
    'semitic-entries-title': { en: "Semitic Entries", standard: "Entrati Semitiċi", arabised: "Madħliet Semin" },
    'romance-entries-title': { en: "Romance Entries", standard: "Entrati Rumanzi", arabised: "Madħliet Rumanzi" },
    'semitic-entries-desc': { en: "Over 10,000 entries with 100,000 inflected word forms.", standard: "Aktar minn 10,000 entrati b'100,000 forma ta' kelma infletta.", arabised: "Aktar minn 10,000 madħla b'100,000 sura ta' kelma imsarrfa." },
    'romance-entries-desc': { en: "Over 10,000 entries with 98,000 inflected word forms.", standard: "Aktar minn 10,000 entrati b'98,000 forma ta' kelma infletta.", arabised: "Aktar minn 10,000 madħla b'98,000 sura ta' kelma imsarrfa." },
    'home-random-title': { en: "Random Entry", standard: "Entrata Każwali", arabised: "Madħla Kif Ġie Ġie" },
    'home-browse-title': { en: "Browse Entries", standard: "Ibbrawżja l-Entrati", arabised: "Għarbel il-Madħliet" },
    'results-for': { en: "Results for '{q}'", standard: "Riżultati għal '{q}'", arabised: "Riżultati għal '{q}'" },
    'entries-shown-simple': { en: "{count} results shown", standard: "{count} riżultati murija", arabised: "{count} ħsiliet murija" },
    'advanced-search-title': { en: "Advanced Search", standard: "Tiftix Avvanzat", arabised: "Tiftix Mitqaddam" },

    // Blog
    'blog': { en: "Blog", standard: "Blogg", arabised: "Imkittba" },
    'blog-desc': { en: "Articles about the Maltese language, etymology, and linguistic research.", standard: "Artikli dwar il-lingwa Maltija, l-etimoloġija, u r-riċerka lingwistika.", arabised: "Artikli dwar l-ilsien Malti, it-tnissil tal-kliem, u r-riċerka lsinija." },
    'blog-post': { en: "Blog Article", standard: "Artiklu tal-Blogg", arabised: "Artiklu tal-Imkittba" },
    'back-to-blog': { en: "Back to Blog", standard: "Lura għall-Blogg", arabised: "Erġa' għall-Imkittba" },

    // Conjugator
    'conjugator-desc': { en: "Enter a verb in the 3sg.m perfect form (e.g. kiteb, niżel, fetaħ).", standard: "Daħħal verb fil-forma 3sg.m perfett (eż. kiteb, niżel, fetaħ).", arabised: "Daħħal verb fis-sura tat-3 pers. mt. mm. tat-tmim (eż. kiteb, niżel, fetaħ)." },
    'eg-kiteb': { en: "e.g. kiteb", standard: "eż. kiteb", arabised: "eż. kiteb" },
    'conjugate': { en: "Conjugate", standard: "Ikkonjuga", arabised: "Sarraf" },
    'conjugator-demo-warning': { en: "Demo: currently only gives the CaCaC form (kiteb). Full Conjugator coming soon.", standard: "Demo: bħalissa jagħti biss il-forma CaCaC (kiteb). Il-Konġugatur sħiħ jiġi dalwaqt.", arabised: "Demo: bħalissa jagħti t-tisrif fis-sura ta' fagħal (forma I) biss. Is-Sarraf kollu jiġi daqt." },
    'basic': { en: "Basic", standard: "Bażiku", arabised: "Siesi" },

    // Is-Semmej
    'semmej-title': { en: "Is-Semmej — Name Generator", standard: "Is-Semmej — Ġeneratur tal-Ismijiet", arabised: "Is-Semmej — Nissiel l-Ismijiet" },
    'semmej-desc': { en: "Give a description of something, and Is-Semmej will create a genuine Maltese name.", standard: "Agħti deskrizzjoni ta' xi ħaġa, u s-Semmej joħloq isem Malti ġenwin.", arabised: "Agħti tifsira ta' xi ħaġa, u s-Semmej joħloq isem Malti b'qalbu u b'ruħu." },
    'semmej-label-desc': { en: "Concept Description *", standard: "Deskrizzjoni tal-Kunċett *", arabised: "Tifsira tal-Maħsub *" },
    'semmej-label-roots': { en: "Preferred Roots (comma-separated, optional)", standard: "Għeruq Preferiti (b'virgola, fakultattiv)", arabised: "Ġidriet Magħżula (b'virgola, mhux bil-fors)" },
    'semmej-btn': { en: "Create name", standard: "Semmi", arabised: "Semmi" },
    'semmej-suggestions': { en: "Suggestions", standard: "Suġġerimenti", arabised: "Suġġerimenti" },

    // Not Found
    'page-not-found': { en: "Page Not Found", standard: "Il-Paġna Ma Nstabetx", arabised: "Il-Paġna Ma Nstabetx" },
    'page-not-found-desc': { en: "This page does not exist. Perhaps the URL is incorrect or it has been removed.", standard: "Din il-paġna ma teżistix. Forsi l-URL mhix korretta jew tħassret.", arabised: "Din il-paġna ma teżistix. Forsi l-URL mhix korretta jew tħassret." },
    'go-back-home': { en: "Go Back Home", standard: "Mur Lura lejn id-Dar", arabised: "Mur Lura lejn id-Dar" },
    'search-dictionary': { en: "Search Dictionary", standard: "Fittex fid-Dizzjunarju", arabised: "Fittex fil-Miklem" },
    'maltese': { en: 'Maltese', standard: 'Malti', arabised: 'Malti' },
    'this-word': { en: 'this word', standard: 'din il-kelma', arabised: 'dil-kelma' },

    // Admin
    'admin-warning': {
        en: "The system does not recognize you as an official Admin in Clerk Metadata. We are letting you in for testing for now.",
        standard: "Is-sistema ma tagħrfekx bħala Admin uffiċjali fil-Clerk Metadata. Għalissa qed inħalluk tidħol biex tittestja.",
        arabised: "Is-sistema ma tagħrfekx bħala Admin uffiċjali fil-Clerk Metadata. Għalissa qed inħalluk tidħol biex tittestja."
    },
    'bulk-delete-confirm': { en: "Are you sure you want to delete {count} items? This cannot be undone.", standard: "Żgur li trid tħassar {count} oġġett? Din ma tistax tinqaleb.", arabised: "Żgur li trid tħassar {count} oġġett? Din ma tistax tinqaleb." },
    'delete-entry-confirm': { en: "DELETE \"{headword}\"? This cannot be undone.", standard: "ĦASSAR \"{headword}\"? Din ma tistax tinqaleb.", arabised: "ĦASSAR \"{headword}\"? Din ma tistax terġa'." },
    'delete-root-confirm': { en: "Are you sure you want to delete the root {cons}?", standard: "Żgur li trid tħassar l-għerq {cons}?", arabised: "Żgur li trid tħassar l-għerq {cons}?" },
    'items-deleted': { en: "{count} items deleted", standard: "{count} oġġett imħassar", arabised: "{count} oġġett imħassar" },
    'entry-deleted': { en: "\"{headword}\" deleted", standard: "\"{headword}\" imħassra", arabised: "\"{headword}\" imħassra" },
    'attention': { en: "Attention:", standard: "Attenzjoni:", arabised: "Intbiħ:" },
    'dashboard': { en: "Dashboard", standard: "Dashboard", arabised: "Dashboard" },
    'refresh': { en: "Refresh", standard: "Aġġorna", arabised: "Ġedded" },
    'add-new': { en: "Add New", standard: "Żid Ġdid", arabised: "Żid Ġdid" },
    'any-role': { en: "Any Role", standard: "Kull Rwol", arabised: "Kull Rwol" },
    'bucket': { en: "Bucket", standard: "Kontenitur", arabised: "Kontenitur" },
    'custom-role': { en: "Custom role…", standard: "Rwol personalizzat…", arabised: "Rwol personalizzat…" },
    'development-tip-sync-to-code': { en: "Development Tip: Sync to Code", standard: "Tip ta' Żvilupp: Sinkronizza mal-Kodiċi", arabised: "Tip ta' Żvilupp: Sinkronizza mal-Kodiċi" },
    'export-to-ts': { en: "Export to TS", standard: "Esporta għal TS", arabised: "Esporta għal TS" },
    'import-from-source': { en: "Import from Source", standard: "Iġbor mis-Sors", arabised: "Iġbor mis-Sors" },
    'metadata-for-this-pos': { en: "Metadata for this POS", standard: "Metadejta għal dan il-POS", arabised: "Metadejta għal dan il-POS" },
    'metadata-for-this-role': { en: "Metadata for this role", standard: "Metadejta għal dan ir-rwol", arabised: "Metadejta għal dan ir-rwol" },
    'derived-key': { en: "Derived Key", standard: "Key derivata", arabised: "Key derivata" },
    'english-display-name': { en: "English display name...", standard: "Isem viżibbli bl-Ingliż...", arabised: "Isem viżibbli bl-Ingliż..." },
    'english-label': { en: "English Label", standard: "Tikketta bl-Ingliż", arabised: "Tikketta bl-Ingliż" },
    'form-name': { en: "Form Name", standard: "Isem il-formola", arabised: "Isem il-formola" },
    'keyboard-helper': { en: "Keyboard Helper", standard: "Għajnuna tat-Tastiera", arabised: "Għajnuna tat-Tastiera" },
    'close-keyboard': { en: "Close Keyboard", standard: "Agħlaq it-Tastiera", arabised: "Agħlaq it-Tastiera" },
    'open-keyboard': { en: "Open Keyboard", standard: "Iftaħ it-Tastiera", arabised: "Iftaħ it-Tastiera" },
    'translations-display-labels': { en: "Translations / Display Labels", standard: "Traduzzjonijiet / Tikketti viżibbli", arabised: "Traduzzjonijiet / Tikketti viżibbli" },
    'maltese-arabised-label': { en: "Maltese (Wizen / Arabised)", standard: "Malti (Wiżen / Arabised)", arabised: "Malti (Wiżen / Arabised)" },
    'maltese-standard-label': { en: "Maltese (CV / Standard)", standard: "Malti (CV / Standard)", arabised: "Malti (CV / Standard)" },
    'maltese-standard-label-hint': { en: "(v = short, V = long vowel)", standard: "(v = qasira, V = twila)", arabised: "(v = qasira, V = twila)" },
    'standard-maltese-label': { en: "Standard Maltese label...", standard: "Tikketta bil-Malti Standard...", arabised: "Tikketta bil-Malti Standard..." },
    'arabised-maltese-label': { en: "Arabised Maltese label...", standard: "Tikketta bil-Malti Arabised...", arabised: "Tikketta bil-Malti Arabised..." },
    'standard-cv': { en: "Standard (CV)", standard: "Standard (CV)", arabised: "Standard (CV)" },
    'arabised-wizen': { en: "Arabised (Wizen)", standard: "Arabised (Wiżen)", arabised: "Arabised (Wiżen)" },
    'cv-notation': { en: "CV notation", standard: "Notazzjoni CV", arabised: "Notazzjoni CV" },
    'wizen-name': { en: "Wizen name", standard: "Isem tal-Wiżen", arabised: "Isem tal-Wiżen" },
    'description': { en: "Description", standard: "Deskrizzjoni", arabised: "Deskrizzjoni" },
    'optional-pattern-description': { en: "Optional pattern description...", standard: "Deskrizzjoni opzjonali tal-mudell...", arabised: "Deskrizzjoni opzjonali tal-mudell..." },
    'apply-to-pos': { en: "Apply to POS", standard: "Applika għall-POS", arabised: "Applika għall-POS" },
    'selected-count': { en: "{count} selected", standard: "{count} magħżul", arabised: "{count} magħżul" },
    'per-pos': { en: "Per POS", standard: "Skont il-POS", arabised: "Skont il-POS" },
    'pick-one-or-more-pos-above-to-edit-their-metadata': { en: "Pick one or more POS above to edit their metadata.", standard: "Agħżel POS wieħed jew aktar biex teditja l-metadejta tagħhom.", arabised: "Agħżel POS wieħed jew aktar biex teditja l-metadejta tagħhom." },
    'set-cv-and-wizen-to-generate-the-key': { en: "Set CV and Wizen to generate the key", standard: "Imla CV u Wiżen biex tinħoloq il-key", arabised: "Imla CV u Wiżen biex tinħoloq il-key" },
    'cv-or-wizen-is-required': { en: "CV or Wizen is required", standard: "CV jew Wiżen huwa meħtieġ", arabised: "CV jew Wiżen huwa meħtieġ" },
    'key-is-required': { en: "Key is required", standard: "Key hija meħtieġa", arabised: "Key hija meħtieġa" },
    'shared-pattern-base-desc': { en: "CV, Wizen, stress, and description stay shared while POS applicability is edited below.", standard: "CV, Wiżen, stress u deskrizzjoni jibqgħu komuni waqt li l-applikabbiltà tal-POS tiġi editjata hawn taħt.", arabised: "CV, Wiżen, stress u deskrizzjoni jibqgħu komuni waqt li l-applikabbiltà tal-POS tiġi editjata hawn taħt." },
    'no-roles-yet-for-this-pos': { en: "No roles yet for this POS. Add one to start editing.", standard: "Għad m'hemmx rwoli għal dan il-POS. Żid wieħed biex tibda teditja.", arabised: "Għad m'hemmx rwoli għal dan il-POS. Żid wieħed biex tibda teditja." },
    'roles-in-this-pos': { en: "{count} roles in this POS", standard: "{count} rwoli f'dan il-POS", arabised: "{count} rwoli f'dan il-POS" },
    'type-a-new-linguistic-role': { en: "Type a new linguistic role...", standard: "Ikteb rwol lingwistiku ġdid...", arabised: "Ikteb rwol lingwistiku ġdid..." },
    'no-matches-found': { en: "No matches found", standard: "Ma nstab l-ebda qbil", arabised: "Ma nstab l-ebda qbil" },
    'pattern-identity': { en: "Pattern Identity", standard: "Identità tal-mudell", arabised: "Identità tal-mudell" },
    'pattern-identity-desc': { en: "The saved key is composed from the surface forms below, so the record stays aligned with the pattern it describes.", standard: "Il-key salvata hija magħmula mill-forom ta' taħt, sabiex ir-rekord jibqa' mqabbel mal-mudell li jiddeskrivi.", arabised: "Il-key salvata hija magħmula mill-forom ta' taħt, sabiex ir-rekord jibqa' mqabbel mal-mudell li jiddeskrivi." },
    'pattern-only-role': { en: "Pattern-only role", standard: "Rwol għall-mudell biss", arabised: "Rwol għall-mudell biss" },
    'pattern-role-no-extra-metadata': { en: "This role can still be linked to patterns, but it does not use extra applicability metadata.", standard: "Dan ir-rwol xorta jista' jkun marbut ma' mudelli, iżda ma jużax metadejta addizzjonali dwar l-applikabbiltà.", arabised: "Dan ir-rwol xorta jista' jkun marbut ma' mudelli, iżda ma jużax metadejta addizzjonali dwar l-applikabbiltà." },
    'pos-applicability': { en: "POS Applicability", standard: "Applikabbiltà tal-POS", arabised: "Applikabbiltà tal-POS" },
    'pos-applicability-desc': { en: "Rendered from the selected POS schema", standard: "Mibni mill-iskema tal-POS magħżula", arabised: "Mibni mill-iskema tal-POS magħżula" },
    'identity': { en: "Identity", standard: "Identità", arabised: "Identità" },
    'in-code-id-key': { en: "In-code ID / Key", standard: "ID / Key fil-kodiċi", arabised: "ID / Key fil-kodiċi" },
    'label-is-required': { en: "Label is required.", standard: "It-tikketta hija meħtieġa.", arabised: "It-tikketta hija meħtieġa." },
    'save-config': { en: "Save Config", standard: "Issejvja l-konfigurazzjoni", arabised: "Issejvja l-konfigurazzjoni" },
    'save-suffix': { en: "Save Suffix", standard: "Issejvja Suffiss", arabised: "Issejvja Suffiss" },
    'saving': { en: "Saving...", standard: "Qed jiġi ssejvjat...", arabised: "Qed jiġi ssejvjat..." },
    'search-items': { en: "Search items...", standard: "Fittex oġġetti...", arabised: "Fittex oġġetti..." },
    'select-placeholder': { en: "-- Select --", standard: "-- Agħżel --", arabised: "-- Agħżel --" },
    'shared-pattern-base': { en: "Shared Pattern Base", standard: "Bażi komuni tal-mudell", arabised: "Bażi komuni tal-mudell" },
    'specific-configuration': { en: "Specific Configuration", standard: "Konfigurazzjoni Speċifika", arabised: "Konfigurazzjoni Speċifika" },
    'stress-label': { en: "Stress (syllable from end)", standard: "Aċċent (sillaba mill-aħħar)", arabised: "Aċċent (sillaba mill-aħħar)" },
    'suffix-example-placeholder': { en: "Example: Dual suffix", standard: "Eżempju: Suffiss doppju", arabised: "Eżempju: Suffiss doppju" },
    'suffix-is-required': { en: "Suffix is required.", standard: "Is-suffiss huwa meħtieġ.", arabised: "Is-suffiss huwa meħtieġ." },
    'suffix-kind': { en: "Kind", standard: "Tip", arabised: "Tip" },
    'suffix-label': { en: "Label", standard: "Tikketta", arabised: "Tikketta" },
    'suffix-surface-form-note': { en: "Use the same surface form you want shown in the browse page.", standard: "Uża l-istess forma li trid tidher fil-paġna tal-browsing.", arabised: "Uża l-istess forma li trid tidher fil-paġna tal-browsing." },
    'sync-from-entries': { en: "Sync from Entries", standard: "Sinkronizza mill-entrati", arabised: "Sinkronizza mill-entrati" },
    'toggle-canonical-pattern-shortcuts': { en: "Toggle canonical pattern shortcuts", standard: "Uri jew aħbi shortcuts tal-mudell kanoniku", arabised: "Uri jew aħbi shortcuts tal-mudell kanoniku" },

    // Brand
    'brand-name': { en: "Il-Miġma'", standard: "Il-Miġma'", arabised: "Il-Miġma'" },
    'brand-desc': {
        en: "Il-Miġma' is a comprehensive digital dictionary and linguistic resource dedicated to the preservation and analysis of the Maltese language. By bridging traditional Semitic morphological patterns with modern computational linguistics, we provide researchers and learners with an unprecedented depth of data, from phonetic transcriptions to historical etymologies.",
        standard: "Il-Miġma' huwa dizzjunarju diġitali komprensiv u riżorsa lingwistika ddedikata għall-preservazzjoni u l-analiżi tal-lingwa Maltija. Billi ngħaqqdu x-xejriet morfoloġiċi Semitiċi tradizzjonali mal-lingwistika komputazzjonali moderna, nipprovdu lir-riċerkaturi u lil dawk li jitgħallmu fond ta' dejta bla preċedent, minn traskrizzjonijiet fonetiċi sa etimoloġiji storiċi.",
        arabised: "Il-Miġma' huwa miklem wesgħani u riżorsa lingwistika ddedikata għall-preservazzjoni u l-analiżi tal-ilsien Malti. Billi ngħaqqdu x-xejriet morfoloġiċi Siemi tradizzjonali mal-lingwistika komputazzjonali moderna, nipprovdu lir-riċerkaturi u lil dawk li jitgħallmu fond ta' dejta kbir, minn traskrizzjonijiet fonetiċi sa etimoloġiji storiċi."
    },

    // Footer
    'maltese-alphabets': { en: 'Maltese Alphabets', standard: 'Alfabetti Maltin', arabised: 'Alfabetti Maltin' },
    'morphology': { en: 'Morphology', standard: 'Morfoloġija', arabised: 'Tisrif' },
    'terminologies': { en: 'Terminologies', standard: 'Terminoloġiji', arabised: 'Magħlqijiet' },
    'suggest-dialect-entry': { en: 'Suggest Dialect Entry', standard: 'Issuġġerixxi Entrata Djalettali', arabised: 'Issuġġerixxi Madħla Lsejnija' },
    'report-error': { en: 'Report Error', standard: 'Irrapporta Żball', arabised: 'Irrapporta Għelt' },
    'contribute': { en: 'Contribute', standard: 'Ikkontribwixxi', arabised: 'Għin lill-Proġett' },
    'recorded': { en: 'recorded', standard: 'reġistrati', arabised: 'reġistrati' },
    'view-all': { en: 'View all', standard: 'Ara kollox', arabised: 'Ara kollox' },
    'recently-added': { en: 'Recently Added', standard: 'Miżjuda Reċentement', arabised: 'Miżjuda dal-Aħħar' },

    // Entry UI
    'share': { en: 'Share', standard: 'Aqsam', arabised: 'Xierek' },
    'report': { en: 'Report', standard: 'Irrapporta', arabised: 'Irrapporta' },
    'under-this-word': { en: 'Under this word', standard: 'Taħt din il-kelma', arabised: 'Taħt dil-kelma' },
    'etymology-not-available': { en: 'Etymology not available', standard: 'L-etimoloġija mhux disponibbli.', arabised: 'It-tnissil mhux disponibbli.' },

    // Reliability
    'very-reliable': { en: 'Very Reliable', standard: 'Affidabbli Ħafna', arabised: 'Affidabbli Ħafna' },
    'reliable': { en: 'Reliable', standard: 'Affidabbli', arabised: 'Affidabbli' },
    'partially-reliable': { en: 'Partially Reliable', standard: 'Parzjalment Affidabbli', arabised: 'Affidabbli biċ-ċejċa' },
    'uncertain': { en: 'Uncertain', standard: 'Inċert', arabised: 'Mhux żgur' },
    'attestation-reliability': { en: 'Attestation Reliability', standard: 'Affidabbiltà tal-Attestament', arabised: 'Affidabbiltà tal-Attestament' },
    'reliability-score-desc': { en: "The score is calculated based on the weighting of different academic sources.", standard: "Il-punteġġ huwa kkalkajat abbażi tal-pesatura ta' sorsi akkademiċi differenti.", arabised: "Il-punteġġ huwa kkalkajat abbażi tal-pesatura ta' sorsi akkademiċi differenti." },

    // Morphology Grid
    'regular-plural': { en: 'Regular Plural', standard: 'Plural Regolari', arabised: 'Ġmigħ Sħiħ' },
    'diminutive': { en: 'Diminutive', standard: 'Diminuttiv', arabised: 'Tiżgħir' },
    'collective': { en: 'Collective', standard: 'Kollettiv', arabised: 'Ġemmiegħi' },
    'singulative': { en: 'Singulative', standard: 'Singulattiv', arabised: 'Farradi' },
    'unit': { en: 'Unit', standard: 'Unità', arabised: 'Unità' },
    'common': { en: 'Common', standard: 'Komuni', arabised: 'Komuni' },
    'proper': { en: 'Proper', standard: 'Propju', arabised: 'Propju' },
    'verbal': { en: 'Verbal', standard: 'Verbali', arabised: 'Fagħli' },
    'form-title': { en: 'Form', standard: 'Forma', arabised: 'Forma' },
    'strength-title': { en: 'Strength', standard: 'Saħħa', arabised: 'Saħħa' },
    'masdar-label': { en: 'Verbal Noun', standard: 'Nom verbali', arabised: 'Misder' },
    'elative': { en: 'Elative', standard: 'Elattiv', arabised: 'Mifgħul fard' },
    'masculine-fem': { en: 'Masculine / Feminine', standard: 'Maskili / Femminil', arabised: 'Imdakkar / Immarri' },
    'inflection-table': { en: 'Inflection Table', standard: 'Tabella tal-Inflezzjoni', arabised: 'Tabella tat-Tisrif' },
    'attached-pronouns': { en: 'Attached Pronouns', standard: 'Pronomi Mehmuża', arabised: 'Dmirijiet Mehmuża' },
    'base-form': { en: 'Base Form', standard: 'Forma Bażika', arabised: 'Sura Sies' },
    'with-pronoun': { en: 'With Pronoun', standard: 'Bl-Anness', arabised: 'Bl-Anness' },
    'broken-plural': { en: 'Broken Plural', standard: 'Plural Miksur', arabised: 'Ġmigħ Miksur' },

    // Tag labels use the tag-<normalized-tag-key> convention.
    'tag-common': { en: 'Common', standard: 'Komuni', arabised: 'Imferrex' },
    'tag-semitic-core': { en: 'Semitic Core', standard: 'Qalba Semitika', arabised: 'Qalba Siemi' },
    'tag-romance-core': { en: 'Romance Core', standard: 'Qalba Rumanz', arabised: 'Qalba Rumanzi' },
    'tag-colour': { en: 'Colour', standard: 'Kulur', arabised: 'Lewn' },
    'tag-color': { en: 'Color', standard: 'Kulur', arabised: 'Lewn' },
    'tag-theoretical': { en: 'Theoretical', standard: 'Teoretiku', arabised: 'Ħsibi' },
    'tag-base': { en: 'Base', standard: 'Bażi', arabised: 'Sies' },
    'tag-term': { en: 'Term', standard: 'Terminu', arabised: 'Terminu' },
    'tag-derived': { en: 'Derived', standard: 'Derivat', arabised: 'Imħarreġ' },
    'tag-arabism': { en: 'Arabism', standard: 'Arabiżmu', arabised: 'Għerubija' },
    'tag-archaic': { en: 'Archaic', standard: 'Arkajku', arabised: 'Qadim' },
    'tag-obsolete': { en: 'Obsolete', standard: 'Skadut', arabised: 'Mherri' },
    'tag-puristic': { en: 'Puristic', standard: 'Puristiku', arabised: 'Safi' },
    'tag-rgħajn': { en: 'Rgħajn', standard: 'Rgħajn', arabised: 'Rgħajn' },
    'tag-loan': { en: 'Loan', standard: 'Selfa', arabised: 'Selfa' },

    // Admin UI labels and tools
    'sql-console': { en: 'SQL Console', standard: 'Konsola SQL', arabised: 'Konsola SQL' },
    'export-data': { en: 'Export Data', standard: 'Esporta d-Data', arabised: 'Esporta d-Data' },
    'query-editor': { en: 'Query Editor', standard: 'Editur tal-Queries', arabised: 'Editur tal-Queries' },
    'write-mode': { en: 'Write Mode', standard: 'Mod tal-Kitba', arabised: 'Mod tal-Kitba' },
    'execute': { en: 'Execute', standard: 'Eżegwixxi', arabised: 'Eżegwixxi' },
    'execution-error': { en: 'Execution Error', standard: 'Żball fl-Eżekuzzjoni', arabised: 'Żball fl-Eżekuzzjoni' },
    'rows-returned': { en: 'Rows Returned', standard: 'Ringieli', arabised: 'Ringieli' },
    'rows-affected': { en: 'Rows Affected', standard: 'Ringieli milquta', arabised: 'Ringieli milquta' },
    'run-query-to-see-results': { en: 'Run a query to see results', standard: 'Agħmel query biex tara r-riżultati', arabised: 'Agħmel query biex tara r-riżultati' },
    'select-table-preview-download': { en: 'Select a table to preview and download its contents.', standard: 'Agħżel tabella biex tara u tniżżel il-kontenut tagħha.', arabised: 'Agħżel tabella biex tara u tniżżel il-kontenut tagħha.' },
    'select-table': { en: 'Select Table', standard: 'Agħżel Tabella', arabised: 'Agħżel Tabella' },
    'choose-a-table': { en: 'Choose a table', standard: 'Agħżel tabella', arabised: 'Agħżel tabella' },
    'previewing-first-100-rows': { en: 'Previewing first 100 rows', standard: 'Qed tara l-ewwel 100 ringiela', arabised: 'Qed tara l-ewwel 100 ringiela' },
    'database-integrity-scan': { en: 'Database Integrity Scan', standard: 'Skenn tal-Integrità', arabised: 'Skenn tal-Integrità' },
    'auto-scan-integrity': { en: 'Automatically scan for broken relationships, orphan records, and malformed data.', standard: 'Skennja għal relazzjonijiet miksura u data mħassra.', arabised: 'Skennja għal relazzjonijiet miksura u data mħassra.' },
    'start-scan': { en: 'Start Scan', standard: 'Ibda Skenn', arabised: 'Ibda Skenn' },
    'last-scan-completed-at': { en: 'Last scan completed at', standard: 'L-aħħar skenn sar fi', arabised: 'L-aħħar skenn sar fi' },
    'all-healthy': { en: 'All Healthy!', standard: 'Kollox Sew!', arabised: 'Kollox Sew!' },
    'no-db-issues': { en: 'No database integrity issues were found.', standard: 'Ma nstabu l-ebda problemi fl-integrità tal-id.', arabised: 'Ma nstabu l-ebda problemi fl-integrità tal-id.' },
    'instances-found': { en: 'instances found', standard: 'każijiet sibt', arabised: 'każijiet sibt' },
    'bulk-delete-dev-only': { en: 'Bulk Delete (Dev Only)', standard: 'Ħassar Kollox (Dev Only)', arabised: 'Ħassar Kollox (Dev Only)' },
    'scanning-engine-ready': { en: 'Scanning Engine Ready', standard: 'Magna ReSti għall-iSkenn', arabised: 'Magna ReSti għall-iSkenn' },
    'confirm-root-merge-danger': { en: 'Are you ABSOLUTELY sure? This will delete the source root and reassign ALL related data. This cannot be undone.', standard: 'Inti żgur B\'KOLlox? Dan se jħassar l-għerq tas-sors u jassenja d-data KOLLHA mill-ġdid. Dan ma jistax jinqaleb.', arabised: 'Inti żgur B\'KOLlox? Dan se jħassar l-għerq tas-sors u jassenja d-data KOLLHA mill-ġdid. Dan ma jistax jinqaleb.' },
    'roots-merged-successfully': { en: 'Roots merged successfully!', standard: 'L-għeruq ingħaqdu b\'suċċess!', arabised: 'L-għeruq ingħaqdu b\'suċċess!' },
    'merge-duplicate-roots': { en: 'Merge Duplicate Roots', standard: 'Għaqqad Għeruq Duplikati', arabised: 'Għaqqad Għeruq Duplikati' },
    'reassign-all-entries-from-one-root-to-another-and-delete-the-duplicate': { en: 'Reassign all entries from one root to another and delete the duplicate.', standard: 'Assenja mill-ġdid l-entrati kollha għall-għerq l-ieħor.', arabised: 'Assenja mill-ġdid l-entrati kollha għall-għerq l-ieħor.' },
    'bulk-field-update': { en: 'Bulk Field Update', standard: 'Aġġorna Diversi Ringieli', arabised: 'Aġġorna Diversi Ringieli' },
    'back-to-workflows': { en: 'Back to Workflows', standard: 'Lura għall-għażliet', arabised: 'Lura għall-għażliet' },
    'source-root-id-to-be-deleted': { en: 'Source Root ID (TO BE DELETED)', standard: 'ID tas-Sors (SE JINĦASSAR)', arabised: 'ID tas-Sors (SE JINĦASSAR)' },
    'target-root-id-to-be-kept': { en: 'Target Root ID (TO BE KEPT)', standard: 'ID tad-Destinazzjoni (SE JINŻAMM)', arabised: 'ID tad-Destinazzjoni (SE JINŻAMM)' },
    'preview-merge': { en: 'Preview Merge', standard: 'Ara Preview', arabised: 'Ara Preview' },
    'merge-summary': { en: 'Merge Summary', standard: 'Sommarju tal-Għaqda', arabised: 'Sommarju tal-Għaqda' },
    'related-data-to-reassign': { en: 'Related Data to Reassign', standard: 'Data Relatata se tiġi assenjata mill-ġdid', arabised: 'Data Relatata se tiġi assenjata mill-ġdid' },
    'confirm-merge': { en: 'Confirm & Merge', standard: 'Ikkonferma u Għaqqad', arabised: 'Ikkonferma u Għaqqad' },
    'bulk-field-update-coming-soon': { en: 'Bulk Field Update workflow coming in the next patch...', standard: 'Il-fluss tat-xogħol għall-aġġornament dalwaqt...', arabised: 'Il-fluss tat-xogħol għall-aġġornament dalwaqt...' },
    'go-back': { en: 'Go Back', standard: 'Mur Lura', arabised: 'Mur Lura' },
    'root-consonants-required': { en: 'Root consonants are required', standard: 'Konsonanti meħtieġa', arabised: 'Konsonanti meħtieġa' },
    'edit-root-info': { en: 'Edit Root Info', standard: 'Editja l-Info tal-Għerq', arabised: 'Editja l-Info tal-Għerq' },
    'root-class': { en: 'Root Class', standard: 'Klassi tal-Għerq', arabised: 'Klassi tal-Għerq' },
    'root-id': { en: 'Root ID', standard: 'ID tal-Għerq', arabised: 'ID tal-Għerq' },
    'tags-comma-separated': { en: 'Tags (comma separated)', standard: 'Tikketti (separati bil-virgola)', arabised: 'Tikketti (separati bil-virgola)' },
    'vowel-set-perf': { en: 'Vowel Set (Perf)', standard: 'Vokali (Perf)', arabised: 'Vokali (Perf)' },
    'vowel-set-impf': { en: 'Vowel Set (Impf)', standard: 'Vokali (Impf)', arabised: 'Vokali (Impf)' },
    'vowel-set-imp': { en: 'Vowel Set (Imp)', standard: 'Vokali (Imp)', arabised: 'Vokali (Imp)' },
    'loading-editors': { en: 'Loading editors…', standard: 'Qed jitgħabbu l-editors…', arabised: 'Qed jitgħabbu l-editors…' },
    'add-step': { en: 'Add Step', standard: 'Żid Pass', arabised: 'Żid Pass' },
    'relationship': { en: 'Relationship', standard: 'Relazzjoni', arabised: 'Relazzjoni' },
    'language': { en: 'Language', standard: 'Lingwa', arabised: 'Lingwa' },
    'definition': { en: 'Definition', standard: 'Tifsira', arabised: 'Tifsira' },
    'additional-fields': { en: 'Additional Fields', standard: 'Għelieqi Oħra', arabised: 'Għelieqi Oħra' },
    'duplicate-as-new': { en: 'Duplicate as New', standard: 'Ikkopja bħala Ġdid', arabised: 'Ikkopja bħala Ġdid' },
    'stem-required': { en: 'Stem is required', standard: 'Iż-Żokk huwa meħtieġ', arabised: 'Iż-Żokk huwa meħtieġ' },
    'new-stem-admin': { en: 'New Stem', standard: 'Żokk Ġdid', arabised: 'Żokk Ġdid' },
    'edit-stem-info': { en: 'Edit Stem Info', standard: 'Editja l-Info taż-Żokk', arabised: 'Editja l-Info taż-Żokk' },
    'agentive-suffix-override': { en: 'Agentive Suffix Override', standard: 'Suffiss Aġentiv Override', arabised: 'Suffiss Aġentiv Override' },
    'related-stems': { en: 'Related Stems', standard: 'Żkuk Relatati', arabised: 'Żkuk Relatati' },
    'new-entry-admin': { en: 'New Entry', standard: 'Entrata Ġdida', arabised: 'Entrata Ġdida' },
    'edit-entry-admin': { en: 'Edit Entry', standard: 'Editja l-Entrata', arabised: 'Editja l-Entrata' },
    'plural-forms': { en: 'Plural Forms', standard: 'Forom tal-Plural', arabised: 'Forom tal-Plural' },
    'add-plural': { en: 'Add Plural', standard: 'Żid Plural', arabised: 'Żid Plural' },
    'add-each-plural-form-on-its-own-row-so-every-plural-can-keep-its-own-pattern': { en: 'Add each plural form on its own row so every plural can keep its own pattern.', standard: 'Żid kull forma ta\' plural fuq ringiela separata biex kull plural iżomm il-mudell tiegħu.', arabised: 'Żid kull forma ta\' plural fuq ringiela separata biex kull plural iżomm il-mudell tiegħu.' },
    'suggest-morphology-from-pattern': { en: 'Suggest Morphology from Pattern', standard: 'Issuġġerixxi Morfoloġija mill-Mudell', arabised: 'Issuġġerixxi Morfoloġija mill-Mudell' },
    'feminine-form': { en: 'Feminine Form', standard: 'Forma Femminili', arabised: 'Forma Femminili' },
    'singulative-form': { en: 'Singulative Form', standard: 'Forma Singolattiva', arabised: 'Forma Singolattiva' },
    'collective-form': { en: 'Collective Form', standard: 'Forma Kollettiva', arabised: 'Forma Kollettiva' },
    'masculine-form': { en: 'Masculine Form', standard: 'Forma Maskili', arabised: 'Forma Maskili' },
    'dual-suffix': { en: 'Dual Suffix', standard: 'Suffiss Doppju', arabised: 'Suffiss Doppju' },
    'paucal-form': { en: 'Paucal Form', standard: 'Forma Pawkali', arabised: 'Forma Pawkali' },
    'augmentative-form': { en: 'Augmentative Form', standard: 'Forma Tkabbir', arabised: 'Forma Tkabbir' },
    'diminutive-form': { en: 'Diminutive Form', standard: 'Forma Tiżgħir', arabised: 'Forma Tiżgħir' },
    'elative-comparative': { en: 'Elative (Comparative)', standard: 'Elattiv (Komparattiv)', arabised: 'Elattiv (Komparattiv)' },
    'suggest-numeral-forms': { en: 'Suggest Numeral Forms', standard: 'Issuġġerixxi Forom Numerali', arabised: 'Issuġġerixxi Forom Numerali' },
    'numeral-type': { en: 'Numeral Type', standard: 'Tip ta\' Numeral', arabised: 'Tip ta\' Numeral' },
    'lemma-base': { en: 'Lemma Base', standard: 'Bażi tal-Lemma', arabised: 'Bażi tal-Lemma' },
    'short-attributive': { en: 'Short Attributive', standard: 'Attributiv Qasir', arabised: 'Attributiv Qasir' },
    'stem-morphology': { en: 'Stem Morphology', standard: 'Morfoloġija taż-Żokk', arabised: 'Morfoloġija taż-Żokk' },
    'reanalysed-root-mirrors-the-main-root-consonants': { en: 'Reanalysed root mirrors the main root consonants.', standard: 'L-għerq rianalizzat jirrifletti l-konsonanti ewlenin tal-għerq.', arabised: 'L-għerq rianalizzat jirrifletti l-konsonanti ewlenin tal-għerq.' },
    'agentive-suffix': { en: 'Agentive Suffix', standard: 'Suffiss Aġentiv', arabised: 'Suffiss Aġentiv' },
    'source-language(s)': { en: 'Source Language(s)', standard: 'Lingwa(i) tas-Sors', arabised: 'Lingwa(i) tas-Sors' },
    'verb-type': { en: 'Verb Type', standard: 'Tip ta\' Verb', arabised: 'Tip ta\' Verb' },
    'pronunciation-example': { en: 'e.g. kan-ta-re', standard: 'eż. kan-ta-re', arabised: 'eż. kan-ta-re' },
    'duplicate-id-handled': { en: 'Duplicate ID handled:', standard: 'ID duplikat immaniġġjat:', arabised: 'ID duplikat immaniġġjat:' },
    'headword-is-required': { en: 'Headword is required', standard: 'Il-headword hija meħtieġa', arabised: 'Il-headword hija meħtieġa' },
    'already-exists': { en: 'already exists', standard: 'diġà jeżisti', arabised: 'diġà jeżisti' },
    'available': { en: 'available', standard: 'disponibbli', arabised: 'disponibbli' },
    'suggest-headword': { en: 'Suggest:', standard: 'Issuġġerixxi:', arabised: 'Issuġġerixxi:' },
    'reset-to-original': { en: 'Reset to original', standard: 'Irrestawra l-oriġinal', arabised: 'Irrestawra l-oriġinal' },
    'prefer-stem-priority': { en: 'Prioritise stem (loanword)', standard: 'Agħti prijorità lis-żokk (selfa)', arabised: 'Agħti prijorità lis-żokk (selfa)' },
    'cv-pattern-wizen': { en: 'CV Pattern / Wiżen', standard: 'Mudell CV / Wiżen', arabised: 'Mudell CV / Wiżen' },
    'suggested-for-form': { en: 'suggested for Form', standard: 'issuġġerit għall-Formola', arabised: 'issuġġerit għall-Formola' },
    'apply': { en: 'Apply', standard: 'Applika', arabised: 'Applika' },
    'verb-presets': { en: 'Verb Presets', standard: 'Preset tal-Verbi', arabised: 'Preset tal-Verbi' },
    'base-pattern': { en: 'Base Pattern', standard: 'Mudell Bażiku', arabised: 'Mudell Bażiku' },
    'notable': { en: 'Notable (!)', standard: 'Notevoli (!)', arabised: 'Notevoli (!)' },
    'add-tag': { en: 'Add tag...', standard: 'Żid tikketta...', arabised: 'Żid tikketta...' },
    'existing-tags': { en: 'Existing Tags', standard: 'Tikketti Eżistenti', arabised: 'Tikketti Eżistenti' },
    'phonetics-dialects': { en: 'Phonetics & Dialects', standard: 'Fonetika u Djaletti', arabised: 'Fonetika u Djaletti' },
    'suggest-ipa': { en: 'Suggest IPA:', standard: 'Issuġġerixxi IPA:', arabised: 'Issuġġerixxi IPA:' },
    'add-variant': { en: 'Add Variant', standard: 'Żid Varjant', arabised: 'Żid Varjant' },
    'spelling': { en: 'Spelling', standard: 'Ortografija', arabised: 'Ortografija' },
    'ipa': { en: 'IPA', standard: 'IPA', arabised: 'IPA' },
    'morphology-admin': { en: 'Morphology', standard: 'Morfoloġija', arabised: 'Tisrif' },
    'entry-morphology': { en: 'Entry Morphology', standard: 'Morfoloġija tal-Entrata', arabised: 'Morfoloġija tal-Madħla' },
    'add-sense': { en: 'Add Sense', standard: 'Żid Tifsira', arabised: 'Żid Tifsira' },
    'use-semicolons-to-split-one-sense-into-separate-entries': { en: 'Use semicolons to split one sense into separate entries.', standard: 'Uża s-semikolon biex taqsam tifsira waħda f\'entrati separati.', arabised: 'Uża s-semikolon biex taqsam tifsira waħda f\'madħliet separati.' },
    'sense': { en: 'Sense', standard: 'Tifsira', arabised: 'Tifsira' },
    'nuance': { en: 'Nuance', standard: 'Nuance', arabised: 'Nuance' },
    'headword-is-required-entry': { en: 'Headword is required', standard: 'Il-headword hija meħtieġa', arabised: 'Il-headword hija meħtieġa' },
    'duplicate-id-handled-entry': { en: 'Duplicate ID handled:', standard: 'ID duplikat immaniġġjat:', arabised: 'ID duplikat immaniġġjat:' },
    'available-entry': { en: 'available', standard: 'disponibbli', arabised: 'disponibbli' },
    'suggest-headword-label': { en: 'Headword', standard: 'Kelma Prinċipali', arabised: 'Kelma Prinċipali' },
    'Augmentative Pattern': { en: 'Augmentative Pattern', standard: 'Mudell Tkabbir', arabised: 'Mudell Tkabbir' },
    'Collective Pattern': { en: 'Collective Pattern', standard: 'Mudell Kollettiv', arabised: 'Mudell Kollettiv' },
    'Create Entry': { en: 'Create Entry', standard: 'Oħloq Entrata', arabised: 'Oħloq Entrata' },
    'Diminutive Pattern': { en: 'Diminutive Pattern', standard: 'Mudell Diminuttiv', arabised: 'Mudell Diminuttiv' },
    'Elative Pattern': { en: 'Elative Pattern', standard: 'Mudell Elattiv', arabised: 'Mudell Elattiv' },
    'Entry ID': { en: 'Entry ID', standard: 'ID tal-Entrata', arabised: 'ID tal-Entrata' },
    'Etymology Builder': { en: 'Etymology Builder', standard: 'Oriġini tal-Kelma', arabised: 'Oriġini tal-Kelma' },
    'Fem. Pattern': { en: 'Fem. Pattern', standard: 'Mudell Fem.', arabised: 'Mudell Fem.' },
    'Feminine Pattern': { en: 'Feminine Pattern', standard: 'Mudell Fem.', arabised: 'Mudell Fem.' },
    'Imperfect (3sg.m)': { en: 'Imperfect (3sg.m)', standard: 'Imperfett (3sg.m)', arabised: 'Imperfett (3sg.m)' },
    'Inherited from root': { en: 'Inherited from root', standard: 'Miret mill-għerq', arabised: 'Miret mill-għerq' },
    'Loading etymology editor…': { en: 'Loading etymology editor…', standard: 'Qed jitgħabba l-editor tal-etimoloġija…', arabised: 'Qed jitgħabba l-editor tal-etimoloġija…' },
    'Loading relationship editors…': { en: 'Loading relationship editors…', standard: 'Qed jitgħabbu l-editors tar-relazzjonijiet…', arabised: 'Qed jitgħabbu l-editors tar-relazzjonijiet…' },
    'Masc. Pattern': { en: 'Masc. Pattern', standard: 'Mudell Mask.', arabised: 'Mudell Mask.' },
    'Masculine Pattern': { en: 'Masculine Pattern', standard: 'Mudell Mask.', arabised: 'Mudell Mask.' },
    'Pattern Presets': { en: 'Pattern Presets', standard: 'Mudelli Presets', arabised: 'Mudelli Presets' },
    'Paucal Pattern': { en: 'Paucal Pattern', standard: 'Mudell Pawkali', arabised: 'Mudell Pawkali' },
    'Perfect (3sg.m)': { en: 'Perfect (3sg.m)', standard: 'Perfett (3sg.m)', arabised: 'Perfett (3sg.m)' },
    'Plural Form': { en: 'Plural Form', standard: 'Forma tal-Plural', arabised: 'Forma tal-Plural' },
    'Select...': { en: 'Select...', standard: 'Agħżel...', arabised: 'Agħżel...' },
    'Singulative Pattern': { en: 'Singulative Pattern', standard: 'Mudell Sing.', arabised: 'Mudell Sing.' },
    'Suggest': { en: 'Suggest', standard: 'Sugġeriment', arabised: 'Sugġeriment' },
    'Unsaved Changes': { en: 'Unsaved Changes', standard: 'Tibdil mhux merfugħ', arabised: 'Tibdil mhux merfugħ' },
    'e.g. Aquilina1987': { en: 'e.g. Aquilina1987', standard: 'eż. Aquilina1987', arabised: 'eż. Aquilina1987' },
    'e.g. Italian, English': { en: 'e.g. Italian, English', standard: 'eż. Taljan, Ingliż', arabised: 'eż. Taljan, Ingliż' },
    'reset': { en: 'reset', standard: 'irrisettja', arabised: 'irrisettja' },
    'add-pattern': { en: 'Add pattern', standard: 'Żid mudell', arabised: 'Żid mudell' },
    'add-suffix': { en: 'Add Suffix', standard: 'Żid Suffiss', arabised: 'Żid Suffiss' },
    'edit-pattern': { en: 'Edit pattern', standard: 'Editja l-mudell', arabised: 'Editja l-mudell' },
    'edit-suffix': { en: 'Edit Suffix', standard: 'Editja Suffiss', arabised: 'Editja Suffiss' },
    'no-entries-yet': { en: 'No entries yet', standard: 'Għad m’hemmx entrati', arabised: 'Għad m’hemmx madħliet' },
    'no-patterns-found': { en: 'No patterns found', standard: 'Ma nstabu l-ebda mudelli', arabised: 'Ma nstabu l-ebda wiżien' },
    'no-patterns-found-desc': { en: 'This view does not have any patterns yet, or the patterns have not been categorized.', standard: 'Din il-veduta għadha ma għandhiex mudelli, jew il-mudelli għadhom ma ġewx kategorizzati.', arabised: 'Din il-veduta għadha ma għandhiex wiżien, jew il-wiżien għadhom ma ġewx kategorizzati.' },
    'total': { en: 'Total', standard: 'Total', arabised: 'Total' },

    // Shared UI labels and states
    'actions': { en: 'Actions', standard: 'Azzjonijiet', arabised: 'Azzjonijiet' },
    'advanced': { en: 'Advanced', standard: 'Avvanzat', arabised: 'Avvanzat' },
    'adverbial': { en: 'Adverbial', standard: 'Avverbjali', arabised: 'Avverbjali' },
    'agentive': { en: 'Agentive', standard: 'Aġentiv', arabised: 'Aġentiv' },
    'admin-settings': { en: 'Admin Settings', standard: 'Settings tal-Amministrazzjoni', arabised: 'Settings tal-Amministrazzjoni' },
    'back-to-browse': { en: 'Back to Browse', standard: 'Mur lura għall-Brawżjar', arabised: 'Mur lura għall-Għarbil' },
    'cardinal': { en: 'Cardinal', standard: 'Kardinali', arabised: 'Kardinali' },
    'categories': { en: 'Categories', standard: 'Kategoriji', arabised: 'Kategoriji' },
    'canonical-patterns': { en: 'Canonical Patterns', standard: 'Mudelli Kanoniċi', arabised: 'Mudelli Kanoniċi' },
    'clear-selection': { en: 'Clear Selection', standard: 'Neħħi l-Għażla', arabised: 'Neħħi l-Għażla' },
    'confirm-remove-relationship': { en: 'Are you sure you want to remove this relationship?', standard: 'Żgur li trid tneħħi din ir-relazzjoni?', arabised: 'Żgur li trid tneħħi din ir-relazzjoni?' },
    'corrupted-data': { en: 'Corrupted data', standard: 'Data korrotta', arabised: 'Data korrotta' },
    'core-grammar': { en: 'Core Grammar', standard: 'Grammatika Ewlenija', arabised: 'Grammatika Ewlenija' },
    'date': { en: 'Date', standard: 'Data', arabised: 'Data' },
    'db-tools': { en: 'Database Tools', standard: 'Għodod tad-Database', arabised: 'Għodod tad-Database' },
    'delete-all': { en: 'Delete All', standard: 'Ħassar Kollha', arabised: 'Ħassar Kollha' },
    'derivational': { en: 'Derivational', standard: 'Derivattiv', arabised: 'Derivattiv' },
    'derived-forms-table': { en: 'Derived Forms Table', standard: 'Tabella tal-Forom Derivati', arabised: 'Tabella tal-Forom Derivati' },
    'details': { en: 'Details', standard: 'Dettalji', arabised: 'Dettalji' },
    'distributive': { en: 'Distributive', standard: 'Distributiv', arabised: 'Distributiv' },
    'dialects': { en: 'Dialects', standard: 'Djaletti', arabised: 'Djaletti' },
    'entries-using-this-pattern': { en: 'Entries using this pattern', standard: 'Entrati li jużaw dan il-mudell', arabised: 'Madħliet li jużaw dan il-mudell' },
    'entries-using-this-suffix': { en: 'Entries using this suffix', standard: 'Entrati li jużaw dan is-suffiss', arabised: 'Madħliet li jużaw dan is-suffiss' },
    'error': { en: 'Error', standard: 'Żball', arabised: 'Għelt' },
    'example-word': { en: 'Example Word', standard: 'Kelma Eżempju', arabised: 'Kelma Eżempju' },
    'failed-remove-relationship': { en: 'Failed to remove relationship: ', standard: 'It-tneħħija tar-relazzjoni falla: ', arabised: 'It-tneħħija tar-relazzjoni falla: ' },
    'found': { en: 'Found', standard: 'Riżultati', arabised: 'Riżultati' },
    'fractional': { en: 'Fractional', standard: 'Frazzjonali', arabised: 'Frazzjonali' },
    'genders': { en: 'Genders', standard: 'Ġeneri', arabised: 'Ġeneri' },
    'general': { en: 'General', standard: 'Ġenerali', arabised: 'Ġenerali' },
    'hybrid': { en: 'Hybrid', standard: 'Ibridu', arabised: 'Ibridu' },
    'interface-view': { en: 'Interface View', standard: 'Veduta tal-Interface', arabised: 'Veduta tal-Interface' },
    'individual-form': { en: 'Individual Form', standard: 'Forma Individwali', arabised: 'Sura Individwali' },
    'internal-id': { en: 'Internal ID', standard: 'ID Intern', arabised: 'ID Intern' },
    'is-hybrid': { en: 'Is Hybrid', standard: 'Huwa Ibridu', arabised: 'Huwa Ibridu' },
    'legacy-adjective-bucket': { en: 'Legacy Adjective Bucket', standard: 'Kontenitur Legat tal-Aġġettiv', arabised: 'Kontenitur Legat tal-Aġġettiv' },
    'legacy-diminutive-bucket': { en: 'Legacy Diminutive Bucket', standard: 'Kontenitur Legat tad-Diminuttiv', arabised: 'Kontenitur Legat tad-Diminuttiv' },
    'legacy-feminine-bucket': { en: 'Legacy Feminine Bucket', standard: 'Kontenitur Legat tal-Femminil', arabised: 'Kontenitur Legat tal-Femminil' },
    'legacy-plural-bucket': { en: 'Legacy Plural Bucket', standard: 'Kontenitur Legat tal-Plural', arabised: 'Kontenitur Legat tal-Plural' },
    'linguistic-roles': { en: 'Linguistic Roles', standard: 'Rwoli Lingwistiċi', arabised: 'Rwoli Lingwistiċi' },
    'roles': { en: 'Roles', standard: 'Rwoli', arabised: 'Rwoli' },
    'long-attributive': { en: 'Long Attributive', standard: 'Attributiv Twil', arabised: 'Attributiv Twil' },
    'maltese-academy': { en: 'Maltese Academy', standard: 'L-Akkademja Maltija', arabised: 'L-Akkademja Maltija' },
    'missing': { en: 'Missing', standard: 'Nieqes', arabised: 'Nieqes' },
    'mode': { en: 'Mode', standard: 'Mod', arabised: 'Mod' },
    'morphological-pattern': { en: 'Morphological Pattern', standard: 'Mudell Morfoloġiku', arabised: 'Mudell Morfoloġiku' },
    'multiplier': { en: 'Multiplier', standard: 'Multiplikatur', arabised: 'Multiplikatur' },
    'noun-types': { en: 'Noun Types', standard: 'Tipi ta\' Nomi', arabised: 'Tipi ta\' Ismijiet' },
    'new-stem': { en: 'New Stem', standard: 'Sura Ġdida', arabised: 'Sura Ġdida' },
    'no-antonyms': { en: 'No antonyms', standard: 'L-ebda antonimi', arabised: 'L-ebda antonimi' },
    'no-definition': { en: 'No definition', standard: 'L-ebda definizzjoni', arabised: 'L-ebda definizzjoni' },
    'no-entries-found': { en: 'No entries found', standard: 'L-ebda entrata ma nstabet', arabised: 'L-ebda madħla ma nstabet' },
    'no-synonyms': { en: 'No synonyms', standard: 'L-ebda sinonimi', arabised: 'L-ebda sinonimi' },
    'numeral-types': { en: 'Numeral Types', standard: 'Tipi ta\' Numru', arabised: 'Tipi ta\' Numru' },
    'none': { en: 'None', standard: 'Ebda', arabised: 'Ebda' },
    'ordinal': { en: 'Ordinal', standard: 'Ordinali', arabised: 'Ordinali' },
    'other': { en: 'Other', standard: 'Oħra', arabised: 'Oħra' },
    'parts-of-speech': { en: 'Parts of Speech', standard: 'Partijiet tad-Diskors', arabised: 'Partijiet tat-Tħaddit' },
    'pattern-not-found': { en: 'Pattern not found', standard: 'Il-mudell ma nstabx', arabised: 'Il-mudell ma nstabx' },
    'reanalysed-root': { en: 'Reanalysed Root', standard: 'Għerq Rianalizzat', arabised: 'Ġidra rianalizzata' },
    'register': { en: 'Register', standard: 'Reġistru', arabised: 'Reġistru' },
    'registers': { en: 'Registers', standard: 'Reġistri', arabised: 'Reġistri' },
    'remove-relationship': { en: 'Remove Relationship', standard: 'Neħħi r-Relazzjoni', arabised: 'Neħħi r-Relazzjoni' },
    'root-deleted': { en: 'Root deleted', standard: 'Għerq imħassar', arabised: 'Ġidra mħassra' },
    'root-strengths': { en: 'Root Strengths', standard: 'Saħħiet tal-Għeruq', arabised: 'Saħħiet tal-Ġidriet' },
    'roots': { en: 'Roots', standard: 'Għeruq', arabised: 'Ġidriet' },
    'remove-from-list': { en: 'Remove from list', standard: 'Neħħi mil-lista', arabised: 'Neħħi mil-lista' },
    'unlink-antonym': { en: 'Unlink Antonym', standard: 'Neħħi l-Antonomi', arabised: 'Neħħi l-Antonomi' },
    'unlink-synonym': { en: 'Unlink Synonym', standard: 'Neħħi s-Sinonimu', arabised: 'Neħħi s-Sinonimu' },
    'save-to-list': { en: 'Save to list', standard: 'Issejvja fil-lista', arabised: 'Issejvja fil-lista' },
    'search-entry': { en: 'Search Entry', standard: 'Fittex Entrata', arabised: 'Fittex Madħla' },
    'search-locations': { en: 'Search Locations', standard: 'Postijiet tat-Tiftix', arabised: 'Postijiet tat-Tiftix' },
    'search-root': { en: 'Search Root', standard: 'Fittex Għerq', arabised: 'Fittex Ġidra' },
    'selected-entries': { en: 'Selected Entries', standard: 'Entrati Magħżula', arabised: 'Madħliet Magħżula' },
    'settings': { en: 'Settings', standard: 'Issettjar', arabised: 'Issettjar' },
    'suffixes': { en: 'Suffixes', standard: 'Suffissi', arabised: 'Suffissi' },
    'sound-plural-suffix': { en: 'Sound Plural Suffix', standard: 'Suffiss tal-Plural Sħiħ', arabised: 'Suffiss tal-Plural Sħiħ' },
    'status': { en: 'Status', standard: 'Status', arabised: 'Status' },
    'ui-system': { en: 'UI & System', standard: 'UI u Sistema', arabised: 'UI u Sistema' },
    'ui-terminology': { en: 'UI Terminology', standard: 'Terminoloġija tal-UI', arabised: 'Terminoloġija tal-UI' },
    'stem-not-found': { en: 'Stem not found', standard: 'Is-sura ma nstabitx', arabised: 'Is-sura ma nstabitx' },
    'stem-not-found-desc': { en: 'This stem does not exist yet.', standard: 'Din is-sura għadha ma teżistix.', arabised: 'Din is-sura għadha ma teżistix.' },
    'verb-classes': { en: 'Verb Classes', standard: 'Klassijiet tal-Verb', arabised: 'Klassijiet tal-Verb' },
    'verb-forms': { en: 'Verb Forms', standard: 'Forom Verbali', arabised: 'Forom Verbali' },
    'strength': { en: 'Strength', standard: 'Saħħa', arabised: 'Saħħa' },
    'suggestions': { en: 'Suggestions', standard: 'Suġġerimenti', arabised: 'Suġġerimenti' },
    'tag': { en: 'Tag', standard: 'Tag', arabised: 'Tag' },
    'ptcp-nuances': { en: 'Ptcp. Nuances', standard: 'Nuances tal-Partiċipju', arabised: 'Nuances tal-Partiċipju' },
    'uncategorized': { en: 'Uncategorized', standard: 'Mhux Kategorizzat', arabised: 'Mhux Kategorizzat' },
    'unit-form': { en: 'Unit Form', standard: 'Forma Unika', arabised: 'Sura Unika' },
    'verb-class': { en: 'Verb Class', standard: 'Klassi tal-Verb', arabised: 'Klassi tal-Verb' },
    'view-entry': { en: 'View Entry', standard: 'Ara l-Entrata', arabised: 'Ara l-Madħla' },
    'weak-class': { en: 'Weak Class', standard: 'Klassi Dgħajfa', arabised: 'Klassi Dgħajfa' },
    'weak-classes': { en: 'Weak Classes', standard: 'Klassijiet Dgħajfa', arabised: 'Klassijiet Dgħajfa' },
    'word': { en: 'Word', standard: 'Kelma', arabised: 'Kelma' },
    'word-forms': { en: 'Word Forms', standard: 'Forom tal-Kelma', arabised: 'Forom tal-Kelma' },

    // TierGate
    'is-a-feature': { en: "{label} is a {tier} feature", standard: "{label} hija feature {tier}", arabised: "{label} hija ghalik fil-livell {tier}" },
    'upgrade-to': { en: "Upgrade to {tier}", standard: "Aġġorna għal {tier}", arabised: "Ittejjeb għal {tier}" },
    'feature-pro-desc': { en: "Upgrade to Pro to unlock this and many more features.", standard: "Aġġorna għal Pro biex tiftaħ din u ħafna aktar.", arabised: "Ittejjeb għal Pro biex tiftaħ din u ħafna aktar." },
    'feature-enterprise-desc': { en: "Enterprise plan required. Contact us to get started.", standard: "Il-pjan Enterprise meħtieġ. Ikkuntattjana biex tibda.", arabised: "Il-pjan Enterprise meħtieġ. Asalna biex tibda." },
    'pro-label': { en: 'Pro', standard: 'Pro', arabised: 'Pro' },
    'enterprise-label': { en: 'Enterprise', standard: 'Intrapriża', arabised: 'Intrapriża' },
};

const TERM_ALIASES: Record<string, string> = {
    partiklu: 'particle',
    'dual-pattern': 'dual-suffix',
    antonimi: 'antonyms',
    sinonimi: 'synonyms',
};

function normalizeTermKey(key: string) {
    const lower = key.toLowerCase();
    return TERM_ALIASES[lower] || lower;
}

/** Resolve a term key against the current linguistic mode and interface language */
export function resolveTerm(key: string, mode: LinguisticMode, lang: 'en' | 'mt' = 'mt'): string {
    const entry = TERMINOLOGY[normalizeTermKey(key)];
    if (!entry) return key;
    if (lang === 'en') return entry.en || key.charAt(0).toUpperCase() + key.slice(1);
    return mode === 'arabised' ? entry.arabised : entry.standard;
}

const ENGLISH_TERM_LOOKUP = new Map(
    Object.entries(TERMINOLOGY)
        .filter(([, entry]) => !!entry.en)
        .map(([key, entry]) => [entry.en as string, key] as const)
);

export function resolveTermByEnglish(english: string): string | undefined {
    const key = ENGLISH_TERM_LOOKUP.get(english);
    if (!key) return undefined;
    return TERMINOLOGY[key]?.standard;
}

/** Get the POS display label for a given POS key + mode + lang */
export function getPOSLabel(pos: string, mode: LinguisticMode, lang: 'en' | 'mt' = 'mt'): string {
    return resolveTerm(pos, mode, lang);
}
