import type { LinguisticMode } from '@/types';

// ─── Terminology Map ───────────────────────────────────────────────────────
// Maps a term key to its English, Standard and Arabised Maltese equivalents.

export const TERMINOLOGY: Record<string, { en?: string; standard: string; arabised: string }> = {
    // Morphological patterns
    'pattern': { en: 'Pattern', standard: 'Mudell', arabised: 'Wiżen' },
    'wizen': { en: 'Wiżen', standard: 'Wiżen', arabised: 'Wiżen' },
    'cv': { en: 'CV', standard: 'CV', arabised: 'CV' },
    'invariable': { en: 'Invariable', standard: 'Invarjabbli', arabised: 'Ma jinbidilx' },
    'cv-pattern': { en: 'CV Pattern', standard: "Mudell ta' CV", arabised: "Mudell ta' CV" },
    'wizen-pattern': { en: 'Wiżen Pattern', standard: "Mudell ta' Wiżen", arabised: "Mudell ta' Wiżen" },
    'demonym': { en: 'Demonym', standard: 'Demonym', arabised: 'Nisba' },
    'root': { en: 'Root', standard: 'Għerq', arabised: 'Ġidra' },
    'weak': { en: 'Weak', standard: 'Dgħajjef', arabised: 'Magħlul' },
    'geminated': { en: 'Geminated', standard: 'Trux', arabised: 'Imżewweġ' },
    'verbal-forms': { en: 'Verbal Forms', standard: 'Forom Verbali', arabised: 'Użien' },
    'lemma': { en: 'Lemma', standard: 'Lemma', arabised: 'Ras il-Kelma' },
    'passive': { en: 'Passive', standard: 'Passiv', arabised: 'Mifgħul' },
    'active': { en: 'Active', standard: 'Attiv', arabised: 'Fiegħel' },
    'noun-type': { en: 'Noun Type', standard: "Tip ta' Nom", arabised: "Għamla ta' Isem" },
    'dialect': { en: 'Dialect', standard: 'Djalett', arabised: 'Ilsejjen' },
    'conjugation-table': { en: 'Conjugation Table', standard: 'Tabella tal-Konjugazzjoni', arabised: 'Tabella tat-Tisrif' },
    'person': { en: 'Person', standard: 'Persuna', arabised: 'Nifs' },
    'imperfect': { en: 'Imperfect', standard: 'Imperfett', arabised: 'Għajr Tmim' },
    'perfect': { en: 'Perfect', standard: 'Perfett', arabised: 'Tmim' },
    'imperative': { en: 'Imperative', standard: 'Imperattiv', arabised: 'Amar' },
    'singular': { en: 'Singular', standard: 'Singular', arabised: 'Fard' },
    'plural': { en: 'Plural', standard: 'Plural', arabised: 'Ġmigħ' },
    '1s': { en: 'I', standard: 'Jiena', arabised: 'Jiena' },
    '2s': { en: 'You (singular)', standard: 'Inti', arabised: 'Inti' },
    '3ms': { en: 'He', standard: 'Huwa', arabised: 'Huwa' },
    '3fs': { en: 'She', standard: 'Hija', arabised: 'Hija' },
    '1p': { en: 'We', standard: 'Aħna', arabised: 'Aħna' },
    '2p': { en: 'You (plural)', standard: 'Intom', arabised: 'Intom' },
    '3p': { en: 'They', standard: 'Huma', arabised: 'Huma' },

    // Possessive Pronouns (for Inflection Tables)
    'pos-1s': { en: 'my', standard: 'tiegħi', arabised: 'tiegħi' },
    'pos-2s': { en: 'your (singular)', standard: 'tiegħek', arabised: 'tiegħek' },
    'pos-3ms': { en: 'his', standard: 'tiegħu', arabised: 'tiegħu' },
    'pos-3fs': { en: 'her', standard: 'tagħha', arabised: 'tagħha' },
    'pos-1p': { en: 'our', standard: 'tagħna', arabised: 'tagħna' },
    'pos-2p': { en: 'your (plural)', standard: 'tagħkom', arabised: 'tagħkom' },
    'pos-3p': { en: 'their', standard: 'tagħhom', arabised: 'tagħhom' },

    'polarity': { en: 'Polarity', standard: 'Polarità', arabised: 'Għamudija' },
    'positive': { en: 'Positive', standard: 'Pożittiv', arabised: 'Qagħdi' },
    'negative': { en: 'Negative', standard: 'Negattiv', arabised: 'Ċaħdi' },
    'direct-object': { en: 'Direct Object', standard: 'Oġġett Dirett', arabised: 'Mifgħul bih l-Ewwel' },
    'indirect-object': { en: 'Indirect Object', standard: 'Oġġett Indirett', arabised: 'Mifgħul bih it-Tieni' },
    'derived-terms': { en: 'Derived Terms', standard: 'Termini Derivati', arabised: 'Magħlqat Maħruġa' },
    'verbal-noun': { en: 'Verbal Noun', standard: 'Nom Verbali', arabised: 'Isem Fagħli' },
    'passive-participle': { en: 'Passive Participle', standard: 'Partiċipju Passiv', arabised: 'Mifgħul' },
    'active-participle': { en: 'Active Participle', standard: 'Partiċipju Attiv', arabised: 'Fiegħel' },
    'usage-example': { en: 'Usage Example', standard: "Eżempju ta' Użu", arabised: "Xbieha ta' Użu" },
    'thesaurus': { en: 'Thesaurus', standard: 'Teżawru', arabised: 'Mifles' },
    'synonyms': { en: 'Synonyms', standard: 'Sinonimi', arabised: 'Mixxibhin' },
    'antonyms': { en: 'Antonyms', standard: 'Antonimi', arabised: 'Mitfirqin' },
    'synonym-abbr': { en: 'syn.', standard: 'sin.', arabised: 'mibb.' },
    'antonym-abbr': { en: 'ant.', standard: 'ant.', arabised: 'mtf.' },
    'gender': { en: 'Gender', standard: 'Ġeneru', arabised: 'Ġens' },
    'feature': { en: 'Feature', standard: 'Karatteristika', arabised: 'Fsurija' },
    'has-inflection': { en: 'Has Inflection', standard: 'Għandu Inflessjoni', arabised: 'Għandu Tisrif' },
    'sun-moon-letters': { en: 'Sun & Moon Letters', standard: 'Ittri tax-Xemx u tal-Qamar', arabised: 'Ittri tax-Xemx u tal-Qamar' },
    'sun-letters': { en: 'Sun Letters', standard: 'Ittri tax-Xemx', arabised: 'Ittri tax-Xemx' },
    'moon-letters': { en: 'Moon Letters', standard: 'Ittri tal-Qamar', arabised: 'Ittri tal-Qamar' },

    // Parts of Speech
    'verb': { en: 'Verb', standard: 'Verb', arabised: 'Fagħal' },
    'noun': { en: 'Noun', standard: 'Nom', arabised: 'Isem' },
    'adjective': { en: 'Adjective', standard: 'Aġġettiv', arabised: 'Isem Fissieri' },
    'adverb': { en: 'Adverb', standard: 'Avverbju', arabised: 'Għatu' },
    'particle': { en: 'Particle', standard: 'Partiklu', arabised: 'Ntejfa' },
    'preposition': { en: 'Preposition', standard: 'Prepożizzjoni', arabised: 'Ntejfa Ġarrari' },
    'conjunction': { en: 'Conjunction', standard: 'Konġunzjoni', arabised: 'Ntejfa Għaqqadi' },
    'article': { en: 'Article', standard: 'Artiklu', arabised: 'Għodda tat-Tagħrif' },
    'interrogative': { en: 'Interrogative', standard: 'Interrogattiv', arabised: 'Għodda Saqsejja' },
    'pronoun': { en: 'Pronoun', standard: 'Pronom', arabised: 'Dmir' },
    'participle': { en: 'Participle', standard: 'Partiċipju', arabised: 'Xerriek' },
    'numeral': { en: 'Numeral', standard: 'Numerali', arabised: 'Għaddi' },
    'interjection': { en: 'Interjection', standard: 'Interjezzjoni', arabised: 'Tagħġiba' },
    'prefix': { en: 'Prefix', standard: 'Prefiss', arabised: 'Qagħda Quddimija' },
    'suffix': { en: 'Suffix', standard: 'Suffiss', arabised: 'Qagħda Warranija' },
    'masculine': { en: 'Masculine', standard: 'Maskili', arabised: 'Imdakkar' },
    'feminine': { en: 'Feminine', standard: 'Femminil', arabised: 'Immarri' },
    'neutral': { en: 'Neutral', standard: 'Newtrali', arabised: 'Newtrali' },
    'transitive': { en: 'Transitive', standard: 'Tranżittiv', arabised: 'Mitgħaddi' },
    'intransitive': { en: 'Intransitive', standard: 'Intranżittiv', arabised: 'Lieżem' },
    'ditransitive': { en: 'Ditransitive', standard: 'Ditranżittiv', arabised: 'Mitgħaddi lil Mifgħulejn' },
    'both': { en: 'Both', standard: 'It-Tnejn', arabised: 'It-Tnejn' },
    'loan': { en: 'Loan', standard: 'Selfa', arabised: 'Selfa' },
    'loanword': { en: 'Loanword', standard: 'Selfa', arabised: 'Selfa' },
    'source-citation': { en: 'Source Citation', standard: "Ċitazzjoni tas-Sors", arabised: "Stexhid tal-Merġa'" },
    'primary-source-language': { en: 'Primary Source Language', standard: 'Lingwa Sors Prinċipali', arabised: "Ilsien il-Merġa' Ewlieni" },

    // Verb strength
    'strong': { en: 'Strong', standard: 'Sħiħ', arabised: 'Sħiħ' },
    'hollow': { en: 'Hollow', standard: 'Moħfi', arabised: 'Moħfi' },
    'defective': { en: 'Defective', standard: 'Difettuż', arabised: 'Nieqes' },
    'assimilative': { en: 'Assimilative', standard: 'Assimilattiv', arabised: 'Xebbiehi' },
    'doubled': { en: 'Doubled', standard: 'Trux', arabised: 'Imżewweġ' },
    'quadriliteral': { en: 'Quadriliteral', standard: 'Kwadrilitteral', arabised: 'Robgħi' },
    'strong-hybrid': { en: 'Strong-Hybrid', standard: 'Sħiħ Ibridu', arabised: 'Sħiħ Ibridu' },
    'weak-hybrid': { en: 'Weak-Hybrid', standard: 'Dgħajjef Ibridu', arabised: 'Magħlul Ibridu' },
    'mixed': { en: 'Mixed', standard: 'Imħallat', arabised: 'Imħallat' },
    'triliteral': { en: 'Triliteral', standard: 'Trilitteral', arabised: 'Tolti' },

    // Morphosyntactic categories
    'part-of-speech': { en: 'Part of Speech', standard: 'Parti tad-Diskors', arabised: 'Qasam tat-Tħaddit' },
    'table-of': { en: 'Table of', standard: 'Tabella tal-', arabised: 'Tabella tat-' },
    'conjugation': { en: 'Konjugazzjoni', standard: 'Konjugazzjoni', arabised: 'Tisrif' },
    'syntax': { en: 'Syntax', standard: 'Sintassi', arabised: 'Naħu' },
    'sentence': { en: 'Sentence', standard: 'Sentenza', arabised: 'Sentenza' },

    // Phonology
    'consonants': { en: 'Consonants', standard: 'konsonanti', arabised: 'ħossi' },
    'vowels': { en: 'Vowels', standard: 'vokali', arabised: 'leħni' },

    // Grammar roles
    'subject': { en: 'Subject', standard: 'suġġett', arabised: 'fiegħel' },
    'object': { en: 'Object', standard: 'oġġett', arabised: 'mifgħul' },

    // UI labels
    'search': { en: 'Search', standard: 'Fittex', arabised: 'Fittex' },
    'filters': { en: 'Filters', standard: 'Filtri', arabised: 'Saffajjiet' },
    'show-more': { en: 'Show More', standard: 'Uri Aktar', arabised: 'Idher Iżjed' },
    'definitions': { en: 'Definitions', standard: 'Tifsiriet', arabised: 'Tifsiriet' },
    'etymology': { en: 'Etymology', standard: 'Etimoloġija', arabised: 'Tnissil' },
    'examples': { en: 'Examples', standard: 'Eżempji', arabised: 'Xbihat' },
    'reliability': { en: 'Reliability', standard: 'Affidabilità', arabised: 'Affidabilità' },
    'source': { en: 'Source', standard: 'Sors', arabised: "Mirġgħa" },
    'sources': { en: 'Sources', standard: 'Sorsi', arabised: "Imrieġa'" },
    'arabic': { en: 'Arabic', standard: 'Għarbi', arabised: 'Għarbi' },
    'sicilian': { en: 'Sicilian', standard: 'Sqalli', arabised: 'Sqalli' },
    'italian': { en: 'Italian', standard: 'Taljan', arabised: 'Taljan' },
    'latin': { en: 'Latin', standard: 'Latin', arabised: 'Latini' },
    'french': { en: 'French', standard: 'Franċiż', arabised: 'Franċiż' },
    'english': { en: 'English', standard: 'Ingliż', arabised: 'Ingliż' },
    'spanish': { en: 'Spanish', standard: 'Spanjol', arabised: 'Spanjol' },
    'berber': { en: 'Berber', standard: 'Berberu', arabised: 'Berberi' },
    'greek': { en: 'Greek', standard: 'Grieg', arabised: 'Grieg' },

    // Dictionary UI components
    "semitic": { en: 'Semitic', standard: 'Semitiku', arabised: 'Siemi' },
    "romance": { en: 'Romance', standard: 'Rumanz', arabised: 'Rumanzi' },
    "its-audio": { en: 'its audio', standard: 'l-awdjo tiegħu', arabised: 'ħossu' },
    "audio": { en: 'Audio', standard: 'Awdjo', arabised: 'Ħoss' },
    "pronunciation": { en: 'Pronunciation', standard: 'Pronunzja', arabised: 'Tlissin' },
    'entry': { en: 'Entry', standard: 'Entrata', arabised: 'Madħla' },
    'entries': { en: 'Entries', standard: 'Entrati', arabised: 'Madħliet' },
    'form': { en: 'Form', standard: 'Forma', arabised: 'Sura' },
    'form-label': { en: 'FORM', standard: 'FORMA', arabised: 'SURA' },
    'alternative-forms': { en: 'Alternative Forms', standard: 'Forma Alternattiva', arabised: 'Sura Newwibija' },
    'inflected': { en: 'Inflected', standard: 'Infletta', arabised: 'Imsarrfa' },
    'term': { en: 'Term', standard: 'Terminu', arabised: 'Magħlqa' },
    'class': { en: 'Class', standard: 'Klassi', arabised: 'Taqsima' },
    'random': { en: 'Random', standard: 'Każwali', arabised: 'Kif Ġie Ġie' },
    'information': { en: 'Information', standard: 'Informazzjoni', arabised: 'Tagħrif' },
    'dictionary': { en: 'Dictionary', standard: 'Dizzjunarju', arabised: 'Miklem' },
    'comprehensive': { en: 'Comprehensive', standard: 'Komprensiv', arabised: 'Wesgħani' },
    'digital': { en: 'Digital', standard: 'Diġitali', arabised: 'Għaddieni' },
    'online': { en: 'online', standard: 'onlajn', arabised: 'fuq linja' },
    'researchers': { en: 'researchers', standard: 'riċerkaturi', arabised: 'fittixin' },
    'dialects': { en: 'dialects', standard: 'djaletti', arabised: 'lsejnin' },

    // Advanced Search
    'use-regular-expression': { en: 'Regex Mode', standard: 'Mod ta\' Regex', arabised: 'Mod ta\' Regex' },
    'dual-pattern': { en: 'Dual Pattern', standard: 'Mudell tal-Imtenni', arabised: 'Sura tal-Imtenni' },
    'plural-pattern': { en: 'Plural Pattern', standard: 'Mudell tal-Plural', arabised: 'Sura tal-Ġmigħ' },
    'root-consonants': { en: 'Root Consonants', standard: 'Konsonanti tal-Għerq', arabised: 'Ittri Wieqaf tal-Ġidra' },
    'vowel-set': { en: 'Vowel Set', standard: 'Sett ta\' Vokali', arabised: 'Ġmejgħa ta\' Ittri Miexi' },
    'vowel-set-perfect': { en: 'Vowel Set Perfect', standard: 'Sett ta\' Vokali Perfett', arabised: 'Ġmejgħa ta\' Ittri Miexi Tmim' },
    'vowel-set-imperfect': { en: 'Vowel Set Imperfect', standard: 'Sett ta\' Vokali Imperfett', arabised: 'Ġmejgħa ta\' Ittri Miexi Għajr Tmim' },
    'vowel-set-imperative': { en: 'Vowel Set Imperative', standard: 'Sett ta\' Vokali Imperattiv', arabised: 'Ġmejgħa ta\' Ittri Miexi Amar' },

    // Entry View
    "meaning": { en: 'Meaning', standard: 'Tifsira', arabised: 'Tagħliq' },
    "related-entries": { en: 'Related Entries', standard: 'Entrati Relatati', arabised: 'Madħliet Marbutin' },
    "transitivity": { en: 'Transitivity', standard: 'Tranżittività', arabised: 'Tgħaddija' },
    "phonetics-ipa": { en: 'Phonetics IPA', standard: 'Fonetika AFI', arabised: 'Ħossija AFI' },
    "(past)": { en: '(Past)', standard: '(Passat)', arabised: '(Mgħoddi)' },
    "(present)": { en: '(Present)', standard: '(Preżent)', arabised: '(Maħdur)' },
    "dual": { en: 'Dual', standard: 'Imtenni', arabised: 'Imtenni' },
    "entries-shown": { en: "{count} of {total} entries shown", standard: "{count} minn {total} entrati murija", arabised: "{count} minn {total} madħliet murija" },
    "search-results": { en: "Search results", standard: "Riżultati tat-tiftix", arabised: "Riżultati tat-tiftix" },
    "search-desc": { en: "Find entries and inflections in the dictionary.", standard: "Sib entrati u inflezzjonijiet fid-dizzjunarju.", arabised: "Sib madħliet u tisrifiet fil-miklem." },
    "toggle-picker": { en: "Toggle Maltese character picker", standard: "I togglja l-għażla tal-karattri Maltin", arabised: "I togglja l-għażla tal-karattri Maltin" },
    "search-lemma": { en: "Search lemma", standard: "Fittex fil-lemma", arabised: "Fittex fil-kelma" },
    "search-word-forms": { en: "Search word forms only", standard: "Fittex f'forom tal-kliem biss", arabised: "Fittex f'forom tal-kliem biss" },
    "search-english-gloss": { en: "Search in English gloss only", standard: "Fittex fit-tifsira Ingliża biss", arabised: "Fittex fit-tifsira Ingliża biss" },
    "include-suggested": { en: "Include suggested results", standard: "Inkludi riżultati ssuġġeriti", arabised: "Inkludi riżultati ssuġġeriti" },
    'max-results': { en: 'Max Results', standard: "Massimu ta' Riżultati", arabised: "L-ogħla ta' Ħsiliet" },
    "include-pending": { en: "Include pending entries", standard: "Inkludi entrati pendenti", arabised: "Inkludi entrati pendenti" },
    "include-suggested-desc": { en: "Include suggested results in the filter.", standard: "Inkludi riżultati ssuġġeriti fil-filtru.", arabised: "Inkludi riżultati ssuġġeriti fil-filtru." },
    "no-results-desc": { en: "If you think this is a mistake, feel free to suggest this term into the database.", standard: "Jekk taħseb li dan huwa żball, tħossok liberu li tissuġġerixxi dan it-terminu fid-database.", arabised: "Jekk taħseb li dan huwa għelt, int ħieles biex tissuġġerixxi dan il-magħlqa fid-database." },
    "no-results-found": { en: "No results found for '{q}'.", standard: "L-ebda riżultat ma nstab għal '{q}'.", arabised: "L-ebda riżultat ma nstab għal '{q}'." },
    "random-entries-desc": { en: "Showing some random entries to get you started.", standard: "Qed juru xi entrati każwali biex tibda.", arabised: "Qed juru xi madħliet kif ġie ġie biex tista' tibda." },
    "filter-options": { en: "Filter Options", standard: "Għażliet tal-Filtru", arabised: "Għażliet tal-Filtru" },
    "advanced-search-desc": { en: "Utilise our advanced search function to narrow down the search further.", standard: "Uża l-funzjoni tat-tiftix avvanzat sabiex tnaqqas ir-riżultati.", arabised: "Uża l-għan tat-tiftix avvanzat sabiex tnaqqas il-ħsiliet." },
    "eg-headword": { en: "e.g. ktieb", standard: "eż. ktieb", arabised: "eż. ktieb" },
    "eg-consonants": { en: "e.g. k-t-b", standard: "eż. k-t-b", arabised: "eż. k-t-b" },
    "theoretical": { en: "Theoretical", standard: "Teoretiku", arabised: "Ħsibi" },
    "auto-generated": { en: "Auto-generated", standard: "Iġġenerat Awtomatikament", arabised: "Imnissel Għoddi" },
    "no-attested-data": { en: "No attested data for root {q}.", standard: "L-ebda data attestata għall-għerq {q}.", arabised: "M'hemm data attestata għall-ġidra {q} ebda." },
    "view-root-anyway": { en: "Attempt to view root page anyway →", standard: "Ipprova ara l-paġna tal-għerq xorta waħda →", arabised: "Ipprova ara l-paġna tal-ġidra xorta waħda →" },
    "root-search-desc": { en: "Explore the morphological derivation of verbs and nouns from their base triliteral and quadriliteral roots. Enter consonants below to find matching root families.", standard: "Esplora d-derivazzjoni morfoloġika ta' verbi u nomi mill-għeruq bażiċi trilitteri u kwadrilitteri. Daħħal il-konsonanti hawn taħt biex issib familji ta' għeruq kompatibbli.", arabised: "Esplora d-derivazzjoni morfoloġika ta' verbi u nomi mill-ġidriet bażiċi trilitteri u kwadrilitteri. Daħħal il-konsonanti hawn taħt biex issib familji ta' ġidriet kompatibbli." },
    "stem": { en: "Stem", standard: "Sura", arabised: "Sura" },
    "stems": { en: "Stems", standard: "Suri", arabised: "Suri" },
    "stem-search": { en: "Stem Search", standard: "Tiftix tas-Sura", arabised: "Tiftix tas-Sura" },
    "stem-search-desc": { en: "Search for loanword verbs and other stem-based entries in the dictionary.", standard: "Fittex verbi tas-selfa u entrati oħra bbażati fuq sura fil-miklem.", arabised: "Fittex verbi tas-selfa u madħliet oħra bbażati fuq sura fil-miklem." },
    "search-stems-placeholder": { en: "Enter stem or headword...", standard: "Daħħal sura jew lemma...", arabised: "Daħħal sura jew kelma..." },
    "search-another-stem": { en: "Search Another Stem", standard: "Fittex Sura Oħra", arabised: "Fittex Sura Oħra" },
    "no-stems-found": { en: "No stems found matching your search.", standard: "L-ebda sura ma nstabet li taqbel mat-tiftix tiegħek.", arabised: "L-ebda sura ma nstabet li taqbel mat-tiftix tiegħek." },
    "root-radicals": { en: "Root Radicals", standard: "Konsonanti tal-Għerq", arabised: "Ittri tal-Ġidra" },
    "search-roots": { en: "Search Roots", standard: "Fittex l-Għeruq", arabised: "Fittex il-Ġidriet" },
    "clear": { en: "Clear", standard: "Ħassar", arabised: "Ħassar" },
    "edit-root-metadata": { en: "Edit Root Metadata", standard: "Editja l-Metadata tal-Għerq", arabised: "Editja l-Metadata tal-Ġidra" },
    "add-entry": { en: "Add Entry", standard: "Żid l-Entrata", arabised: "Żid il-Madħla" },
    "delete-entry": { en: "Delete Entry", standard: "Ħassar l-Entrata", arabised: "Ħassar il-Madħla" },
    "confirm-delete-entry": { en: "Are you sure you want to delete this entry permanently?", standard: "Żgur li trid tħassar din l-entrata b'mod permanenti?", arabised: "Żgur li trid tħassar din il-madħla b'mod permanenti?" },
    "confirm-unlink": { en: "Are you sure you want to unlink this relationship?", standard: "Żgur li trid tneħħi din ir-relazzjoni?", arabised: "Żgur li trid tneħħi din ir-relazzjoni?" },
    "failed-delete-entry": { en: "Failed to delete entry: ", standard: "Il-ħassir tal-entrata falla: ", arabised: "Il-ħassir tal-madħla falla: " },
    "failed-update-rel": { en: "L-aġġornament tar-relazzjoni falla: ", standard: "L-aġġornament tar-relazzjoni falla: ", arabised: "L-aġġornament tar-relazzjoni falla: " },
    "back-to-root-search": { en: "Back to Root Search", standard: "Irġa' Lura lejn it-Tiftix tal-Għerq", arabised: "Irġa' Lura lejn it-Tiftix tal-Ġidra" },
    "root-not-found": { en: "Root not found", standard: "L-Għerq ma nstabx", arabised: "Il-Ġidra ma nstabitx" },
    "root-not-found-desc": { en: "The root '{id}' ma nstabx fid-database tagħna. Jekk taħseb li dan l-għerq għandu jeżisti, tista' tsuġġerih biex jiżdied.", standard: "L-għerq '{id}' ma nstabx fid-database tagħna. Jekk taħseb li dan l-għerq għandu jeżisti, tista' tsuġġerih biex jiżdied.", arabised: "Il-ġidra '{id}' ma nstabitx fid-database tagħna. Jekk taħseb li din il-ġidra għandha teżisti, tista' tsuġġerilha biex tiżdied." },
    "suggest-adding-root": { en: "Suggest Adding Root", standard: "Issuġġerixxi Żieda ta' Għerq", arabised: "Issuġġerixxi Żieda ta' Ġidra" },
    "search-another-root": { en: "Search Another Root", standard: "Fittex Għerq Ieħor", arabised: "Fittex Ġidra Oħra" },
    "derived": { en: "Derived", standard: "Derivat", arabised: "Imħarreġ" },
    "related": { en: "Related", standard: "Relatat", arabised: "Marbut" },
    "manage-derived": { en: "Manage Derived Terms", standard: "Ġestjoni tat-Termini Derivati", arabised: "Ġestjoni tat-Termini Mħarrġa" },
    "manage-thesaurus": { en: "Manage Thesaurus", standard: "Ġestjoni tat-Teżawru", arabised: "Ġestjoni tat-Teżawru" },
    "link-derived-desc": { en: "Link derived entries to this root. Enter the entry ID and press Enter to confirm.", standard: "Aġġanċja entrati derivati ma' dan l-għerq. Ikteb l-ID u agħfas Enter biex tikkonferma.", arabised: "Orbot madħliet imħarrġa ma' din il-ġidra. Ikteb l-ID u agħfas Enter biex twettaq." },
    "link-thesaurus-desc": { en: "Link synonym and antonym roots. Enter the root consonants and press Enter to confirm.", standard: "Aġġanċja għeruq sinonimi u antonimi. Ikteb l-għerq u agħfas Enter biex tikkonferma.", arabised: "Orbot ġidriet sinonimi u antonimi. Ikteb il-ġidra u agħfas Enter biex twettaq." },
    "new-entry": { en: "New Entry", standard: "Entrata Ġdida", arabised: "Madħla Ġdida" },
    "new-root": { en: "New Root", standard: "Għerq Ġdid", arabised: "Ġidra Ġdida" },
    "cancel": { en: "Cancel", standard: "Ikkanċella", arabised: "Ikkanċella" },
    "save-changes": { en: "Save Changes", standard: "Issevja l-Bidliet", arabised: "Issevja l-Bidliet" },
    "failed-save-rels": { en: "L-isseyvjar tar-relazzjonijiet falla: ", standard: "L-isseyvjar tar-relazzjonijiet falla: ", arabised: "L-isseyvjar tar-relazzjonijiet falla: " },
    "email-placeholder": { en: "name@example.com", standard: "isem@eżempju.com", arabised: "isem@xbieha.com" },
    "back-to-search": { en: "Back to Search", standard: "Irġa' Lura lejn it-Tiftix", arabised: "Irġa' Lura lejn it-Tiftix" },
    "from": { en: "From", standard: "Minn", arabised: "Minn" },
    "edit-entry": { en: "Edit Entry", standard: "Editja l-Entrata", arabised: "Editja l-Madħla" },
    "gloss": { en: "Gloss", standard: "Tifsira", arabised: "Tagħliq" },
    "internal-metadata": { en: "Internal Metadata", standard: "Metadata Interna", arabised: "Metadata Interna" },
    "imala-blocked": { en: "Blocked Imala", standard: "Imala Mblukkata", arabised: "Imala Mblukkata" },
    "yes": { en: "Yes", standard: "Iva", arabised: "Iva" },
    "no": { en: "No", standard: "Le", arabised: "Le" },
    "entry-not-found": { en: "Entry not found", standard: "L-Entrata ma nstabitx", arabised: "Il-Madħla ma nstabitx" },
    "entry-not-found-desc": { en: "The entry '{id}' ma nstabitx fid-database tagħna. Jekk taħseb li din l-entrata għandha teżisti, tista' tsuġġerilha biex tiżdied.", standard: "L-entrata '{id}' ma nstabitx fid-database tagħna. Jekk taħseb li din l-entrata għandha teżisti, tista' tsuġġerilha biex tiżdied.", arabised: "Il-madħla '{id}' ma nstabitx fid-database tagħna. Jekk taħseb li din il-madħla għandha teżisti, tista' tsuġġerilha biex tiżdied." },
    "suggest-adding-entry": { en: "Suggest Adding Entry", standard: "Issuġġerixxi Żieda ta' Entrata", arabised: "Issuġġerixxi Żieda ta' Madħla" },
    "full-entry-view-coming-soon": { en: "Full entry view for {pos} coming soon.", standard: "Il-veduta sħiħa għal {pos} ġejja dalwaqt.", arabised: "Il-veduta sħiħa għal {pos} ġejja dalwaqt." },
    "search-placeholder": { en: "Search...", standard: "Fittex...", arabised: "Fittex..." },
    "toggle-terminology-standard": { en: "Switch to Standard CV terminology", standard: "Aqleb għat-terminoloġija Standard CV", arabised: "Aqleb għat-terminoloġija Standard CV" },
    "toggle-terminology-arabised": { en: "Switch to Arabised وزن terminology", standard: "Aqleb għat-terminoloġija Għarbija وزن", arabised: "Aqleb għat-terminoloġija Għarbija وزن" },
    "toggle-language-mt": { en: "Switch to Maltese language", standard: "Aqleb għal-lingwa Maltija", arabised: "Aqleb għal-lingwa Maltija" },
    "toggle-language-en": { en: "Switch to English language", standard: "Aqleb għal-lingwa Ingliża", arabised: "Aqleb għal-lingwa Ingliża" },
    "toggle-light-mode": { en: "Switch to light mode", standard: "Aqleb għall-modalità ċar", arabised: "Aqleb għall-modalità dawli" },
    "toggle-dark-mode": { en: "Switch to dark mode", standard: "Aqleb għall-modalità skur", arabised: "Aqleb għall-modalità dalmi" },
    "headword": { en: "Headword", standard: "Lemma", arabised: "Ras il-Kelma" },
    "back": { en: "Back", standard: "Lura", arabised: "Irġa'" },
    "suggest-addition": { en: "Suggest Addition", standard: "Issuġġerixxi Żieda", arabised: "Issuġġerixxi Żieda" },
    "type": { en: "Type", standard: "Tip", arabised: "Għamla" },
    "suggest-desc": { en: "Help us improve by suggesting a new entry or root.", standard: "Għinna ntejbu billi tissuġġerixxi entrata jew għerq ġdid.", arabised: "Għinna ntejbu billi tissuġġerixxi madħla jew ġidra ġdida." },
    "additional-notes": { en: "Additional Notes", standard: "Noti Addizzjonali", arabised: "Noti Addizzjonali" },
    "provide-meanings": { en: "Provide meanings, examples, or sources...", standard: "Ipprovdi tifsiriet, eżempji, jew sorsi...", arabised: "Midd tifsiriet, xbihat, jew mirġgħat..." },
    "your-email": { en: "Your Email (optional)", standard: "L-Email Tiegħek (mhux obbligatorja)", arabised: "L-Email Tiegħek (mhux ħtari)" },
    "submit-suggestion": { en: "Submit Suggestion", standard: "Ibgħat is-Suġġeriment", arabised: "Ibgħat is-Suġġeriment" },
    "thank-you": { en: "Thank You!", standard: "Grazzi!", arabised: "Grazzi!" },
    "suggestion-received": { en: "Your suggestion has been received and will be reviewed by our team.", standard: "Is-suġġeriment tiegħek jinwasal u se jiġi rivedut mit-tim tagħna.", arabised: "Is-suġġeriment tiegħek jinwasal u se jrieġa' mill-fariq tagħna." },
    "back-to-home": { en: "Back to Home", standard: "Lura għad-Dar", arabised: "Irġa' lid-Dar" },
    "sign-in": { en: "Sign in", standard: "Idħol", arabised: "Idħol" },
    "toggle-menu": { en: "Toggle menu", standard: "Ittogglja l-menu", arabised: "Ittogglja l-menu" },
    "user-view": { en: "User View", standard: "Veduta tal-Utent", arabised: "Nadar tal-Utent" },
    "admin-view": { en: "Admin View", standard: "Veduta tal-Amministratur", arabised: "Nadar tal-Amministratur" },
    "system-role-admin": { en: "Admin Access", standard: "Aċċess għall-Amministratur", arabised: "Usul għall-Amministratur" },
    "admin-dashboard": { en: "Admin Dashboard", standard: "Dashboard tal-Amministratur", arabised: "Bord tat-Taħkim tal-Amministratur" },
    "tier": { en: "Tier", standard: "Livell", arabised: "Livell" },
    "management-panel": { en: "Management Panel", standard: "Panel tal-Ġestjoni", arabised: "Panel tat-Tmexxija" },
    "live-site": { en: "Live Site", standard: "Sajt Dirett", arabised: "Sajt Ħaj" },
    "root-management": { en: "Root Management", standard: "Ġestjoni tal-Għeruq", arabised: "Ġestjoni tal-Ġidriet" },
    "word-entries": { en: "Word Entries", standard: "Entrati tal-Kliem", arabised: "Madħliet il-Kliem" },
    "content-and-blog": { en: "Content & Blog", standard: "Kontenut u Blogg", arabised: "Kontenut u Mkittba" },
    "quick-search-verification": { en: "Quick Search Verification", standard: "Verifikazzjoni tat-Tiftix Rapidu", arabised: "Verifikazzjoni tat-Tiftix Rapidu" },
    "check": { en: "Check", standard: "Iċċekkja", arabised: "Iċċekkja" },
    "browse-entries": { en: "Browse Entries", standard: "Ibbrawżja l-Entrati", arabised: "Għarbel il-Madħliet" },
    "random-entry": { en: "Random Entry", standard: "Entrata Kazwali", arabised: "Madħla Kif Ġie Ġie" },
    "browse-by-letter": { en: "Browse by Letter", standard: "Ibbrawżja skont l-Ittra", arabised: "Għarbel skont l-Ittra" },
    "all-pos": { en: "All {pos}", standard: "Il-{pos} Kollha", arabised: "Il-{pos} Kollha" },
    "verb-forms-title": { en: "Verb Forms", standard: "Forom tal-Verbi", arabised: "Użien il-Fagħal" },

    // Navbar Specific
    'advanced-search': { en: "Advanced Search", standard: "Tiftix Avvanzat", arabised: "Tiftix Mitqaddam" },
    'root-search': { en: "Root Search", standard: "Tiftix tal-Għerq", arabised: "Tiftix tal-Ġidra" },
    'suggest-entry': { en: "Suggest Entry", standard: "Issuġġerixxi Entrata", arabised: "Issuġġerixxi Madħla" },
    'help': { en: 'Help', standard: 'Għajnuna', arabised: 'Għajnuna' },

    // Home Page
    'dictionary-title': { en: "A Comprehensive Digital Maltese-English Dictionary", standard: "Dizzjunarju u Konjugatur Komprensiv Diġitali tal-Malti-Ingliż", arabised: "Miklem u Sarraf Wesgħani Għaddieni tal-Malti-Ingliż" },
    'home-desc': { en: "An ever-growing online tool for learners and researchers to the meaning, history, and usage of 300,000 words in Maltese and its dialects.", standard: "Għodda onlajn li dejjem tikber għal dawk li jitgħallmu u għar-riċerkaturi dwar it-tifsira, l-istorja u l-użu ta' 300,000 kelma bil-Malti u d-djaletti tiegħu.", arabised: "Għodda fuq linja li dejjem tikber għal dawk li jitgħallmu u għall-fittixin dwar it-tagħliq, l-oriġini u l-użu ta' 300,000 kelma bil-Malti u l-lsejnin tiegħu." },
    'ipa-audio-title': { en: "IPA & Audio Pronunciation", standard: "IPA u Pronunzja bl-Awdjo", arabised: "IPA u Tlissin bil-Ħoss" },
    'ipa-audio-desc': { en: "Every term will have its own IPA and audio to help learners.", standard: "Kull terminu se jkollu l-IPA u l-awdjo tiegħu biex jgħin lil dawk li jitgħallmu.", arabised: "Kull magħlqa se jkollha l-IPA u ħossha biex tgħin lil dawk li jitgħallmu." },
    'welcome-admin': { en: "Welcome back Admin {name}!", standard: "Merħba lura Admin {name}!", arabised: "Merħba lura Admin {name}!" },
    'root-mgmt-desc': { en: "Manage your consonants, etymology, and derived roots from one point.", standard: "Immaniġġja l-konsonanti, l-etimoloġija, u l-għeruq derivati tiegħek minn punt wieħed.", arabised: "Immaniġġja l-konsonanti, l-oriġini, u l-ġidriet imħarrġa tiegħek minn punt wieħed." },
    'word-entries-desc': { en: "Add new words, update meanings and IPA in your library of 300k+ entries.", standard: "Żid kliem ġdid, aġġorna t-tifsiriet u l-IPA fil-librerija tiegħek ta' 300k+ entrati.", arabised: "Żid kliem ġdid, aġġorna t-tagħliq u l-IPA fil-librerija tiegħek ta' 300k+ madħliet." },
    'content-blog-desc': { en: "Publish new articles and add usage examples to enhance the user experience.", standard: "Ippubblika artikli ġodda u żid eżempji ta' użu biex ttejjeb l-esperjenza tal-utent.", arabised: "Ippubblika artikli ġodda u żid tixbihat ta' użu biex ttejjeb l-esperjenza tal-utent." },
    'root-mgmt-open': { en: "Open Root Management", standard: "Iftaħ Ġestjoni tal-Għeruq", arabised: "Iftaħ Ġestjoni tal-Ġidriet" },
    'manage-entries': { en: "Manage Entries", standard: "Immaniġġja l-Entrati", arabised: "Immaniġġja l-Madħliet" },
    'edit-blog': { en: "Edit Blog", standard: "Editja Blogg", arabised: "Editja Mkittba" },
    'quick-search-verification-desc': { en: "Quickly search to verify if a word is already in the database before adding it.", standard: "Fittex malajr biex tivverifika jekk kelma hix diġà fid-database qabel ma żżidha.", arabised: "Fittex malajr biex tivverifika jekk kelma hix diġà fid-database qabel ma żżidha." },
    'search-word-placeholder': { en: "Search for a word...", standard: "Fittex kelma...", arabised: "Fittex kelma..." },
    'semitic-entries-title': { en: "Semitic Entries", standard: "Entrati Semitiċi", arabised: "Madħliet Semin" },
    'romance-entries-title': { en: "Romance Entries", standard: "Entrati Rumanzi", arabised: "Madħliet Rumanzi" },
    'semitic-entries-desc': { en: "Over 10,000 entries with 100,000 inflected word forms.", standard: "Aktar minn 10,000 entrati b'100,000 forma ta' kelma infletta.", arabised: "Aktar minn 10,000 madħla b'100,000 sura ta' kelma imsarrfa." },
    'romance-entries-desc': { en: "Over 10,000 entries with 98,000 inflected word forms.", standard: "Aktar minn 10,000 entrati b'98,000 forma ta' kelma infletta.", arabised: "Aktar minn 10,000 madħla b'98,000 sura ta' kelma imsarrfa." },
    'home-random-title': { en: "Random Entry", standard: "Entrata Każwali", arabised: "Madħla Kif Ġie Ġie" },
    'home-browse-title': { en: "Browse Entries", standard: "Ibbrawżja l-Entrati", arabised: "Għarbel il-Madħliet" },
    'results-for': { en: "Results for '{q}'", standard: "Riżultati għal '{q}'", arabised: "Riżultati għal '{q}'" },
    'entries-shown-simple': { en: "{count} results shown", standard: "{count} riżultati murija", arabised: "{count} ħsiliet murija" },
    'advanced-search-title': { en: "Advanced Search", standard: "Tiftix Avvanzat", arabised: "Tiftix Mitqaddam" },

    // Blog
    'blog': { en: "Blog", standard: "Blogg", arabised: "Imkittba" },
    'blog-desc': { en: "Articles about the Maltese language, etymology, and linguistic research.", standard: "Artikli dwar il-lingwa Maltija, l-etimoloġija, u r-riċerka lingwistika.", arabised: "Artikli dwar l-ilsien Malti, it-tnissil tal-kliem, u r-riċerka lsinija." },
    'blog-post': { en: "Blog Article", standard: "Artiklu tal-Blogg", arabised: "Artiklu tal-Imkittba" },
    'back-to-blog': { en: "Back to Blog", standard: "Lura għall-Blogg", arabised: "Erġa' għall-Imkittba" },

    // Conjugator
    'conjugator-desc': { en: "Enter a verb in the 3sg.m perfect form (e.g. kiteb, niżel, fetaħ).", standard: "Daħħal verb fil-forma 3sg.m perfett (eż. kiteb, niżel, fetaħ).", arabised: "Daħħal verb fis-sura tat-3 pers. mt. mm. tat-tmim (eż. kiteb, niżel, fetaħ)." },
    'eg-kiteb': { en: "e.g. kiteb", standard: "eż. kiteb", arabised: "eż. kiteb" },
    'conjugate': { en: "Conjugate", standard: "Ikkonjuga", arabised: "Sarraf" },
    'conjugator-demo-warning': { en: "Demo: currently only gives the CaCaC form (kiteb). Full Conjugator coming soon.", standard: "Demo: bħalissa jagħti biss il-forma CaCaC (kiteb). Il-Konġugatur sħiħ jiġi dalwaqt.", arabised: "Demo: bħalissa jagħti t-tisrif fis-sura ta' fagħal (forma I) biss. Is-Sarraf kollu jiġi daqt." },
    'basic': { en: "Basic", standard: "Bażiku", arabised: "Siesi" },

    // Is-Semmej
    'semmej-title': { en: "Is-Semmej — Name Generator", standard: "Is-Semmej — Ġeneratur tal-Ismijiet", arabised: "Is-Semmej — Nissiel l-Ismijiet" },
    'semmej-desc': { en: "Give a description of something, and Is-Semmej will create a genuine Maltese name.", standard: "Agħti deskrizzjoni ta' xi ħaġa, u s-Semmej joħloq isem Malti ġenwin.", arabised: "Agħti tifsira ta' xi ħaġa, u s-Semmej joħloq isem Malti b'qalbu u b'ruħu." },
    'semmej-label-desc': { en: "Concept Description *", standard: "Deskrizzjoni tal-Kunċett *", arabised: "Tifsira tal-Maħsub *" },
    'semmej-label-roots': { en: "Preferred Roots (comma-separated, optional)", standard: "Għeruq Preferiti (b'virgola, fakultattiv)", arabised: "Ġidriet Magħżula (b'virgola, mhux bil-fors)" },
    'semmej-btn': { en: "Create name", standard: "Semmi", arabised: "Semmi" },
    'semmej-suggestions': { en: "Suggestions", standard: "Suġġerimenti", arabised: "Suġġerimenti" },

    // Not Found
    'page-not-found': { en: "Page Not Found", standard: "Il-Paġna Ma Nstabetx", arabised: "Il-Paġna Ma Nstabetx" },
    'page-not-found-desc': { en: "This page does not exist. Perhaps the URL is incorrect or it has been removed.", standard: "Din il-paġna ma teżistix. Forsi l-URL mhix korretta jew tħassret.", arabised: "Din il-paġna ma teżistix. Forsi l-URL mhix korretta jew tħassret." },
    'go-back-home': { en: "Go Back Home", standard: "Mur Lura lejn id-Dar", arabised: "Mur Lura lejn id-Dar" },
    'search-dictionary': { en: "Search Dictionary", standard: "Fittex fid-Dizzjunarju", arabised: "Fittex fil-Miklem" },
    'maltese': { en: 'Maltese', standard: 'Malti', arabised: 'Malti' },
    'this-word': { en: 'this word', standard: 'din il-kelma', arabised: 'dil-kelma' },

    // Admin
    'admin-warning': {
        en: "The system does not recognize you as an official Admin in Clerk Metadata. We are letting you in for testing for now.",
        standard: "Is-sistema ma tagħrfekx bħala Admin uffiċjali fil-Clerk Metadata. Għalissa qed inħalluk tidħol biex tittestja.",
        arabised: "Is-sistema ma tagħrfekx bħala Admin uffiċjali fil-Clerk Metadata. Għalissa qed inħalluk tidħol biex tittestja."
    },
    'bulk-delete-confirm': { en: "Are you sure you want to delete {count} items? This cannot be undone.", standard: "Żgur li trid tħassar {count} oġġett? Din ma tistax tinqaleb.", arabised: "Żgur li trid tħassar {count} oġġett? Din ma tistax tinqaleb." },
    'delete-entry-confirm': { en: "DELETE \"{headword}\"? This cannot be undone.", standard: "ĦASSAR \"{headword}\"? Din ma tistax tinqaleb.", arabised: "ĦASSAR \"{headword}\"? Din ma tistax terġa'." },
    'delete-root-confirm': { en: "Are you sure you want to delete the root {cons}?", standard: "Żgur li trid tħassar l-għerq {cons}?", arabised: "Żgur li trid tħassar l-għerq {cons}?" },
    'items-deleted': { en: "{count} items deleted", standard: "{count} oġġett imħassar", arabised: "{count} oġġett imħassar" },
    'entry-deleted': { en: "\"{headword}\" deleted", standard: "\"{headword}\" imħassra", arabised: "\"{headword}\" imħassra" },
    'attention': { en: "Attention:", standard: "Attenzjoni:", arabised: "Intbiħ:" },
    'dashboard': { en: "Dashboard", standard: "Dashboard", arabised: "Dashboard" },
    'refresh': { en: "Refresh", standard: "Aġġorna", arabised: "Ġedded" },

    // Brand
    'brand-name': { en: "Il-Miġma'", standard: "Il-Miġma'", arabised: "Il-Miġma'" },
    'brand-desc': {
        en: "Il-Miġma' is a comprehensive digital dictionary and linguistic resource dedicated to the preservation and analysis of the Maltese language. By bridging traditional Semitic morphological patterns with modern computational linguistics, we provide researchers and learners with an unprecedented depth of data, from phonetic transcriptions to historical etymologies.",
        standard: "Il-Miġma' huwa dizzjunarju diġitali komprensiv u riżorsa lingwistika ddedikata għall-preservazzjoni u l-analiżi tal-lingwa Maltija. Billi ngħaqqdu x-xejriet morfoloġiċi Semitiċi tradizzjonali mal-lingwistika komputazzjonali moderna, nipprovdu lir-riċerkaturi u lil dawk li jitgħallmu fond ta' dejta bla preċedent, minn traskrizzjonijiet fonetiċi sa etimoloġiji storiċi.",
        arabised: "Il-Miġma' huwa miklem wesgħani u riżorsa lingwistika ddedikata għall-preservazzjoni u l-analiżi tal-ilsien Malti. Billi ngħaqqdu x-xejriet morfoloġiċi Siemi tradizzjonali mal-lingwistika komputazzjonali moderna, nipprovdu lir-riċerkaturi u lil dawk li jitgħallmu fond ta' dejta kbir, minn traskrizzjonijiet fonetiċi sa etimoloġiji storiċi."
    },

    // Footer
    'maltese-alphabets': { en: 'Maltese Alphabets', standard: 'Alfabetti Maltin', arabised: 'Alfabetti Maltin' },
    'morphology': { en: 'Morphology', standard: 'Morfoloġija', arabised: 'Tisrif' },
    'terminologies': { en: 'Terminologies', standard: 'Terminoloġiji', arabised: 'Magħlqijiet' },
    'suggest-dialect-entry': { en: 'Suggest Dialect Entry', standard: 'Issuġġerixxi Entrata Djalettali', arabised: 'Issuġġerixxi Madħla Lsejnija' },
    'report-error': { en: 'Report Error', standard: 'Irrapporta Żball', arabised: 'Irrapporta Għelt' },
    'contribute': { en: 'Contribute', standard: 'Ikkontribwixxi', arabised: 'Għin lill-Proġett' },
    'recorded': { en: 'recorded', standard: 'reġistrati', arabised: 'reġistrati' },
    'view-all': { en: 'View all', standard: 'Ara kollox', arabised: 'Ara kollox' },
    'recently-added': { en: 'Recently Added', standard: 'Miżjuda Reċentement', arabised: 'Miżjuda dal-Aħħar' },

    // Entry UI
    'share': { en: 'Share', standard: 'Aqsam', arabised: 'Xierek' },
    'report': { en: 'Report', standard: 'Irrapporta', arabised: 'Irrapporta' },
    'under-this-word': { en: 'Under this word', standard: 'Taħt din il-kelma', arabised: 'Taħt dil-kelma' },
    'etymology-not-available': { en: 'Etymology not available', standard: 'L-etimoloġija mhux disponibbli.', arabised: 'It-tnissil mhux disponibbli.' },

    // Reliability
    'very-reliable': { en: 'Very Reliable', standard: 'Affidabbli Ħafna', arabised: 'Affidabbli Ħafna' },
    'reliable': { en: 'Reliable', standard: 'Affidabbli', arabised: 'Affidabbli' },
    'partially-reliable': { en: 'Partially Reliable', standard: 'Parzjalment Affidabbli', arabised: 'Affidabbli biċ-ċejċa' },
    'uncertain': { en: 'Uncertain', standard: 'Inċert', arabised: 'Mhux żgur' },
    'attestation-reliability': { en: 'Attestation Reliability', standard: 'Affidabbiltà tal-Attestament', arabised: 'Affidabbiltà tal-Attestament' },
    'reliability-score-desc': { en: "The score is calculated based on the weighting of different academic sources.", standard: "Il-punteġġ huwa kkalkajat abbażi tal-pesatura ta' sorsi akkademiċi differenti.", arabised: "Il-punteġġ huwa kkalkajat abbażi tal-pesatura ta' sorsi akkademiċi differenti." },

    // Morphology Grid
    'regular-plural': { en: 'Regular Plural', standard: 'Plural Regolari', arabised: 'Ġmigħ Sħiħ' },
    'diminutive': { en: 'Diminutive', standard: 'Diminuttiv', arabised: 'Tiżgħir' },
    'collective': { en: 'Collective', standard: 'Kollettiv', arabised: 'Ġemmiegħi' },
    'singulative': { en: 'Singulative', standard: 'Singulattiv', arabised: 'Farradi' },
    'unit': { en: 'Unit', standard: 'Unità', arabised: 'Unità' },
    'verbal': { en: 'Verbal', standard: 'Verbali', arabised: 'Fagħli' },
    'form-title': { en: 'Form', standard: 'Forma', arabised: 'Forma' },
    'strength-title': { en: 'Strength', standard: 'Saħħa', arabised: 'Saħħa' },
    'masdar-label': { en: 'Verbal Noun', standard: 'Nom verbali', arabised: 'Misder' },
    'elative': { en: 'Elative', standard: 'Elattiv', arabised: 'Mifgħul fard' },
    'masculine-fem': { en: 'Masculine / Feminine', standard: 'Maskili / Femminil', arabised: 'Imdakkar / Immarri' },
    'inflection-table': { en: 'Inflection Table', standard: 'Tabella tal-Inflezzjoni', arabised: 'Tabella tat-Tisrif' },
    'attached-pronouns': { en: 'Attached Pronouns', standard: 'Pronomi Mehmuża', arabised: 'Dmirijiet Mehmuża' },
    'base-form': { en: 'Base Form', standard: 'Forma Bażika', arabised: 'Sura Sies' },
    'with-pronoun': { en: 'With Pronoun', standard: 'Bl-Anness', arabised: 'Bl-Anness' },
    'broken-plural': { en: 'Broken Plural', standard: 'Plural Miksur', arabised: 'Ġmigħ Miksur' },

    // Tag labels (ui_terminology convention: tag-<normalized-tag-key>)
    'tag-common': { en: 'Common', standard: 'Komuni', arabised: 'Imferrex' },
    'tag-semitic-core': { en: 'Semitic Core', standard: 'Qalba Semitika', arabised: 'Qalba Siemi' },
    'tag-romance-core': { en: 'Romance Core', standard: 'Qalba Rumanz', arabised: 'Qalba Rumanzi' },
    'tag-colour': { en: 'Colour', standard: 'Kulur', arabised: 'Lewn' },
    'tag-color': { en: 'Color', standard: 'Kulur', arabised: 'Lewn' },
    'tag-theoretical': { en: 'Theoretical', standard: 'Teoretiku', arabised: 'Ħsibi' },
    'tag-base': { en: 'Base', standard: 'Bażi', arabised: 'Sies' },
    'tag-derived': { en: 'Derived', standard: 'Derivat', arabised: 'Imħarreġ' },
    'tag-arabism': { en: 'Arabism', standard: 'Arabiżmu', arabised: 'Għerubija' },
    'tag-archaic': { en: 'Archaic', standard: 'Arkajku', arabised: 'Qadim' },
    'tag-obsolete': { en: 'Obsolete', standard: 'Skadut', arabised: 'Mherri' },
    'tag-puristic': { en: 'Puristic', standard: 'Puristiku', arabised: 'Safi' },
    'tag-rgħajn': { en: 'Rgħajn', standard: 'Rgħajn', arabised: 'Rgħajn' },
    'tag-loan': { en: 'Loan', standard: 'Selfa', arabised: 'Selfa' },

    // TierGate
    'is-a-feature': { en: "{label} is a {tier} feature", standard: "{label} hija feature {tier}", arabised: "{label} hija ghalik fil-livell {tier}" },
    'upgrade-to': { en: "Upgrade to {tier}", standard: "Aġġorna għal {tier}", arabised: "Ittejjeb għal {tier}" },
    'feature-pro-desc': { en: "Upgrade to Pro to unlock this and many more features.", standard: "Aġġorna għal Pro biex tiftaħ din u ħafna aktar.", arabised: "Ittejjeb għal Pro biex tiftaħ din u ħafna aktar." },
    'feature-enterprise-desc': { en: "Enterprise plan required. Contact us to get started.", standard: "Il-pjan Enterprise meħtieġ. Ikkuntattjana biex tibda.", arabised: "Il-pjan Enterprise meħtieġ. Asalna biex tibda." },
    'pro-label': { en: 'Pro', standard: 'Pro', arabised: 'Pro' },
    'enterprise-label': { en: 'Enterprise', standard: 'Intrapriża', arabised: 'Intrapriża' },
};

const TERM_ALIASES: Record<string, string> = {
    partiklu: 'particle',
};

function normalizeTermKey(key: string) {
    const lower = key.toLowerCase();
    return TERM_ALIASES[lower] || lower;
}

/** Resolve a term key against the current linguistic mode and interface language */
export function resolveTerm(key: string, mode: LinguisticMode, lang: 'en' | 'mt' = 'mt'): string {
    const entry = TERMINOLOGY[normalizeTermKey(key)];
    if (!entry) return key;
    if (lang === 'en') return entry.en || key.charAt(0).toUpperCase() + key.slice(1);
    return mode === 'arabised' ? entry.arabised : entry.standard;
}

/** Get the POS display label for a given POS key + mode + lang */
export function getPOSLabel(pos: string, mode: LinguisticMode, lang: 'en' | 'mt' = 'mt'): string {
    return resolveTerm(pos, mode, lang);
}
