import type { LinguisticMode } from '@/types';

// ─── Terminology Map ───────────────────────────────────────────────────────
// Maps a term key to its English, Standard and Arabised Maltese equivalents.

export const TERMINOLOGY: Record<string, { en?: string; standard: string; arabised: string }> = {
    // Morphological patterns
    'cv-pattern': { en: 'CV Pattern', standard: "Mudell ta' CV", arabised: "Xbieha ta' Wiżen" },
    'mudell-cv': { en: 'CV Pattern', standard: "Mudell ta' CV", arabised: "Xbieha ta' Wiżen" },
    'demonym': { en: 'Demonym', standard: 'Demonym', arabised: 'Nisba' },
    'għerq': { en: 'Root', standard: 'Għerq', arabised: 'Ġidra' },
    'dgħajjef': { en: 'Weak', standard: 'Dgħajjef', arabised: 'Magħlul' },
    'trux': { en: 'Geminated', standard: 'Trux', arabised: 'Imżewweġ' },
    'verbal forms': { en: 'Verbal Forms', standard: 'Forom Verbali', arabised: 'Użien' },
    'lemma': { en: 'Lemma', standard: 'Lemma', arabised: 'Ras il-Kelma' },
    'passive': { en: 'Passive', standard: 'Passiv', arabised: 'Mifgħul' },
    'active': { en: 'Active', standard: 'Attiv', arabised: 'Fiegħel' },
    'noun type': { en: 'Noun Type', standard: "Tip ta' Nom", arabised: "Għamla ta' Isem" },
    'dialect': { en: 'Dialect', standard: 'Djalett', arabised: 'Ilsejjen' },
    'conjugation table': { en: 'Conjugation Table', standard: 'Tabella tal-Konjugazzjoni', arabised: 'Tabella tat-Tisrif' },
    'person': { en: 'Person', standard: 'Persuna', arabised: 'Nifs' },
    'imperfett': { en: 'Imperfect', standard: 'Imperfett', arabised: 'Għajr Tmim' },
    'perfett': { en: 'Perfect', standard: 'Perfett', arabised: 'Tmim' },
    'imperattiv': { en: 'Imperative', standard: 'Imperattiv', arabised: 'Amar' },
    'singular': { en: 'Singular', standard: 'Singular', arabised: 'Fard' },
    'plural': { en: 'Plural', standard: 'Plural', arabised: 'Ġmigħ' },
    'jiena': { en: 'I', standard: 'Jiena', arabised: 'Jiena' },
    'inti': { en: 'You (singular)', standard: 'Inti', arabised: 'Inti' },
    'huwa': { en: 'He', standard: 'Huwa', arabised: 'Huwa' },
    'hija': { en: 'She', standard: 'Hija', arabised: 'Hija' },
    'aħna': { en: 'We', standard: 'Aħna', arabised: 'Aħna' },
    'intom': { en: 'You (plural)', standard: 'Intom', arabised: 'Intom' },
    'huma': { en: 'They', standard: 'Huma', arabised: 'Huma' },
    'polarità': { en: 'Polarity', standard: 'Polarità', arabised: 'Għamudija' },
    'positive': { en: 'Positive', standard: 'Pożittiv', arabised: 'Qagħdi' },
    'negative': { en: 'Negative', standard: 'Negattiv', arabised: 'Ċaħdi' },
    'oġġett dirett': { en: 'Direct Object', standard: 'Oġġett Dirett', arabised: 'Mifgħul bih l-Ewwel' },
    'oġġett indirett': { en: 'Indirect Object', standard: 'Oġġett Indirett', arabised: 'Mifgħul bih it-Tieni' },
    'termini derivati': { en: 'Derived Terms', standard: 'Termini Derivati', arabised: 'Termini Maħruġa' },
    'nom verbali': { en: 'Verbal Noun', standard: 'Nom Verbali', arabised: 'Isem Fagħli' },
    'partiċipju passiv': { en: 'Passive Participle', standard: 'Partiċipju Passiv', arabised: 'Mifgħul' },
    'partiċipju attiv': { en: 'Active Participle', standard: 'Partiċipju Attiv', arabised: 'Fiegħel' },
    'eżempju ta\' użu': { en: 'Usage Example', standard: "Eżempju ta' Użu", arabised: "Tixbih ta' Użu" },
    'tesawru': { en: 'Thesaurus', standard: 'Teżawru', arabised: 'Maħżen' },
    'sinonimi': { en: 'Synonyms', standard: 'Sinonimi', arabised: 'Mixxibhin' },
    'antonimi': { en: 'Antonyms', standard: 'Antonimi', arabised: 'Mitfirqin' },

    // Parts of Speech — Maltese keys
    'verb': { en: 'Verb', standard: 'Verb', arabised: 'Fagħal' },
    'nom': { en: 'Noun', standard: 'Nom', arabised: 'Isem' },
    'aġġettiv': { en: 'Adjective', standard: 'Aġġettiv', arabised: 'Isem Fissieri' },
    'avverbju': { en: 'Adverb', standard: 'Avverbju', arabised: 'Għatu' },
    'partiklu': { en: 'Particle', standard: 'Partiklu', arabised: 'Intejfa' },
    'prepożizzjoni': { en: 'Preposition', standard: 'Prepożizzjoni', arabised: 'Intejfa Ġarrari' },
    'konġunzjoni': { en: 'Conjunction', standard: 'Konġunzjoni', arabised: 'Intejfa Għaqqadi' },
    'artiklu': { en: 'Article', standard: 'Artiklu', arabised: 'Għodda tat-Tagħrif' },
    'interrogattiv': { en: 'Interrogative', standard: 'Interrogattiv', arabised: 'Għodda Saqsejja' },
    'pronom': { en: 'Pronoun', standard: 'Pronom', arabised: 'Dmir' },
    'partiċipju': { en: 'Participle', standard: 'Partiċipju', arabised: 'Xerriek' },
    'numerali': { en: 'Numeral', standard: 'Numerali', arabised: 'Għaddi' },
    'interjezzjoni': { en: 'Interjection', standard: 'Interjezzjoni', arabised: 'Tagħġiba' },

    // Parts of Speech — English aliases (keys used by admin config)
    'noun': { en: 'Noun', standard: 'Nom', arabised: 'Isem' },
    'adjective': { en: 'Adjective', standard: 'Aġġettiv', arabised: 'Isem Fissieri' },
    'adverb': { en: 'Adverb', standard: 'Avverbju', arabised: 'Għatu' },
    'particle': { en: 'Particle', standard: 'Partiklu', arabised: 'Ntejfa' },
    'preposition': { en: 'Preposition', standard: 'Prepożizzjoni', arabised: 'Ntejfa Ġarrari' },
    'conjunction': { en: 'Conjunction', standard: 'Konġunzjoni', arabised: 'Ntejfa Għaqqadi' },
    'article': { en: 'Article', standard: 'Artiklu', arabised: 'Għodda tat-Tagħrif' },
    'interrogative': { en: 'Interrogative', standard: 'Interrogattiv', arabised: 'Għodda Saqsejja' },
    'pronoun': { en: 'Pronoun', standard: 'Pronom', arabised: 'Dmir' },
    'participle': { en: 'Participle', standard: 'Partiċipju', arabised: 'Xerriek' },
    'numeral': { en: 'Numeral', standard: 'Numerali', arabised: 'Għaddi' },
    'interjection': { en: 'Interjection', standard: 'Interjezzjoni', arabised: 'Tagħġiba' },
    'prefix': { en: 'Prefix', standard: 'Prefiss', arabised: 'Qagħda Quddimija' },
    'suffix': { en: 'Suffix', standard: 'Suffiss', arabised: 'Qagħda Warranija' },
    'masculine': { en: 'Masculine', standard: 'Maskili', arabised: 'Mdakkar' },
    'feminine': { en: 'Feminine', standard: 'Femminil', arabised: 'Mmarri' },
    'neutral': { en: 'Neutral', standard: 'Newtrali', arabised: 'Newtrali' },
    'transitive': { en: 'Transitive', standard: 'Tranżittiv', arabised: 'Mitgħaddi' },
    'intransitive': { en: 'Intransitive', standard: 'Intranżittiv', arabised: 'Lieżem' },
    'ditransitive': { en: 'Ditransitive', standard: 'Ditranżittiv', arabised: 'Mitgħaddi lil Mifgħulejn' },
    'both': { en: 'Both', standard: 'It-Tnejn', arabised: 'Klihaom' },
    'loanword': { en: 'Loanword', standard: 'Selfa', arabised: 'Selfa' },

    // Verb strength (English engine keys)
    'strong': { en: 'Strong', standard: 'Sħiħ', arabised: 'Sħiħ' },
    'weak': { en: 'Weak', standard: 'Dgħajjef', arabised: 'Magħlul' },
    'geminated': { en: 'Geminated', standard: 'Trux', arabised: 'Imżewweġ' },
    'hollow': { en: 'Hollow', standard: 'Moħfi', arabised: 'Moħfi' },
    'defective': { en: 'Defective', standard: 'Difettuż', arabised: 'Nieqes' },
    'assimilative': { en: 'Assimilative', standard: 'Assimilattiv', arabised: 'Xebbiehi' },
    'doubled': { en: 'Doubled', standard: 'Mirdum', arabised: 'Imżewweġ' },
    'quadriliteral': { en: 'Quadriliteral', standard: 'Kwadrilitteral', arabised: 'Robugħi' },
    'triliteral': { en: 'Triliteral', standard: 'Trilitteral', arabised: 'Tolti' },

    // Morphosyntactic categories
    'parti tad-diskors': { en: 'Part of Speech', standard: 'Parti tad-Diskors', arabised: 'Qasam tat-Tħaddit' },
    'tabella tal-': { en: 'Table of ', standard: 'Tabella tal-', arabised: 'Tabella tat-' },
    'konjugazzjoni': { en: 'Conjugation', standard: 'Konjugazzjoni', arabised: 'Tisrif' },
    'sintassi': { en: 'Syntax', standard: 'Sintassi', arabised: 'Naħu' },
    'sentenza': { en: 'Sentence', standard: 'Sentenza', arabised: 'Sensiela tal-Kliem Sħiħ' },

    // Phonology
    'konsonanti': { en: 'Consonants', standard: 'konsonanti', arabised: 'ħossi' },
    'vokali': { en: 'Vowels', standard: 'vokali', arabised: 'leħni' },

    // Grammar roles
    'suġġett': { en: 'Subject', standard: 'suġġett', arabised: 'fiegħel' },
    'oġġett': { en: 'Object', standard: 'oġġett', arabised: 'mifgħul' },

    // UI labels
    'search': { en: 'Search', standard: 'Search', arabised: 'Tfittxija' },
    'definitions': { en: 'Definitions', standard: 'Tifsiriet', arabised: 'Tifsiriet' },
    'etymology': { en: 'Etymology', standard: 'Oriġini', arabised: 'Oriġini' },
    'examples': { en: 'Examples', standard: 'Eżempji', arabised: 'Eżempji' },
    'reliability': { en: 'Reliability', standard: 'Reliability', arabised: 'Affidabilità' },
    'sors': { en: 'Source', standard: 'Sors', arabised: "Mirġgħa" },
    'sorsi': { en: 'Sources', standard: 'Sorsi', arabised: "Imrieġa'" },
    'massimu ta\' riżultati': { en: 'Max Results', standard: 'Massimu ta\' Riżultati', arabised: 'L-ogħla ta\' Ħsiliet' },
    'tabella ta\'': { en: 'Table of', standard: 'Tabella tal-', arabised: 'Tabella tat-' },
    'arabic': { en: 'Arabic', standard: 'Għarbi', arabised: 'Għarbi' },
    'sicilian': { en: 'Sicilian', standard: 'Sqalli', arabised: 'Sqalli' },
    'italian': { en: 'Italian', standard: 'Taljan', arabised: 'Taljan' },
    'latin': { en: 'Latin', standard: 'Latin', arabised: 'Latini' },
    'french': { en: 'French', standard: 'Franċiż', arabised: 'Franċiż' },
    'english': { en: 'English', standard: 'Ingliż', arabised: 'Ingliż' },
    'spanish': { en: 'Spanish', standard: 'Spanjol', arabised: 'Spanjol' },
    'berber': { en: 'Berber', standard: 'Berberu', arabised: 'Berberi' },
    'greek': { en: 'Greek', standard: 'Grieg', arabised: 'Grieg' },

    // Dictionary UI components
    "semitiku": { en: 'Semitic', standard: 'Semitiku', arabised: 'Siemi' },
    "rumanz": { en: 'Romance', standard: 'Rumanz', arabised: 'Rumanzi' },
    "l-awdjo tiegħu": { en: 'its audio', standard: 'l-awdjo tiegħu', arabised: 'ħossu' },
    "l-awdjo": { en: 'Audio', standard: 'l-Awdjo', arabised: 'il-Ħoss' },
    "pronunzja": { en: 'Pronunciation', standard: 'Pronunzja', arabised: 'Tlissin' },
    'entrata': { en: 'Entry', standard: 'Entrata', arabised: 'Madħla' },
    'entrati': { en: 'Entries', standard: 'Entrati', arabised: 'Madħliet' },
    'forma': { en: 'Form', standard: 'Forma', arabised: 'Sura' },
    'forma-label': { en: 'FORM', standard: 'FORMA', arabised: 'SURA' },
    'infletta': { en: 'Inflected', standard: 'Infletta', arabised: 'Imsarrfa' },
    'term': { en: 'Term', standard: 'Terminu', arabised: 'Magħlqa' },
    'class': { en: 'Class', standard: 'Klassi', arabised: 'Taqsima' },
    'każwali': { en: 'Random', standard: 'Każwali', arabised: 'Kif Ġie Ġie' },
    'informazzjoni': { en: 'Information', standard: 'Informazzjoni', arabised: 'Tagħrif' },
    'dizzjunarju': { en: 'Dictionary', standard: 'Dizzjunarju', arabised: 'Miklem' },
    'komprensiv': { en: 'Comprehensive', standard: 'Komprensiv', arabised: 'Wesgħani' },
    'diġitali': { en: 'Digital', standard: 'Diġitali', arabised: 'Għaddieni' },
    'onlajn': { en: 'Online', standard: 'onlajn', arabised: 'fuq linja' },
    'riċerkaturi': { en: 'Researchers', standard: 'riċerkaturi', arabised: 'fittixin' },
    'djaletti': { en: 'Dialects', standard: 'djaletti', arabised: 'lsejnin' },

    // Advanced Search
    'mudell tal-imtenni': { en: 'Dual Pattern', standard: 'Mudell tal-Imtenni', arabised: 'Sura tal-Imtenni' },
    'mudell tal-plural': { en: 'Plural Pattern', standard: 'Mudell tal-Plural', arabised: 'Sura tal-Ġmigħ' },
    'konsonanti tal-għerq': { en: 'Root Consonants', standard: 'Konsonanti tal-Għerq', arabised: 'Ittri Wieqaf tal-Ġidra' },
    'sett ta\' vokali': { en: 'Vowel Set', standard: 'Sett ta\' Vokali', arabised: 'Ġmejgħa ta\' Ittri Miexi' },

    // Entry View
    "etimoloġija": { en: 'Etymology', standard: 'Etimoloġija', arabised: 'Tinsil' },
    "tifsira": { en: 'Meaning', standard: 'Tifsira', arabised: 'Tagħliq' },
    "entrati relatati": { en: 'Related Entries', standard: 'Entrati Relatati', arabised: 'Madħliet Marbutin' },
    "tranżittività": { en: 'Transitivity', standard: 'Tranżittività', arabised: 'Tgħaddija' },
    "fonetika afi": { en: 'Phonetics IPA', standard: 'Fonetika AFI', arabised: 'Ħossija AFI' },
    "(past)": { en: '(Past)', standard: '(Passat)', arabised: '(Mgħoddi)' },
    "(present)": { en: '(Present)', standard: '(Preżent)', arabised: '(Maħdur)' },
    "dual": { en: 'Dual', standard: 'Imtenni', arabised: 'Mewweġ' },
    "results-for": { en: "Results for '{q}'", standard: "Riżultati għal '{q}'", arabised: "Riżultati għal '{q}'" },
    "entries-shown": { en: "{count} of {total} entries shown", standard: "{count} minn {total} entrati murija", arabised: "{count} minn {total} madħliet murija" },
    "search-results": { en: "Search results", standard: "Riżultati tat-tiftix", arabised: "Riżultati tat-tiftix" },
    "search-desc": { en: "Find entries and inflections in the dictionary.", standard: "Sib entrati u tasrifiet fid-dizzjunarju.", arabised: "Sib madħliet u tasrifiet fil-maħżen." },
    "toggle-picker": { en: "Toggle Maltese character picker", standard: "I togglja l-għażla tal-karattri Maltin", arabised: "I togglja l-għażla tal-karattri Maltin" },
    "search-lemma": { en: "Search lemma", standard: "Fittex fil-lemma", arabised: "Fittex fil-kelma" },
    "search-word-forms": { en: "Search word forms only", standard: "Fittex f'forom tal-kliem biss", arabised: "Fittex f'forom tal-kliem biss" },
    "search-english-gloss": { en: "Search in English gloss only", standard: "Fittex fit-tifsira Ingliża biss", arabised: "Fittex fit-tifsira Ingliża biss" },
    "include-suggested": { en: "Include suggested results", standard: "Inkludi riżultati ssuġġeriti", arabised: "Inkludi riżultati ssuġġeriti" },
    'max-results': { en: 'Max Results', standard: "Massimu ta' Riżultati", arabised: "L-ogħla ta' Ħsiliet" },
    "part-of-speech": { en: "Part of Speech", standard: "Parti tad-diskors", arabised: "Qasam tat-tħaddit" },
    "include-pending": { en: "Include pending entries", standard: "Inkludi entrati pendenti", arabised: "Inkludi entrati pendenti" },
    "include-suggested-desc": { en: "Include suggested results in the filter.", standard: "Inkludi riżultati ssuġġeriti fil-filtru.", arabised: "Inkludi riżultati ssuġġeriti fil-filtru." },
    "no-results-desc": { en: "If you think this is a mistake, feel free to suggest this term into the database.", standard: "Jekk taħseb li dan huwa żball, tħossok liberu li tissuġġerixxi dan it-terminu fid-database.", arabised: "Jekk taħseb li dan huwa żball, tħossok liberu li tissuġġerixxi dan it-terminu fid-database." },
    "no-results-found": { en: "No results found for '{q}'.", standard: "L-ebda riżultat ma nstab għal '{q}'.", arabised: "L-ebda riżultat ma nstab għal '{q}'." },
    "eg-headword": { en: "e.g. ktieb", standard: "eż. ktieb", arabised: "eż. ktieb" },
    "eg-consonants": { en: "e.g. k-t-b", standard: "eż. k-t-b", arabised: "eż. k-t-b" },
    "theoretical": { en: "Theoretical", standard: "Teoretiku", arabised: "Teoretiku" },
    "auto-generated": { en: "Auto-generated", standard: "Iġġenerat Awtomatikament", arabised: "Iġġenerat Awtomatikament" },
    "no-attested-data": { en: "No attested data for root {q}.", standard: "L-ebda data attestata għall-għerq {q}.", arabised: "L-ebda data attestata għall-ġidra {q}." },
    "view-root-anyway": { en: "Attempt to view root page anyway →", standard: "Ipprova ara l-paġna tal-għerq xorta waħda →", arabised: "Ipprova ara l-paġna tal-ġidra xorta waħda →" },
    "root-search-desc": { en: "Explore the morphological derivation of verbs and nouns from their base triliteral and quadriliteral roots. Enter consonants below to find matching root families.", standard: "Esplora d-derivazzjoni morfoloġika ta' verbi u nomi mill-għeruq bażiċi trilitteri u kwadrilitteri. Daħħal il-konsonanti hawn taħt biex issib familji ta' għeruq kompatibbli.", arabised: "Esplora d-derivazzjoni morfoloġika ta' verbi u nomi mill-ġidriet bażiċi trilitteri u kwadrilitteri. Daħħal il-konsonanti hawn taħt biex issib familji ta' ġidriet kompatibbli." },
    "root-radicals": { en: "Root Radicals", standard: "Konsonanti tal-Għerq", arabised: "Ittri tal-Ġidra" },
    "search-roots": { en: "Search Roots", standard: "Fittex l-Għeruq", arabised: "Fittex il-Ġidriet" },
    "clear": { en: "Clear", standard: "Ħassar", arabised: "Ħassar" },
    "edit-root-metadata": { en: "Edit Root Metadata", standard: "Editja l-Metadata tal-Għerq", arabised: "Editja l-Metadata tal-Ġidra" },
    "add-entry": { en: "Add Entry", standard: "Żid l-Entrata", arabised: "Żid il-Madħla" },
    "delete-entry": { en: "Delete Entry", standard: "Ħassar l-Entrata", arabised: "Ħassar il-Madħla" },
    "confirm-delete-entry": { en: "Are you sure you want to delete this entry permanently?", standard: "Żgur li trid tħassar din l-entrata b'mod permanenti?", arabised: "Żgur li trid tħassar din il-madħla b'mod permanenti?" },
    "confirm-unlink": { en: "Are you sure you want to unlink this relationship?", standard: "Żgur li trid tneħħi din ir-relazzjoni?", arabised: "Żgur li trid tneħħi din ir-relazzjoni?" },
    "failed-delete-entry": { en: "Failed to delete entry: ", standard: "Il-ħassir tal-entrata falla: ", arabised: "Il-ħassir tal-madħla falla: " },
    "failed-update-rel": { en: "Failed to update relationship: ", standard: "L-aġġornament tar-relazzjoni falla: ", arabised: "L-aġġornament tar-relazzjoni falla: " },
    "back-to-root-search": { en: "Back to Root Search", standard: "Irġa' Lura lejn it-Tiftix tal-Għerq", arabised: "Irġa' Lura lejn it-Tiftix tal-Ġidra" },
    "root-not-found": { en: "Root not found", standard: "L-Għerq ma nstabx", arabised: "Il-Ġidra ma nstabitx" },
    "root-not-found-desc": { en: "The root '{id}' was not found in our database. If you believe this root should exist, you can suggest it for addition.", standard: "L-għerq '{id}' ma nstabx fid-database tagħna. Jekk taħseb li dan l-għerq għandu jeżisti, tista' tsuġġerih biex jiżdied.", arabised: "Il-ġidra '{id}' ma nstabitx fid-database tagħna. Jekk taħseb li din il-ġidra għandha teżisti, tista' tsuġġerilha biex tiżdied." },
    "suggest-adding-root": { en: "Suggest Adding Root", standard: "Issuġġerixxi Żieda ta' Għerq", arabised: "Issuġġerixxi Żieda ta' Ġidra" },
    "search-another-root": { en: "Search Another Root", standard: "Fittex Għerq Ieħor", arabised: "Fittex Ġidra Oħra" },
    "derived": { en: "Derived", standard: "Derivat", arabised: "Imħarreġ" },
    "related": { en: "Related", standard: "Relatat", arabised: "Marbut" },
    "manage-derived": { en: "Manage Derived Terms", standard: "Ġestjoni tat-Termini Derivati", arabised: "Ġestjoni tat-Termini Mħarrġa" },
    "manage-thesaurus": { en: "Manage Thesaurus", standard: "Ġestjoni tat-Teżawru", arabised: "Ġestjoni tat-Teżawru" },
    "link-derived-desc": { en: "Link derived entries to this root. Enter the entry ID and press Enter to confirm.", standard: "Aġġanċja entrati derivati ma' dan l-għerq. Ikteb l-ID u agħfas Enter biex tikkonferma.", arabised: "Orbot madħliet imħarrġa ma' din il-ġidra. Ikteb l-ID u agħfas Enter biex twettaq." },
    "link-thesaurus-desc": { en: "Link synonym and antonym roots. Enter the root consonants and press Enter to confirm.", standard: "Aġġanċja għeruq sinonimi u antonimi. Ikteb l-għerq u agħfas Enter biex tikkonferma.", arabised: "Orbot ġidriet sinonimi u antonimi. Ikteb il-ġidra u agħfas Enter biex twettaq." },
    "new-entry": { en: "New Entry", standard: "Entrata Ġdida", arabised: "Madħla Ġdida" },
    "new-root": { en: "New Root", standard: "Għerq Ġdid", arabised: "Ġidra Ġdida" },
    "cancel": { en: "Cancel", standard: "Ikkanċella", arabised: "Ikkanċella" },
    "save-changes": { en: "Save Changes", standard: "Issevja l-Bidliet", arabised: "Issevja l-Bidliet" },
    "failed-save-rels": { en: "Failed to save relationships: ", standard: "L-isseyvjar tar-relazzjonijiet falla: ", arabised: "L-isseyvjar tar-relazzjonijiet falla: " },
    "email-placeholder": { en: "name@example.com", standard: "isem@eżempju.com", arabised: "isem@eżempju.com" },
    "back-to-search": { en: "Back to Search", standard: "Irġa' Lura lejn it-Tiftix", arabised: "Irġa' Lura lejn it-Tiftix" },
    "from": { en: "From ", standard: "Minn ", arabised: "Minn " },
    "edit-entry": { en: "Edit Entry", standard: "Editja l-Entrata", arabised: "Editja l-Madħla" },
    "gloss": { en: "Gloss", standard: "Tifsira", arabised: "Tagħliq" },
    "internal-metadata": { en: "Internal Metadata", standard: "Metadata Interna", arabised: "Metadata Interna" },
    "imala-blocked": { en: "Imala Blocked", standard: "Imala Imblukkata", arabised: "Imala Imblukkata" },
    "yes": { en: "Yes", standard: "Iva", arabised: "Iva" },
    "no": { en: "No", standard: "Le", arabised: "Le" },
    "entry-not-found": { en: "Entry not found", standard: "L-Entrata ma nstabitx", arabised: "Il-Madħla ma nstabitx" },
    "entry-not-found-desc": { en: "The entry '{id}' was not found in our database. If you believe this entry should exist, you can suggest it for addition.", standard: "L-entrata '{id}' ma nstabitx fid-database tagħna. Jekk taħseb li din l-entrata għandha teżisti, tista' tsuġġerilha biex tiżdied.", arabised: "Il-madħla '{id}' ma nstabitx fid-database tagħna. Jekk taħseb li din il-madħla għandha teżisti, tista' tsuġġerilha biex tiżdied." },
    "suggest-adding-entry": { en: "Suggest Adding Entry", standard: "Issuġġerixxi Żieda ta' Entrata", arabised: "Issuġġerixxi Żieda ta' Madħla" },
    "full-entry-view-coming-soon": { en: "Full entry view for {pos} coming soon.", standard: "Il-veduta sħiħa għal {pos} ġejja dalwaqt.", arabised: "Il-veduta sħiħa għal {pos} ġejja dalwaqt." },
    "search-placeholder": { en: "Search...", standard: "Fittex...", arabised: "Fittex..." },
    "toggle-terminology-standard": { en: "Switch to Standard CV terminology", standard: "Aqleb għat-terminoloġija Standard CV", arabised: "Aqleb għat-terminoloġija Standard CV" },
    "toggle-terminology-arabised": { en: "Switch to Arabised وزن terminology", standard: "Aqleb għat-terminoloġija Għarbija وزن", arabised: "Aqleb għat-terminoloġija Għarbija وزن" },
    "toggle-language-mt": { en: "Switch to Maltese language", standard: "Aqleb għal-lingwa Maltija", arabised: "Aqleb għal-lingwa Maltija" },
    "toggle-language-en": { en: "Switch to English language", standard: "Aqleb għal-lingwa Ingliża", arabised: "Aqleb għal-lingwa Ingliża" },
    "toggle-light-mode": { en: "Switch to light mode", standard: "Aqleb għall-mod ċar", arabised: "Aqleb għall-mod ċar" },
    "toggle-dark-mode": { en: "Switch to dark mode", standard: "Aqleb għall-mod skur", arabised: "Aqleb għall-mod skur" },
    "headword": { en: "Headword", standard: "Ras il-Kelma", arabised: "Ras il-Kelma" },
    "consonants": { en: "Consonants", standard: "Konsonanti", arabised: "Konsonanti" },
    "back": { en: "Back", standard: "Lura", arabised: "Lura" },
    "suggest-addition": { en: "Suggest Addition", standard: "Issuġġerixxi Żieda", arabised: "Issuġġerixxi Żieda" },
    "suggest-desc": { en: "Help us improve by suggesting a new entry or root.", standard: "Għinna ntejbu billi tsuġġerixxi entrata jew għerq ġdid.", arabised: "Għinna ntejbu billi tsuġġerixxi madħla jew ġidra ġida." },
    "additional-notes": { en: "Additional Notes", standard: "Noti Addizzjonali", arabised: "Noti Addizzjonali" },
    "provide-meanings": { en: "Provide meanings, examples, or sources...", standard: "Ipprovdi tifsiriet, eżempji, jew sorsi...", arabised: "Ipprovdi tifsiriet, eżempji, jew sorsi..." },
    "your-email": { en: "Your Email (optional)", standard: "L-Email Tiegħek (mhux obbligatorja)", arabised: "L-Email Tiegħek (mhux obbligatorja)" },
    "submit-suggestion": { en: "Submit Suggestion", standard: "Ibgħat is-Suġġeriment", arabised: "Ibgħat is-Suġġeriment" },
    "thank-you": { en: "Thank You!", standard: "Grazzi!", arabised: "Grazzi!" },
    "suggestion-received": { en: "Your suggestion has been received and will be reviewed by our team.", standard: "Is-suġġeriment tiegħek jinwasal u se jiġi rivedut mit-tim tagħna.", arabised: "Is-suġġeriment tiegħek jinwasal u se jiġi rivedut mit-tim tagħna." },
    "back-to-home": { en: "Back to Home", standard: "Lura għall-Home", arabised: "Lura għall-Home" },
    "sign-in": { en: "Sign in", standard: "Idħol", arabised: "Idħol" },
    "toggle-menu": { en: "Toggle menu", standard: "I togglja l-menu", arabised: "I togglja l-menu" },
    "user-view": { en: "User View", standard: "Veduta tal-Utent", arabised: "Veduta tal-Utent" },
    "admin-view": { en: "Admin View", standard: "Veduta tal-Amministratur", arabised: "Veduta tal-Amministratur" },
    "system-role-admin": { en: "Admin Access", standard: "Aċċess għall-Amministratur", arabised: "Aċċess għall-Amministratur" },
    "admin-dashboard": { en: "Admin Dashboard", standard: "Dashboard tal-Amministratur", arabised: "Dashboard tal-Amministratur" },
    "tier": { en: "Tier", standard: "Livell", arabised: "Livell" },

    // Navbar Specific
    'advanced-search': { en: 'Advanced Search', standard: 'Tiftix Avvanzat', arabised: 'Tiftix Mitqaddam' },
    'root-search': { en: 'Root Search', standard: 'Tiftix tal-Ġidriet', arabised: 'Tiftix tal-Ġidriet' },
    'suggest-entry': { en: 'Suggest Entry', standard: 'Issuġġerixxi Entrata', arabised: 'Ressaq Madħla' },
    'information': { en: 'Information', standard: 'Tagħrif', arabised: 'Tagħrif' },
    'help': { en: 'Help', standard: 'Għajnuna', arabised: 'Għajnuna' },
};

/** Resolve a term key against the current linguistic mode and interface language */
export function resolveTerm(key: string, mode: LinguisticMode, lang: 'en' | 'mt' = 'mt'): string {
    const entry = TERMINOLOGY[key.toLowerCase()];
    if (!entry) return key;
    if (lang === 'en') return entry.en || key.charAt(0).toUpperCase() + key.slice(1);
    return mode === 'arabised' ? entry.arabised : entry.standard;
}

/** Get the POS display label for a given POS key + mode + lang */
export function getPOSLabel(pos: string, mode: LinguisticMode, lang: 'en' | 'mt' = 'mt'): string {
    return resolveTerm(pos, mode, lang);
}
