export type SurfaceMarker = 'plain' | 'theoretical' | 'auto_generated';

type SurfaceLike = {
    marker?: SurfaceMarker | null;
    theoretical?: boolean | null;
    value?: unknown;
    form?: unknown;
    headword?: unknown;
    text?: unknown;
    label?: unknown;
};

function readSurfaceText(surface: SurfaceLike): string {
    const candidates = [surface.value, surface.form, surface.headword, surface.text, surface.label];
    for (const candidate of candidates) {
        if (typeof candidate === 'string') return candidate.trim();
    }
    return '';
}

export function stripTheoreticalPrefix(value: string) {
    return String(value || '').trim().replace(/^[*✦]+\s*/, '').trim();
}

export function normalizeSurfaceText(surface: unknown): string {
    if (typeof surface === 'string') return surface.trim();
    if (!surface || typeof surface !== 'object') return '';
    return readSurfaceText(surface as SurfaceLike);
}

export function isTheoreticalSurface(surface: unknown): boolean {
    if (typeof surface === 'string') {
        return surface.trim().startsWith('*');
    }

    if (!surface || typeof surface !== 'object') return false;

    const obj = surface as SurfaceLike;
    if (obj.theoretical === true) return true;
    if (obj.marker === 'theoretical') return true;

    return normalizeSurfaceText(obj).startsWith('*');
}

export function isAutoGeneratedSurface(surface: unknown): boolean {
    if (typeof surface === 'string') {
        return surface.trim().startsWith('✦');
    }

    if (!surface || typeof surface !== 'object') return false;

    const obj = surface as SurfaceLike;
    if (obj.marker === 'auto_generated') return true;

    return normalizeSurfaceText(obj).startsWith('✦');
}

export function shouldHideSurface(surface: unknown, hideTheoreticalForms: boolean): boolean {
    if (!hideTheoreticalForms) return false;
    return isTheoreticalSurface(surface) || isAutoGeneratedSurface(surface);
}

export function getVisibleSurfaceText(surface: unknown, hideTheoreticalForms: boolean): string {
    const text = normalizeSurfaceText(surface);
    return hideTheoreticalForms ? stripTheoreticalPrefix(text) : text;
}
