import { useEffect, useState } from 'react';
import { Link, Navigate, useParams, useSearchParams } from 'react-router-dom';
import { ArrowLeft, BookOpen, Info } from 'lucide-react';
import { useHideTheoreticalForms } from '@/contexts/HideTheoreticalFormsContext';
import { useLinguisticMode } from '@/contexts/LinguisticModeContext';
import { apiGetPattern, type PatternDetailGroup, type PatternDetailResponse } from '@/lib/api';
import { Card } from '@/components/ui/Card';
import { BrowseViewSwitch, type BrowseViewMode } from '@/components/browse/BrowseViewSwitch';
import { normalizePluralFormRows } from '@/lib/pluralForms';
import { isAutoGeneratedSurface, isTheoreticalSurface, shouldHideSurface } from '@/lib/theoreticalForms';
import { convertCVTo1V } from '@/lib/maltesePhonology';

const CREAM_RGBA = 'rgba(244,243,240,0.88)';

function getPatternEntryDisplayValue(entry: PatternDetailResponse['entries'][number]) {
    const matchedSurface = (entry.match_display_value || entry.plural_display || '').trim();
    return matchedSurface || entry.headword.trim();
}

function PatternEntryCard({
    entry,
    term,
    hidePos = false,
    hideMorph = false,
}: {
    entry: PatternDetailResponse['entries'][number];
    term: (key: string) => string;
    hidePos?: boolean;
    hideMorph?: boolean;
}) {
    const cardTitle = getPatternEntryDisplayValue(entry);
    const isMarkedTitle = isTheoreticalSurface(cardTitle) || isAutoGeneratedSurface(cardTitle);
    const rootLabel = entry.root_consonants || '';
    const rootHref = entry.root_id ? `/root/${entry.root_id}` : '';
    const roleLabel = entry.morphology_group_label || '';
    const headwordLabel = entry.headword.trim();
    const showHeadword = entry.morphology_group_key !== 'lemma' && headwordLabel && headwordLabel !== cardTitle;

    return (
        <div className="h-full w-full overflow-hidden rounded-2xl border border-black/8 bg-white shadow-sm">
            <div className="grid h-full grid-cols-1 md:grid-cols-[minmax(0,1fr)_9.5rem]">
                <div className="border-b border-black/5 px-4 py-4 md:border-b-0 md:py-3.5">
                    <Link
                        to={`/entry/${entry.id}`}
                        className={`block font-serif text-[1.2rem] font-extrabold leading-tight hover:underline ${isMarkedTitle ? 'text-black/55' : 'text-black'}`}
                    >
                        {cardTitle || entry.headword}
                    </Link>

                    <div className="mt-1 flex flex-wrap items-center gap-x-2 gap-y-0.5">
                        {rootLabel && (
                            rootHref ? (
                                <Link
                                    to={rootHref}
                                    style={{ color: '#1034A6' }}
                                    className="font-sans text-xs hover:underline"
                                >
                                    {rootLabel}
                                </Link>
                            ) : (
                                <span className="font-sans text-xs text-black/55">
                                    {rootLabel}
                                </span>
                            )
                        )}
                    </div>

                    {entry.definition && (
                        <p className="mt-2.5 text-[13px] leading-6 text-black/90">
                            {entry.definition}
                        </p>
                    )}
                </div>

                <div className="flex flex-col items-start justify-start gap-0.5 px-4 py-4 md:items-end md:justify-self-end md:border-l md:border-black/5 md:text-right md:py-3.5">
                    {!hidePos && (
                        <span className="font-sans text-[10px] font-semibold uppercase tracking-[0.18em] leading-snug text-black/55 md:text-right">
                            {term(entry.pos).toUpperCase()}
                        </span>
                    )}
                    {!hideMorph && roleLabel && (
                        <span className="font-sans text-[10px] font-semibold uppercase tracking-[0.18em] leading-snug text-black md:text-right">
                            {roleLabel.toUpperCase()}
                        </span>
                    )}
                    {showHeadword && (
                        <div className="mt-2.5 w-full border-t border-black/5 pt-2.5 md:w-auto md:min-w-0">
                            <div className="font-sans text-[9px] font-bold uppercase tracking-[0.22em] text-black/30">
                                {term('headword') || 'Headword'}
                            </div>
                            <div className="font-serif text-[13px] leading-tight text-black/70 md:text-right">
                                {headwordLabel}
                            </div>
                        </div>
                    )}
                </div>
            </div>
        </div>
    );
}

export function Pattern() {
    const { id } = useParams<{ id: string }>();
    const [searchParams, setSearchParams] = useSearchParams();
    const { term, mode } = useLinguisticMode();
    const { hideTheoreticalForms } = useHideTheoreticalForms();
    const [data, setData] = useState<PatternDetailResponse | null>(null);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState<string | null>(null);
    const selectedMode: BrowseViewMode = searchParams.get('mode') === 'morphology' ? 'morphology' : 'pos';
    const [selectedGroupKey, setSelectedGroupKey] = useState<string>('all');

    useEffect(() => {
        if (!id) return;
        setLoading(true);
        apiGetPattern(id)
            .then(res => {
                setData(res);
                setLoading(false);
            })
            .catch(err => {
                setError(err.message);
                setLoading(false);
            });
    }, [id]);

    useEffect(() => {
        if (data?.pattern) {
            const displayPat = mode === 'arabised' ? data.pattern.wizen_notation : convertCVTo1V(data.pattern.cv_notation);
            document.title = `${displayPat} — ${term('pattern')} | Il-Miġma'`;
        }
    }, [data, term, mode]);

    const bgStyle = {
        background: `linear-gradient(${CREAM_RGBA}, ${CREAM_RGBA}), url("/bg-pattern.webp") center/cover no-repeat`,
        minHeight: '100vh',
    };

    const entryGroups = data?.entry_groups?.[selectedMode] ?? [];
    const visibleEntryGroups: PatternDetailGroup[] = entryGroups
        .map((group) => {
            const entries = group.entries.filter((entry) => {
                if (!hideTheoreticalForms) return true;

                const candidateSurfaces = [
                    entry.headword,
                    entry.match_display_value,
                    entry.plural_display,
                    ...(normalizePluralFormRows(entry.inflections_pl).map((row) => row.form)),
                ];

                return !candidateSurfaces.some((surface) => shouldHideSurface(surface, hideTheoreticalForms));
            });

            return {
                ...group,
                count: entries.length,
                entries,
            };
        })
        .filter((group) => group.entries.length > 0);
    const totalEntries = visibleEntryGroups.reduce((sum, group) => sum + group.count, 0);
    const activeGroupKey = selectedGroupKey !== 'all' && visibleEntryGroups.some((group) => group.key === selectedGroupKey)
        ? selectedGroupKey
        : 'all';
    const selectedEntryGroups = activeGroupKey === 'all'
        ? visibleEntryGroups
        : visibleEntryGroups.filter((group) => group.key === activeGroupKey);

    useEffect(() => {
        setSelectedGroupKey('all');
    }, [selectedMode, id]);

    useEffect(() => {
        if (selectedGroupKey === 'all') return;
        if (!visibleEntryGroups.some((group) => group.key === selectedGroupKey)) {
            setSelectedGroupKey('all');
        }
    }, [selectedGroupKey, visibleEntryGroups]);

    if (!id) return <Navigate to="/404" replace />;

    const setMode = (nextMode: BrowseViewMode) => {
        const nextParams = new URLSearchParams(searchParams);
        nextParams.set('mode', nextMode);
        setSearchParams(nextParams);
    };

    if (loading) {
        return (
            <div style={bgStyle} className="flex justify-center items-center h-screen">
                <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-[#1034A6]"></div>
            </div>
        );
    }

    if (error || !data?.pattern) {
        return (
            <div style={bgStyle} className="flex flex-col items-center justify-center h-screen px-4 text-center">
                <h2 className="font-serif text-2xl font-bold text-black mb-2">{term('error')}</h2>
                <p className="text-text-muted mb-6">{error || term('pattern-not-found')}</p>
                <Link to="/browse/pattern" className="text-link hover:underline flex items-center gap-2">
                    <ArrowLeft size={16} /> {term('back-to-browse')}
                </Link>
            </div>
        );
    }

    const { pattern, roles } = data;
    const primaryNotation = mode === 'arabised' ? pattern.wizen_notation : convertCVTo1V(pattern.cv_notation);
    const secondaryNotation = mode === 'arabised' ? convertCVTo1V(pattern.cv_notation) : pattern.wizen_notation;

    return (
        <div style={bgStyle} className="w-full">
            <div className="max-w-6xl mx-auto px-7 sm:px-8 py-20 pb-20">

                {/* Header Section */}
                <div className="flex flex-col md:flex-row gap-10 items-start mb-16">
                    <div className="flex-1">
                        <div className="flex flex-wrap items-baseline gap-x-5 gap-y-2 mb-4">
                            <h1 className="font-serif font-bold text-[2rem] sm:text-[3rem] leading-none text-black">
                                {primaryNotation}
                            </h1>
                            <span className="font-serif font-medium italic text-[1.8rem] sm:text-[2.8rem] leading-none text-black/55 tracking-tight">
                                {secondaryNotation}
                            </span>
                        </div>

                        {pattern.description && (
                            <div className="bg-white/40 backdrop-blur-sm border border-black/5 rounded-2xl p-6 relative group overflow-hidden">
                                <div className="absolute top-0 left-0 w-1 h-full bg-link/20" />
                                <div className="flex gap-3">
                                    <Info size={18} className="text-link mt-0.5 shrink-0" />
                                    <p className="text-sm text-black/80 leading-relaxed italic">
                                        {pattern.description}
                                    </p>
                                </div>
                            </div>
                        )}
                    </div>

                    {/* Metadata Card */}
                    <Card className="w-full md:w-80 border-black/5 bg-white/60 backdrop-blur-md p-8 rounded-3xl shadow-xl shadow-black/5">
                        <div className="space-y-6">
                            <div>
                                <h2 className="text-[10px] font-bold uppercase tracking-widest text-black/30 mb-3">{term('linguistic-roles')}</h2>
                                <div className="flex flex-wrap gap-2">
                                    {roles.length > 0 ? roles.map((r: any, i: number) => (
                                        <div key={i} className="flex flex-col gap-0.5">
                                            <span className="px-2.5 py-1 bg-black/5 text-black/70 rounded-lg text-[11px] font-medium border border-black/5">
                                                {term(r.linguistic_role || r.category)}
                                            </span>
                                            <span className="text-[9px] text-black/30 uppercase tracking-tighter px-1">
                                                {r.pos} {r.gender ? `• ${r.gender}` : ''}
                                            </span>
                                        </div>
                                    )) : (
                                        <span className="text-xs text-black/40 italic">{term('uncategorized')}</span>
                                    )}
                                </div>
                            </div>

                            {pattern.example_word && (
                                <div>
                                    <h2 className="text-[10px] font-bold uppercase tracking-widest text-black/30 mb-2">{term('example-word')}</h2>
                                    <p className="font-serif text-lg text-black">{pattern.example_word}</p>
                                </div>
                            )}

                            <div className="pt-6 border-t border-black/5">
                                <div className="flex items-center justify-between text-xs text-black/40">
                                    <span>{term('internal-id')}</span>
                                    <code className="font-mono text-[10px] opacity-60">{pattern.id}</code>
                                </div>
                            </div>
                        </div>
                    </Card>
                </div>

                {/* Entries List Section */}
                <div className="space-y-6">
                    <div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between">
                        <div
                            role="tablist"
                            aria-label="Pattern entry filters"
                            className="inline-flex w-full flex-wrap items-end gap-1.5 border-b border-black/10 lg:w-auto"
                        >
                            <button
                                type="button"
                                role="tab"
                                aria-selected={activeGroupKey === 'all'}
                                onClick={() => setSelectedGroupKey('all')}
                                className={`relative -mb-px border-b-2 px-4 py-3 text-sm font-semibold uppercase tracking-[0.2em] whitespace-nowrap transition-colors focus:outline-none focus-visible:ring-2 focus-visible:ring-link/20 focus-visible:ring-offset-2 focus-visible:ring-offset-transparent ${activeGroupKey === 'all'
                                    ? 'border-link text-black'
                                    : 'border-transparent text-black/45 hover:border-black/20 hover:text-black'
                                    }`}
                            >
                                All ({totalEntries})
                            </button>
                            {visibleEntryGroups.map((group) => {
                                const isActive = activeGroupKey === group.key;

                                return (
                                    <button
                                        key={group.key}
                                        type="button"
                                        role="tab"
                                        aria-selected={isActive}
                                        onClick={() => setSelectedGroupKey(group.key)}
                                        className={`relative -mb-px border-b-2 px-4 py-3 text-sm font-semibold uppercase tracking-[0.2em] whitespace-nowrap transition-colors focus:outline-none focus-visible:ring-2 focus-visible:ring-link/20 focus-visible:ring-offset-2 focus-visible:ring-offset-transparent ${isActive
                                            ? 'border-link text-black'
                                            : 'border-transparent text-black/45 hover:border-black/20 hover:text-black'
                                            }`}
                                    >
                                        {group.label} ({group.count})
                                    </button>
                                );
                            })}
                        </div>

                        <BrowseViewSwitch
                            mode={selectedMode}
                            onChange={setMode}
                            ariaLabel="Pattern entry view mode"
                            className="lg:ml-auto"
                        />
                    </div>

                    {selectedEntryGroups.length > 0 ? (
                        <div className="space-y-10">
                            {selectedEntryGroups.map((group: PatternDetailGroup) => (
                                <section key={group.key} className="space-y-5">
                                    <div className="flex items-center gap-3">
                                        <h3 className="font-serif text-2xl font-bold text-black">
                                            {group.label}
                                        </h3>
                                        <div className="h-px flex-1 bg-black/8" />
                                        <span className="text-[10px] font-bold uppercase tracking-widest text-black/30">
                                            {group.count}
                                        </span>
                                    </div>

                                    <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-4">
                                        {group.entries.map((entry) => (
                                            <PatternEntryCard
                                                key={entry.id}
                                                entry={entry}
                                                term={term}
                                                hidePos={selectedMode === 'pos'}
                                                hideMorph={selectedMode === 'morphology'}
                                            />
                                        ))}
                                    </div>
                                </section>
                            ))}
                        </div>
                    ) : (
                        <div className="col-span-full py-16 text-center bg-black/5 rounded-3xl border border-dashed border-black/10">
                            <BookOpen size={40} className="mx-auto text-black/10 mb-4" />
                            <p className="text-black/30 font-medium">{term('no-entries-found')}</p>
                        </div>
                    )}
                </div>

            </div>
        </div>
    );
}
