import { useEffect, useState } from 'react';
import { Link, Navigate, useParams, useSearchParams } from 'react-router-dom';
import { ArrowLeft, BookOpen, Info } from 'lucide-react';
import { useHideTheoreticalForms } from '@/contexts/HideTheoreticalFormsContext';
import { useLinguisticMode } from '@/contexts/LinguisticModeContext';
import { apiGetPattern, type PatternDetailGroup, type PatternDetailResponse } from '@/lib/api';
import { Card } from '@/components/ui/Card';
import { BrowseViewSwitch, type BrowseViewMode } from '@/components/browse/BrowseViewSwitch';
import { normalizePluralFormRows } from '@/lib/pluralForms';
import { isAutoGeneratedSurface, isTheoreticalSurface, shouldHideSurface } from '@/lib/theoreticalForms';

const CREAM_RGBA = 'rgba(244,243,240,0.88)';

function getPatternEntryDisplayValue(entry: PatternDetailResponse['entries'][number]) {
    const matchedSurface = (entry.match_display_value || entry.plural_display || '').trim();
    return matchedSurface || entry.headword.trim();
}

function PatternEntryCard({
    entry,
    term,
}: {
    entry: PatternDetailResponse['entries'][number];
    term: (key: string) => string;
}) {
    const cardTitle = getPatternEntryDisplayValue(entry);
    const isMarkedTitle = isTheoreticalSurface(cardTitle) || isAutoGeneratedSurface(cardTitle);
    const rootLabel = entry.root_consonants || '';
    const rootHref = entry.root_id ? `/root/${entry.root_id}` : '';
    const roleLabel = entry.morphology_group_label || '';
    const headwordLabel = entry.headword.trim();
    const showHeadword = entry.morphology_group_key !== 'lemma' && headwordLabel && headwordLabel !== cardTitle;

    return (
        <div className="bg-white rounded-xl border border-black/8 shadow-sm overflow-hidden mb-3 w-full">
            <div className="flex flex-col md:grid md:grid-cols-[minmax(0,1fr)_11rem] min-h-20">
                <div className="px-5 py-4 border-b md:border-b-0 border-black/5">
                    <Link
                        to={`/entry/${entry.id}`}
                        className={`font-serif font-extrabold text-[1.35rem] leading-tight block hover:underline ${isMarkedTitle ? 'text-black/55' : 'text-black'}`}
                    >
                        {cardTitle || entry.headword}
                    </Link>

                    <div className="mt-0.5 flex flex-wrap items-center gap-x-2">
                        {rootLabel && (
                            rootHref ? (
                                <Link
                                    to={rootHref}
                                    style={{ color: '#1034A6' }}
                                    className="text-xs hover:underline font-sans"
                                >
                                    {rootLabel}
                                </Link>
                            ) : (
                                <span className="text-xs text-black/55 font-sans">
                                    {rootLabel}
                                </span>
                            )
                        )}
                    </div>

                    {entry.definition && (
                        <p className="mt-3 text-sm text-black leading-relaxed">
                            {entry.definition}
                        </p>
                    )}
                </div>

                <div className="px-5 py-4 flex flex-col items-start justify-start gap-0.5 md:items-end md:text-right md:justify-self-end">
                    <span className="font-sans text-xs font-normal uppercase tracking-tight leading-snug text-black md:text-right">
                        {term(entry.pos).toUpperCase()}
                    </span>
                    {roleLabel && (
                        <span className="font-sans text-xs font-normal uppercase tracking-tight leading-snug text-black md:text-right">
                            {roleLabel.toUpperCase()}
                        </span>
                    )}
                    {showHeadword && (
                        <div className="mt-3 pt-3 border-t border-black/5 w-full md:w-auto md:min-w-0">
                            <div className="font-sans text-[10px] font-bold uppercase tracking-widest text-black/30">
                                {term('headword') || 'Headword'}
                            </div>
                            <div className="font-serif text-sm leading-tight text-black/70 md:text-right">
                                {headwordLabel}
                            </div>
                        </div>
                    )}
                </div>
            </div>
        </div>
    );
}

export function Pattern() {
    const { id } = useParams<{ id: string }>();
    const [searchParams, setSearchParams] = useSearchParams();
    const { term, mode } = useLinguisticMode();
    const { hideTheoreticalForms } = useHideTheoreticalForms();
    const [data, setData] = useState<PatternDetailResponse | null>(null);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState<string | null>(null);
    const selectedMode: BrowseViewMode = searchParams.get('mode') === 'morphology' ? 'morphology' : 'pos';

    useEffect(() => {
        if (!id) return;
        setLoading(true);
        apiGetPattern(id)
            .then(res => {
                setData(res);
                setLoading(false);
            })
            .catch(err => {
                setError(err.message);
                setLoading(false);
            });
    }, [id]);

    useEffect(() => {
        if (data?.pattern) {
            document.title = `${data.pattern.cv_notation} — ${term('pattern')} | Il-Miġma'`;
        }
    }, [data, term]);

    const bgStyle = {
        background: `linear-gradient(${CREAM_RGBA}, ${CREAM_RGBA}), url("/bg-pattern.png") center/cover no-repeat`,
        minHeight: '100vh',
    };

    if (!id) return <Navigate to="/404" replace />;

    const entryGroups = data?.entry_groups?.[selectedMode] ?? [];
    const visibleEntryGroups: PatternDetailGroup[] = entryGroups
        .map((group) => {
            const entries = group.entries.filter((entry) => {
                if (!hideTheoreticalForms) return true;

                const candidateSurfaces = [
                    entry.headword,
                    entry.match_display_value,
                    entry.plural_display,
                    ...(normalizePluralFormRows(entry.inflections_pl).map((row) => row.form)),
                ];

                return !candidateSurfaces.some((surface) => shouldHideSurface(surface, hideTheoreticalForms));
            });

            return {
                ...group,
                count: entries.length,
                entries,
            };
        })
        .filter((group) => group.entries.length > 0);
    const totalEntries = visibleEntryGroups.reduce((sum, group) => sum + group.count, 0);
    const setMode = (nextMode: BrowseViewMode) => {
        const nextParams = new URLSearchParams(searchParams);
        nextParams.set('mode', nextMode);
        setSearchParams(nextParams);
    };

    if (loading) {
        return (
            <div style={bgStyle} className="flex justify-center items-center h-screen">
                <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-[#1034A6]"></div>
            </div>
        );
    }

    if (error || !data?.pattern) {
        return (
            <div style={bgStyle} className="flex flex-col items-center justify-center h-screen px-4 text-center">
                <h2 className="font-serif text-2xl font-bold text-black mb-2">{term('error')}</h2>
                <p className="text-text-muted mb-6">{error || term('pattern-not-found')}</p>
                <Link to="/browse/pattern" className="text-link hover:underline flex items-center gap-2">
                    <ArrowLeft size={16} /> {term('back-to-browse')}
                </Link>
            </div>
        );
    }

    const { pattern, roles } = data;
    const primaryNotation = mode === 'arabised' ? pattern.wizen_notation : pattern.cv_notation;
    const secondaryNotation = mode === 'arabised' ? pattern.cv_notation : pattern.wizen_notation;

    return (
        <div style={bgStyle} className="w-full">
            <div className="max-w-6xl mx-auto px-7 sm:px-8 py-10 pb-20">

                {/* Back Link */}
                <div className="mb-10">
                    <Link to="/browse/pattern" className="group text-sm text-black/40 hover:text-black flex items-center gap-1 transition-all">
                        <ArrowLeft size={16} className="group-hover:-translate-x-1 transition-transform" />
                        {term('back-to-browse')}
                    </Link>
                </div>

                {/* Header Section */}
                <div className="flex flex-col md:flex-row gap-10 items-start mb-16">
                    <div className="flex-1">
                        <div className="flex items-center gap-4 mb-2">
                            <span className="px-3 py-1 bg-link/10 text-link rounded-full text-[10px] font-bold uppercase tracking-widest border border-link/10">
                                {term('morphological-pattern')}
                            </span>
                        </div>
                        <div className="flex flex-wrap items-baseline gap-x-5 gap-y-2 mb-4">
                            <h1 className="font-serif font-bold text-[3.5rem] leading-none text-black tracking-tight">
                                {primaryNotation}
                            </h1>
                            <span className="font-serif font-medium italic text-[2.15rem] leading-none text-black/55 tracking-tight">
                                {secondaryNotation}
                            </span>
                        </div>

                        {pattern.description && (
                            <div className="bg-white/40 backdrop-blur-sm border border-black/5 rounded-2xl p-6 relative group overflow-hidden">
                                <div className="absolute top-0 left-0 w-1 h-full bg-link/20" />
                                <div className="flex gap-3">
                                    <Info size={18} className="text-link mt-0.5 shrink-0" />
                                    <p className="text-sm text-black/80 leading-relaxed italic">
                                        {pattern.description}
                                    </p>
                                </div>
                            </div>
                        )}
                    </div>

                    {/* Metadata Card */}
                    <Card className="w-full md:w-80 border-black/5 bg-white/60 backdrop-blur-md p-8 rounded-3xl shadow-xl shadow-black/5">
                        <div className="space-y-6">
                            <div>
                                <h2 className="text-[10px] font-bold uppercase tracking-widest text-black/30 mb-3">{term('linguistic-roles')}</h2>
                                <div className="flex flex-wrap gap-2">
                                    {roles.length > 0 ? roles.map((r: any, i: number) => (
                                        <div key={i} className="flex flex-col gap-0.5">
                                            <span className="px-2.5 py-1 bg-black/5 text-black/70 rounded-lg text-[11px] font-medium border border-black/5">
                                                {term(r.linguistic_role || r.category)}
                                            </span>
                                            <span className="text-[9px] text-black/30 uppercase tracking-tighter px-1">
                                                {r.pos} {r.gender ? `• ${r.gender}` : ''}
                                            </span>
                                        </div>
                                    )) : (
                                        <span className="text-xs text-black/40 italic">{term('uncategorized')}</span>
                                    )}
                                </div>
                            </div>

                            {pattern.example_word && (
                                <div>
                                    <h2 className="text-[10px] font-bold uppercase tracking-widest text-black/30 mb-2">{term('example-word')}</h2>
                                    <p className="font-serif text-lg text-black">{pattern.example_word}</p>
                                </div>
                            )}

                            <div className="pt-6 border-t border-black/5">
                                <div className="flex items-center justify-between text-xs text-black/40">
                                    <span>{term('internal-id')}</span>
                                    <code className="font-mono text-[10px] opacity-60">{pattern.id}</code>
                                </div>
                            </div>
                        </div>
                    </Card>
                </div>

                {/* Entries List Section */}
                <div className="space-y-8">
                    <div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between">
                        <div className="flex items-end gap-4">
                            <h2 className="font-serif text-2xl font-bold text-black border-l-4 border-link pl-4">
                                {term('entries-using-this-pattern')}
                            </h2>
                            <span className="text-xs font-bold text-black/30 uppercase tracking-widest bg-black/5 px-3 py-1 rounded-full">
                                {totalEntries} {term('entries')}
                            </span>
                        </div>

                        <BrowseViewSwitch
                            mode={selectedMode}
                            onChange={setMode}
                            ariaLabel="Pattern entry view mode"
                            className="lg:ml-auto"
                        />
                    </div>

                    <div className="flex items-center gap-4">
                        <div className="h-px flex-1 bg-black/5" />
                        <span className="text-xs font-bold text-black/30 uppercase tracking-widest bg-black/5 px-3 py-1 rounded-full">
                            {selectedMode === 'pos' ? 'POS' : 'Morphology'}
                        </span>
                    </div>

                    {visibleEntryGroups.length > 0 ? (
                        <div className="space-y-14">
                            {visibleEntryGroups.map((group: PatternDetailGroup) => (
                                <section key={group.key} className="space-y-8">
                                    <div className="flex items-center gap-4">
                                        <div className="border-l-4 border-link pl-5">
                                            <h3 className="font-serif text-3xl font-bold text-black">
                                                {group.label}
                                            </h3>
                                        </div>
                                        <div className="h-px flex-1 bg-black/8" />
                                        <span className="text-[10px] font-bold uppercase tracking-widest text-black/30">
                                            {group.count}
                                        </span>
                                    </div>

                                    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                                        {group.entries.map((entry) => (
                                            <PatternEntryCard
                                                key={entry.id}
                                                entry={entry}
                                                term={term}
                                            />
                                        ))}
                                    </div>
                                </section>
                            ))}
                        </div>
                    ) : (
                        <div className="col-span-full py-16 text-center bg-black/5 rounded-3xl border border-dashed border-black/10">
                            <BookOpen size={40} className="mx-auto text-black/10 mb-4" />
                            <p className="text-black/30 font-medium">{term('no-entries-found')}</p>
                        </div>
                    )}
                </div>

            </div>
        </div>
    );
}
