import React, { useState, useEffect, useMemo, useRef } from 'react';
import { Link, useSearchParams, useNavigate } from 'react-router-dom';
import { Search as SearchIcon, Keyboard, MessageSquare, Filter, ChevronDown, ChevronUp, Shuffle, Loader2 } from 'lucide-react';
import { cn } from '@/lib/utils';
import { MalteseCharPicker } from '@/components/ui/MalteseCharPicker';
import { useLanguage } from '@/contexts/LanguageContext';
import { useLinguisticMode } from '@/contexts/LinguisticModeContext';
import { useHideTheoreticalForms } from '@/contexts/HideTheoreticalFormsContext';
import { apiSearch } from '@/lib/api';
import { useAdminConfig } from '@/lib/adminConfig';
import { getAttestedEntries } from '@/lib/conjugationEngine';
import { buildVerbPreviewFromEngine } from '@/lib/verbMorphology';
import { getSearchCardLocation } from '@/lib/searchCard';
import { buildStemSearchPreview, type StemSearchPreviewKind } from '@/lib/stemSearchPreview';
import { SubParts } from '@/components/dictionary/SubParts';
import { resolveEntryGender } from '@/lib/gender';
import { getGloss, parseMaybeArray } from '@/lib/utils';
import { normalizePluralFormRows } from '@/lib/pluralForms';
import { isAutoGeneratedSurface, isTheoreticalSurface, normalizeSurfaceText, shouldHideSurface, stripTheoreticalPrefix } from '@/lib/theoreticalForms';

// ── Colours ────────────────────────────────────────────────────────────────
const EGYPTIAN_BLUE = '#1034A6';

// ── Types ──────────────────────────────────────────────────────────────────
interface InflectionRow {
    label: string;
    form: string;
    hasPage: boolean;
    entryId?: string;
    marker?: 'plain' | 'theoretical' | 'auto_generated'; // these + labels appear at black/55
    secondary?: {
        form: string;
        hasPage: boolean;
        entryId?: string;
        marker?: 'plain' | 'theoretical' | 'auto_generated';
    };
}

interface SearchResult {
    id: string;
    headword: string;
    root: string;
    rootSlug: string;
    rootHref: string;
    gender?: string;    // shown as Egyptian Blue below root
    pos: string;
    definitions: string[];
    inflections: InflectionRow[];
    entry: any;
}

type SearchSuggestion = Pick<SearchResult, 'id' | 'headword' | 'pos' | 'definitions'>;

// ── Filter state ───────────────────────────────────────────────────────────
interface Filters {
    maxResults: string;
    pos: string;
    rootType: string;
    source: string;
    searchLemma: boolean;
    searchWordForms: boolean;
    searchEnglishGloss: boolean;
    includeSuggested: boolean;
    includePending: boolean;
}

const DEFAULT_FILTERS: Filters = {
    maxResults: '25',
    pos: '',
    rootType: '',
    source: '',
    searchLemma: false,
    searchWordForms: false,
    searchEnglishGloss: false,
    includeSuggested: false,
    includePending: true,
};

function readMultiValueParams(searchParams: URLSearchParams, key: string): string[] {
    return [...new Set(
        searchParams
            .getAll(key)
            .flatMap((value) => String(value).split(','))
            .map((value) => value.trim())
            .filter(Boolean),
    )];
}

// ── Sub-components ─────────────────────────────────────────────────────────
function FilterSelect({
    label, value, onChange, options,
}: {
    label: string;
    value: string;
    onChange: (v: string) => void;
    options: { value: string; label: string }[];
}) {
    const [open, setOpen] = useState(false);
    const ref = useRef<HTMLDivElement>(null);
    const selectedLabel = options.find(o => o.value === value)?.label ?? options[0]?.label;

    // Close on outside click
    useEffect(() => {
        const handler = (e: MouseEvent) => {
            if (ref.current && !ref.current.contains(e.target as Node)) {
                setOpen(false);
            }
        };
        document.addEventListener('mousedown', handler);
        return () => document.removeEventListener('mousedown', handler);
    }, []);

    return (
        <div>
            <p className="text-xs font-medium text-black mb-1.5">{label}</p>
            <div ref={ref} className="relative">
                {/* Trigger */}
                <button
                    type="button"
                    onClick={() => setOpen(o => !o)}
                    className="w-full flex items-center justify-between bg-white border border-black/10 rounded-md px-3 py-2 text-sm text-black focus:outline-none focus:ring-1 focus:ring-black/20 cursor-pointer text-left"
                >
                    <span>{selectedLabel}</span>
                    <span
                        className="text-[#999] text-xs transition-transform duration-200 ml-2 shrink-0"
                        style={{ display: 'inline-block', transform: open ? 'rotate(180deg)' : 'rotate(0deg)' }}
                    >
                        ▲
                    </span>
                </button>

                {/* Options list */}
                {open && (
                    <ul className="absolute z-50 w-full mt-1 bg-white border border-black/10 rounded-md shadow-md overflow-hidden text-sm">
                        {options.map(o => (
                            <li
                                key={o.value}
                                onClick={() => { onChange(o.value); setOpen(false); }}
                                className={cn(
                                    'px-3 py-2 cursor-pointer hover:bg-black/5 transition-colors',
                                    o.value === value ? 'font-medium text-black' : 'text-[#333]',
                                )}
                            >
                                {o.label}
                            </li>
                        ))}
                    </ul>
                )}
            </div>
        </div>
    );
}

function FilterCheckbox({
    label, checked, onChange,
}: {
    label: string; checked: boolean; onChange: (v: boolean) => void;
}) {
    return (
        <label className="flex items-center gap-2.5 cursor-pointer select-none">
            <div
                className={cn(
                    'w-4 h-4 border rounded-sm flex items-center justify-center shrink-0 transition-colors',
                    checked ? 'bg-black border-black' : 'bg-white border-black/25',
                )}
                onClick={() => onChange(!checked)}
            >
                {checked && (
                    <svg width="10" height="8" viewBox="0 0 10 8" fill="none">
                        <path d="M1 4l3 3 5-6" stroke="white" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
                    </svg>
                )}
            </div>
            <span className="text-sm text-black">{label}</span>
        </label>
    );
}

function InflectionCell({ row }: { row: InflectionRow }) {
    const { hideTheoreticalForms } = useHideTheoreticalForms();

    const normalizeSurface = (
        surface: Pick<InflectionRow, 'form' | 'hasPage' | 'entryId' | 'marker'>,
        compact = false,
    ) => {
        const isTheoretical = isTheoreticalSurface(surface) || surface.marker === 'theoretical';
        const isAutoGenerated = surface.marker === 'auto_generated';
        if (shouldHideSurface(surface, hideTheoreticalForms)) return null;

        const form = typeof surface.form === 'string'
            ? stripTheoreticalPrefix(surface.form)
            : surface.form;

        const markerEl = !hideTheoreticalForms && isTheoretical ? (
            <span className="text-black/45">*</span>
        ) : !hideTheoreticalForms && isAutoGenerated ? (
            <span className="text-black/45">✦</span>
        ) : null;

        const textClass = cn(
            compact ? 'text-[11px] leading-tight' : 'text-sm',
            'font-serif',
            (isTheoretical || isAutoGenerated || surface.marker) ? 'text-black/55' : 'text-black',
        );

        const content = (
            <span className={textClass}>
                {markerEl}{form}
            </span>
        );

        if (surface.hasPage || surface.entryId) {
            return (
                <Link
                    to={`/entry/${surface.entryId || surface.form}`}
                    style={{ color: isTheoretical ? undefined : EGYPTIAN_BLUE }}
                    className={cn(
                        compact ? 'text-[11px] leading-tight' : 'text-sm',
                        'hover:underline',
                        isTheoretical ? 'text-black/55' : '',
                    )}
                >
                    {markerEl}{form}
                </Link>
            );
        }

        return content;
    };

    const primary = normalizeSurface(row);
    const secondary = row.secondary ? normalizeSurface(row.secondary, true) : null;
    if (!primary && !secondary) return null;

    return (
        <div className="flex flex-col gap-0.5">
            {primary || secondary}
            {primary && secondary && (
                <div className="pl-0.5">
                    {secondary}
                </div>
            )}
        </div>
    );
}

function getStemPreviewLabel(kind: StemSearchPreviewKind, term: (key: string) => string) {
    switch (kind) {
        case 'imperfect':
            return term('imperfect');
        case 'imperative':
            return term('imperative');
        case 'passive':
            return term('passive');
        case 'verbal-noun':
            return term('verbal-noun');
        default:
            return kind;
    }
}

function getSearchPreviewText(result: Pick<SearchSuggestion, 'definitions'>) {
    return result.definitions[0] || '';
}


function EntryCard({ result, index }: { result: SearchResult; index: number }) {
    const { language } = useLanguage();
    const { term, mode } = useLinguisticMode();
    const { hideTheoreticalForms } = useHideTheoreticalForms();
    const alternativeForms = parseMaybeArray<any>(result.entry.alternative_forms);
    const headword = hideTheoreticalForms ? stripTheoreticalPrefix(result.headword) : result.headword;
    const visibleInflections = result.inflections.filter(row => {
        const primaryHidden = shouldHideSurface(row, hideTheoreticalForms);
        const secondaryHidden = row.secondary ? shouldHideSurface(row.secondary, hideTheoreticalForms) : true;
        return !(primaryHidden && secondaryHidden);
    });
    const displayAlternativeForms = hideTheoreticalForms
        ? alternativeForms
            .filter((alt: any) => !shouldHideSurface(alt, hideTheoreticalForms))
            .map((alt: any) => ({ ...alt, headword: stripTheoreticalPrefix(alt.headword || '') }))
        : alternativeForms;
    return (
        <div className="bg-white rounded-xl border border-black/8 shadow-sm overflow-hidden mb-3 w-full">
            <div className="flex flex-col md:grid md:grid-cols-[12rem_8rem_1fr_16rem] min-h-20">

                {/* Col 1: Index number | headword + root */}
                <div className="px-5 py-4 flex items-start gap-2 border-b md:border-b-0 md:border-r border-black/5">
                    <span className="text-xs text-black/30 font-sans w-5 shrink-0 pt-1">{index}.</span>
                    <div>
                        <Link to={`/entry/${result.id}`}
                            className="font-serif font-extrabold text-[1.35rem] leading-tight text-black hover:underline block">
                            {headword}
                        </Link>
                        <div className="flex flex-wrap items-center gap-x-2 mt-0.5">
                            <Link to={result.rootHref}
                                style={{ color: EGYPTIAN_BLUE }}
                                className="text-xs hover:underline font-sans">
                                {result.root}
                            </Link>
                            {result.gender && (
                                <Link to={`/search?gender=${result.gender}`}
                                    style={{ color: EGYPTIAN_BLUE }}
                                    className="text-xs hover:underline font-sans">
                                    {term(result.gender)}
                                </Link>
                            )}
                        </div>
                    </div>
                </div>

                {/* Col 2: POS block */}
                <div className="px-5 py-3 md:py-4 flex flex-row md:flex-col flex-wrap gap-2 md:gap-0.5 border-b md:border-b-0 md:border-r border-black/5 bg-black/1 md:bg-transparent">
                    <SubParts entry={result.entry} layout="lines" showTransitivity />
                </div>

                {/* Col 3: Definitions */}
                <div className="px-5 py-4 border-b md:border-b-0 md:border-r border-black/5">
                    {result.definitions.length === 1 ? (
                        <p className="text-sm text-black leading-relaxed">{result.definitions[0]}</p>
                    ) : (
                        <ol className="space-y-1 md:space-y-0.5 list-none">
                            {result.definitions.map((def, i) => (
                                <li key={i} className="text-sm text-black">
                                    <span className="text-black/30 mr-1.5 font-sans text-xs">{i + 1}.</span> {def}
                                </li>
                            ))}
                        </ol>
                    )}

                    {displayAlternativeForms.length > 0 && (
                        <div className="mt-3 pt-3 border-t border-black/5 space-y-1">
                            <div className="text-[10px] font-bold text-black/30 uppercase tracking-wider">
                                {term('alternative-forms')}
                            </div>
                            <div className="space-y-1">
                                {displayAlternativeForms.map((alt: any) => (
                                    <div key={alt.id || alt.headword} className="flex items-baseline gap-2">
                                        <Link to={`/entry/${alt.id || alt.headword}`} className="font-serif text-sm font-semibold text-[#1034A6] hover:underline">
                                            {alt.headword}
                                        </Link>
                                        <span className="text-xs text-black/50 italic">
                                            "{getGloss(alt, language, mode)}"
                                        </span>
                                    </div>
                                ))}
                            </div>
                        </div>
                    )}
                </div>

                {/* Col 4: Inflections */}
                <div className="px-5 py-4 space-y-2 md:space-y-1 bg-black/1 md:bg-transparent">
                    {visibleInflections.map((row, i) => (
                        <div key={i} className="flex items-baseline gap-3">
                            <span className="text-[10px] md:text-xs text-black/40 md:text-black/55 font-sans w-24 shrink-0 leading-snug uppercase tracking-tight md:tracking-normal">
                                {row.label}
                            </span>
                            <InflectionCell row={row} />
                        </div>
                    ))}
                </div>

            </div>

        </div>
    );
}

// ── Main page ──────────────────────────────────────────────────────────────
export function Search() {
    const { language } = useLanguage();
    const { term, mode } = useLinguisticMode();
    const { getOptions } = useAdminConfig();
    const [searchParams, setSearchParams] = useSearchParams();
    const navigate = useNavigate();
    const [results, setResults] = useState<SearchResult[]>([]);
    const [loading, setLoading] = useState(false);
    const [showFiltersMobile, setShowFiltersMobile] = useState(false);
    const [total, setTotal] = useState(0);
    const [suggestions, setSuggestions] = useState<SearchSuggestion[]>([]);
    const [suggestionsLoading, setSuggestionsLoading] = useState(false);
    const [query, setQuery] = useState(searchParams.get('q') ?? '');
    const [searchFocused, setSearchFocused] = useState(false);

    const POS_FILTER_OPTIONS = useMemo(() => [
        { value: '', label: term('all') },
        ...getOptions('pos', mode, language)
    ], [getOptions, mode, language, term]);

    const ROOT_TYPE_FILTER_OPTIONS = useMemo(() => [
        { value: '', label: term('all') },
        ...getOptions('verb_class', mode, language)
    ], [getOptions, mode, language, term]);

    const isSearchPerformed = searchParams.has('q') || searchParams.has('pos') || searchParams.has('type') || searchParams.has('noun_type') || searchParams.has('source') || searchParams.has('source_language') || searchParams.has('suffix') || searchParams.has('gender') || searchParams.has('form');
    const submitted = searchParams.get('q') ?? '';
    const suggestionQuery = query.trim();

    // Effect to fetch from API
    useEffect(() => {
        let cancelled = false;
        const controller = new AbortController();

        const load = async () => {
            setLoading(true);

            const q = searchParams.get('q') ?? '';
            const pos = searchParams.get('pos') || undefined;
            const type = searchParams.get('type') || undefined;
            const nounType = searchParams.get('noun_type') || undefined;
            const source = searchParams.get('source') || undefined;
            const sourceLanguage = searchParams.get('source_language') || undefined;
            const suffix = searchParams.get('suffix') || undefined;
            const suffixKind = searchParams.get('suffix_kind') || undefined;
            const gender = searchParams.get('gender') || undefined;
            const v = searchParams.get('v') || undefined;
            const forms = readMultiValueParams(searchParams, 'form');
            const pending = searchParams.get('pending') === 'true' || searchParams.get('pending') === null; // default to true if not present to match DEFAULT_FILTERS
            const suggested = searchParams.get('suggested') === 'true';
            const limit = Number(searchParams.get('limit') ?? DEFAULT_FILTERS.maxResults);
            const offset = Number(searchParams.get('offset') ?? 0);
            const random = searchParams.get('random') || undefined;

            try {
                const res = await apiSearch(q, {
                    pos,
                    type,
                    noun_type: nounType,
                    source,
                    source_language: sourceLanguage,
                    suffix,
                    suffix_kind: suffixKind as 'nominal' | 'derivational' | undefined,
                    gender,
                    limit,
                    offset,
                    random,
                    v,
                    forms: forms.length > 0 ? forms : undefined,
                    includePending: pending,
                    includeSuggested: suggested,
                    signal: controller.signal,
                });

                if (cancelled || controller.signal.aborted) return;

                setTotal(res.total);

                const stemEntriesMap = new Map<string, any[]>();
                res.results.forEach((r: any) => {
                    const s = r?.zokk_morphology?.stem_string?.trim();
                    if (s) {
                        const existing = stemEntriesMap.get(s) || [];
                        existing.push(r);
                        stemEntriesMap.set(s, existing);
                    }
                });

                const mapped: SearchResult[] = res.results.map((r: any) => {
                    const inflections: InflectionRow[] = [];
                    const vm = r.verb_morphology;
                    let generated: any = null;

                    if (r.zokk_morphology?.stem_string) {
                        const previewRows = buildStemSearchPreview(
                            r,
                            stemEntriesMap.get(r.zokk_morphology.stem_string) || [r],
                        );

                        previewRows.forEach((previewRow) => {
                            inflections.push({
                                label: getStemPreviewLabel(previewRow.kind, term),
                                form: previewRow.value,
                                hasPage: previewRow.hasPage,
                                entryId: previewRow.entryId,
                                marker: previewRow.marker,
                                secondary: previewRow.secondary ? {
                                    form: previewRow.secondary.value,
                                    hasPage: previewRow.secondary.hasPage,
                                    entryId: previewRow.secondary.entryId,
                                    marker: previewRow.secondary.marker,
                                } : undefined,
                            });
                        });
                    } else if (vm) {
                        try {
                            const preview = buildVerbPreviewFromEngine(
                                r,
                                r.root_pattern_form?.root?.entries || [r],
                            );
                            generated = preview.rootForm || {
                                imperfect: preview.marked.imperfect,
                                imperative: preview.marked.imperative,
                                passiveParticiple: preview.marked.passiveParticiple,
                                verbalNoun: preview.marked.verbalNoun,
                            };
                        } catch (e) {
                            console.warn('Search conjugation error:', e);
                        }

                        const pushMarked = (label: string, data: any) => {
                            if (!data || data.value === '-') return;
                            inflections.push({
                                label,
                                form: data.value,
                                hasPage: !!data.entryId,
                                entryId: data.entryId,
                                marker: data.marker,
                            });
                        };

                        pushMarked(term('imperfect'), generated?.imperfect);
                        pushMarked(term('imperative'), generated?.imperative);
                        pushMarked(term('passive'), generated?.passiveParticiple);

                        pushMarked(term('verbal-noun'), generated?.verbalNoun);
                    } else {
                        const genderValue = resolveEntryGender(r);
                        const rootEntries = r.root_pattern_form?.root?.entries || [r];
                        const attested = getAttestedEntries(rootEntries);

                        const pushMarkedSimple = (label: string, form: any, type: string) => {
                            if (!form || form === '-') return;
                            const text = normalizeSurfaceText(form);
                            if (!text || text === '-') return;

                            const clean = stripTheoreticalPrefix(text);
                            const isTheoretical = isTheoreticalSurface(form);
                            const isAutoGenerated = isAutoGeneratedSurface(form);
                            const existing = attested.find(a => a.word === clean.trim() && a.type === type);
                            inflections.push({
                                label,
                                form: clean.trim(),
                                hasPage: !!existing,
                                entryId: existing?.id,
                                marker: existing ? undefined : (isTheoretical ? 'theoretical' : (isAutoGenerated ? 'auto_generated' : undefined))
                            });
                        };

                        // 1. Add opposite gender if applicable
                        const fem = r.form_fem || r.adjective_morphology?.feminine;
                        const masc = r.form_masc || r.adjective_morphology?.masculine;
                        if (genderValue === 'masculine' && fem) {
                            pushMarkedSimple(term('feminine'), fem, r.pos === 'adjective' ? 'adjective' : 'noun');
                        } else if (genderValue === 'feminine' && masc) {
                            pushMarkedSimple(term('masculine'), masc, r.pos === 'adjective' ? 'adjective' : 'noun');
                        }

                        // 2. Add plural
                        const rawPluralForms = r.noun_morphology?.plural_forms || r.inflections_pl || r.adjective_morphology?.plural;
                        const pluralRows = rawPluralForms ? normalizePluralFormRows(rawPluralForms) : [];
                        if (pluralRows.length > 0 && pluralRows[0].form) {
                            pushMarkedSimple(term('plural'), pluralRows[0].form, r.pos === 'adjective' ? 'adjective' : 'noun');
                        }

                        // 3. Adjective specific: Elative
                        if (r.pos === 'adjective' || r.adjective_morphology) {
                            const am = r.adjective_morphology;
                            const elative = am?.elative;
                            if (elative) pushMarkedSimple(term('elative') || 'Elative', elative, 'adjective');

                            const dim = r.diminutive_form || am?.diminutive;
                            if (dim) pushMarkedSimple(term('diminutive'), dim, 'adjective');
                        }

                        // 4. Numeral specific: Ordinal, Adverbial, Distributive
                        if (r.pos === 'numeral' || r.numeral_morphology) {
                            const nm = r.numeral_morphology;
                            if (nm?.ordinal) pushMarkedSimple(term('ordinal') || 'Ordinal', nm.ordinal, 'adjective');
                            if (nm?.adverbial) pushMarkedSimple(term('adverbial') || 'Adverbial', nm.adverbial, 'adverb');
                            if (nm?.distributive) pushMarkedSimple(term('distributive') || 'Distributive', nm.distributive, 'numeral');
                        }

                        // 5. Collective/Singulative
                        const nm = r.noun_morphology;
                        if (nm) {
                            if (nm.collective_form) pushMarkedSimple(r.is_singulative ? term('collective') : (term('unit-form') || 'Unit Form'), nm.collective_form, 'noun');
                            if (nm.singulative_form) pushMarkedSimple(r.is_collective ? term('singulative') : (term('individual-form') || 'Individual Form'), nm.singulative_form, 'noun');
                        }
                    }

                    return {
                        id: r.id,
                        headword: r.headword,
                        ...getSearchCardLocation(r, r.root_pattern_form?.root?.consonants || ''),
                        gender: resolveEntryGender(r) || undefined,
                        pos: r.pos,
                        definitions: r.definition_en ? [r.definition_en] : (r.definitions?.length ? r.definitions.map((d: any) => d.text_en) : []),
                        inflections,
                        entry: r,
                    };
                });

                if (cancelled) return;

                if (offset === 0) {
                    setResults(mapped);
                } else {
                    setResults(prev => [...prev, ...mapped]);
                }
            } catch (err) {
                if (cancelled) return;
                console.error('Search fetch error:', err);
                setResults([]);
            } finally {
                if (!cancelled) setLoading(false);
            }
        };

        load();

        return () => {
            cancelled = true;
            controller.abort();
        };
    }, [searchParams.toString(), isSearchPerformed, term]);

    // Filter and map results (Now handled by API effect, this useMemo is mostly for query state tracking)
    const [filters, setFilters] = useState<Filters>(() => {
        const f = { ...DEFAULT_FILTERS };
        if (searchParams.has('pos')) f.pos = searchParams.get('pos')!;
        if (searchParams.has('type')) f.rootType = searchParams.get('type')!;
        if (searchParams.has('source')) f.source = searchParams.get('source')!;
        if (searchParams.has('limit')) f.maxResults = searchParams.get('limit')!;
        return f;
    });

    useEffect(() => {
        const q = searchParams.get('q') ?? '';
        setQuery(q);
    }, [searchParams]);

    useEffect(() => {
        if (query) {
            document.title = `${term('search')}: ${query} | Il-Miġma'`;
        } else {
            document.title = `${term('search')} | Il-Miġma'`;
        }
    }, [query, term]);

    const submitSearch = (nextQuery: string) => {
        const params: Record<string, string> = { q: nextQuery.trim() };
        if (filters.pos) params.pos = filters.pos;
        if (filters.rootType) params.type = filters.rootType;
        if (filters.source) params.source = filters.source;
        const sourceLanguage = searchParams.get('source_language') || '';
        if (sourceLanguage) params.source_language = sourceLanguage;
        const suffix = searchParams.get('suffix') || '';
        if (suffix) params.suffix = suffix;
        const suffixKind = searchParams.get('suffix_kind') || '';
        if (suffixKind) params.suffix_kind = suffixKind;
        if (filters.maxResults && filters.maxResults !== DEFAULT_FILTERS.maxResults) params.limit = filters.maxResults;
        setSearchParams(params);
        setShowFiltersMobile(false);
    };

    const handleSearch = (e?: React.FormEvent) => {
        e?.preventDefault();
        submitSearch(query);
    };

    useEffect(() => {
        let cancelled = false;
        const controller = new AbortController();
        const trimmed = query.trim();

        if (trimmed.length < 2) {
            setSuggestions([]);
            setSuggestionsLoading(false);
            return;
        }

        setSuggestionsLoading(true);
        const timer = setTimeout(async () => {
            try {
                const pos = searchParams.get('pos') || undefined;
                const type = searchParams.get('type') || undefined;
                const nounType = searchParams.get('noun_type') || undefined;
                const source = searchParams.get('source') || undefined;
                const sourceLanguage = searchParams.get('source_language') || undefined;
                const suffix = searchParams.get('suffix') || undefined;
                const suffixKind = searchParams.get('suffix_kind') || undefined;
                const gender = searchParams.get('gender') || undefined;
                const v = searchParams.get('v') || undefined;
                const forms = readMultiValueParams(searchParams, 'form');
                const pending = searchParams.get('pending') === 'true' || searchParams.get('pending') === null;
                const suggested = searchParams.get('suggested') === 'true';

                const res = await apiSearch(trimmed, {
                    pos,
                    type,
                    noun_type: nounType,
                    source,
                    source_language: sourceLanguage,
                    suffix,
                    suffix_kind: suffixKind as 'nominal' | 'derivational' | undefined,
                    gender,
                    limit: 3,
                    offset: 0,
                    v,
                    forms: forms.length > 0 ? forms : undefined,
                    includePending: pending,
                    includeSuggested: suggested,
                    signal: controller.signal,
                });

                if (!cancelled && !controller.signal.aborted) {
                    setSuggestions(
                        res.results.slice(0, 3).map((r: any) => ({
                            id: r.id,
                            headword: r.headword,
                            pos: r.pos,
                            definitions: r.definition_en
                                ? [r.definition_en]
                                : (r.definitions?.length ? r.definitions.map((d: any) => d.text_en) : []),
                        })),
                    );
                }
            } catch (error) {
                if (!cancelled && !controller.signal.aborted) {
                    console.warn('Search suggestions fetch failed:', error);
                    setSuggestions([]);
                }
            } finally {
                if (!cancelled && !controller.signal.aborted) setSuggestionsLoading(false);
            }
        }, 250);

        return () => {
            cancelled = true;
            clearTimeout(timer);
            controller.abort();
        };
    }, [query, searchParams.toString()]);

    // Global Enter key listener
    useEffect(() => {
        const handler = (e: KeyboardEvent) => {
            if (e.key === 'Enter') {
                if (document.activeElement?.tagName !== 'BUTTON' && document.activeElement?.tagName !== 'A') {
                    handleSearch();
                }
            }
        };
        window.addEventListener('keydown', handler);
        return () => window.removeEventListener('keydown', handler);
    }, [query, filters]);

    const bgStyle = {
        background: `linear-gradient(rgba(244,243,240,0.88), rgba(244,243,240,0.88)),
                 url("/bg-pattern.webp") center/cover no-repeat`,
        minHeight: '100vh',
    };

    const [kbOpen, setKbOpen] = useState(false);
    const inputRef = useRef<HTMLInputElement>(null);
    const kbRef = useRef<HTMLButtonElement>(null);

    const insertChar = (char: string) => {
        const input = inputRef.current;
        if (!input) { setQuery(q => q + char); return; }
        const start = input.selectionStart ?? query.length;
        const end = input.selectionEnd ?? query.length;
        const next = query.slice(0, start) + char + query.slice(end);
        setQuery(next);
        requestAnimationFrame(() => {
            input.focus();
            input.setSelectionRange(start + char.length, start + char.length);
        });
    };

    const setFilter = <K extends keyof Filters>(key: K, value: Filters[K]) => {
        setFilters(f => {
            const next = { ...f, [key]: value };
            if (key === 'maxResults') {
                // Changing max results should trigger a fresh search
                const params = Object.fromEntries(searchParams.entries());
                params.limit = value as string;
                delete params.offset; // Reset offset
                setSearchParams(params);
            }
            return next;
        });
    }

    const handleRandom = () => {
        setSearchParams({ random: 'true' });
    };

    const handleLoadMore = () => {
        const params = new URLSearchParams(searchParams);
        const currentOffset = Number(params.get('offset') ?? 0);
        const currentLimit = Number(params.get('limit') ?? filters.maxResults);
        const nextOffset = currentOffset + currentLimit;
        params.set('offset', String(nextOffset));
        if (!params.has('limit')) params.set('limit', filters.maxResults);
        navigate(`?${params.toString()}`, { replace: true, preventScrollReset: true });
    };

    return (
        <div style={bgStyle}>
            <div className="max-w-6xl mx-auto px-7 sm:px-8 py-8">

                {/* ── Page heading ── */}
                <div className="mb-6">
                    {submitted ? (
                        <>
                            <h1 className="font-serif font-medium text-4xl leading-tight text-black">
                                {term('results-for', { q: submitted })}
                            </h1>
                            <p className="text-black/40 text-sm font-sans mt-1">
                                {term('entries-shown', { count: results.length.toString(), total: total.toString() })}
                            </p>
                        </>
                    ) : (
                        <>
                            <h1 className="font-serif font-medium text-4xl leading-tight text-black">
                                {term('search-results')}
                            </h1>
                            <p className="text-black/40 text-sm font-sans mt-2">
                                {results.length > 0 && !submitted && !searchParams.has('pos') && !searchParams.has('type')
                                    ? term('random-entries-desc')
                                    : term('search-desc')}
                            </p>
                        </>
                    )}
                </div>

                {/* ── Inline search bar ── */}
                <form onSubmit={handleSearch} className="w-full md:max-w-2xl mb-8 relative">
                    <div className="flex items-center bg-white border border-black/10 rounded-lg overflow-hidden shadow-sm">
                        {/* Keyboard toggle */}
                        <button
                            ref={kbRef}
                            type="button"
                            onClick={() => setKbOpen(o => !o)}
                            className={cn(
                                'flex items-center gap-1 px-3 border-r border-black/10 shrink-0 py-2.5 transition-colors',
                                kbOpen ? 'text-black bg-black/5' : 'text-[#555] hover:text-black',
                            )}
                            aria-label={term('toggle-picker')}
                        >
                            <Keyboard size={14} />
                            <span className="text-xs text-[#aaa]">›</span>
                        </button>
                        <input
                            ref={inputRef}
                            type="text"
                            value={query}
                            onChange={e => setQuery(e.target.value)}
                            onFocus={() => setSearchFocused(true)}
                            onBlur={() => setSearchFocused(false)}
                            placeholder={term('search') + '…'}
                            className="flex-1 px-3 py-2.5 text-sm bg-transparent focus:outline-none font-sans text-black"
                        />
                        <button type="submit"
                            className="px-3 py-2.5 text-[#555] hover:text-black transition-colors shrink-0"
                            aria-label={term('search')}>
                            <SearchIcon size={16} />
                        </button>
                    </div>
                    {searchFocused && suggestionQuery.length >= 2 && (suggestionsLoading || suggestions.length > 0) && (
                        <div className="absolute left-0 right-0 top-full mt-2 z-40 rounded-xl border border-black/10 bg-white shadow-lg overflow-hidden">
                            {suggestionsLoading && suggestions.length === 0 && (
                                <div className="flex items-center gap-2 px-4 py-4 text-sm text-black/55">
                                    <Loader2 size={14} className="animate-spin" />
                                    Searching...
                                </div>
                            )}
                            <div className="px-2 pb-2">
                                {suggestions.map((suggestion) => (
                                    <button
                                        key={suggestion.id}
                                        type="button"
                                        onMouseDown={(e) => e.preventDefault()}
                                        onClick={() => {
                                            setQuery(suggestion.headword);
                                            submitSearch(suggestion.headword);
                                        }}
                                        className="w-full text-left rounded-lg px-3 py-2.5 hover:bg-black/5 transition-colors flex items-start justify-between gap-4"
                                    >
                                        <div className="min-w-0">
                                            <div className="font-serif text-sm text-black leading-tight truncate">
                                                {suggestion.headword}
                                            </div>
                                            {getSearchPreviewText(suggestion) && (
                                                <div className="text-xs text-black/55 mt-0.5 truncate">
                                                    {getSearchPreviewText(suggestion)}
                                                </div>
                                            )}
                                        </div>
                                        <div className="shrink-0 text-[11px] uppercase tracking-wide text-black/35 pt-0.5">
                                            {suggestion.pos}
                                        </div>
                                    </button>
                                ))}
                            </div>
                        </div>
                    )}
                    <MalteseCharPicker
                        open={kbOpen}
                        onOpenChange={setKbOpen}
                        onInsert={insertChar}
                        triggerRef={kbRef}
                    />
                </form>

                {/* ── Two-column layout ── */}
                <div className="flex flex-col md:flex-row gap-8 md:items-start w-full">

                    {/* Filter Sidebar Container (Unified on Mobile) */}
                    <div className="w-full md:w-64 shrink-0 flex flex-col md:sticky md:top-20">
                        {/* Mobile Filter Toggle */}
                        <div className="md:hidden w-full">
                            <button
                                onClick={() => setShowFiltersMobile(!showFiltersMobile)}
                                className={cn(
                                    "w-full flex items-center justify-between bg-white border border-black/10 px-5 py-4 shadow-sm transition-all",
                                    showFiltersMobile ? "rounded-t-xl border-b-0" : "rounded-xl"
                                )}
                            >
                                <div className="flex items-center gap-2">
                                    <Filter size={18} className="text-[#1034A6]" />
                                    <span className="font-sans font-semibold text-sm text-black">
                                        {term('filter-options')}
                                    </span>
                                </div>
                                {showFiltersMobile ? <ChevronUp size={18} className="text-black/30" /> : <ChevronDown size={18} className="text-black/30" />}
                            </button>
                        </div>

                        {/* ── Filter sidebar ── */}
                        <aside className={cn(
                            "w-full bg-white border border-black/10 md:border-black/8 shadow-sm p-5 space-y-4 transition-all duration-300 overflow-hidden",
                            "md:rounded-xl md:block",
                            showFiltersMobile ? "rounded-b-xl block" : "hidden"
                        )}>
                            <h2 className="hidden md:block font-sans font-semibold text-sm text-black">{term('filters')}</h2>

                            <FilterSelect
                                label={term("max-results")}
                                value={filters.maxResults}
                                onChange={v => setFilter('maxResults', v)}
                                options={[
                                    { value: '10', label: '10' },
                                    { value: '25', label: '25' },
                                    { value: '50', label: '50' },
                                    { value: '100', label: '100' },
                                ]}
                            />

                            <FilterSelect
                                label={term("part-of-speech")}
                                value={filters.pos}
                                onChange={v => setFilter('pos', v)}
                                options={POS_FILTER_OPTIONS}
                            />

                            <FilterSelect
                                label={term("root") + " (" + term("form") + ")"}
                                value={filters.rootType}
                                onChange={v => setFilter('rootType', v)}
                                options={ROOT_TYPE_FILTER_OPTIONS}
                            />

                            <FilterSelect
                                label={term("source")}
                                value={filters.source}
                                onChange={v => setFilter('source', v)}
                                options={[
                                    { value: '', label: term('all') },
                                    { value: 'spagnol2011', label: 'Spagnol (2011)' },
                                    { value: 'mayer2013', label: 'Mayer (2013)' },
                                    { value: 'borg1997', label: 'Borg & Azzopardi-Alexander (1997)' },
                                    { value: 'maltese-academy', label: term('maltese-academy') },
                                ]}
                            />

                            <div className="border-t border-black/8 pt-4 space-y-2.5">
                                <FilterCheckbox label={term('search-lemma')}
                                    checked={filters.searchLemma} onChange={v => setFilters(f => ({ ...f, searchLemma: v }))} />
                                <FilterCheckbox label={term('search-word-forms')}
                                    checked={filters.searchWordForms} onChange={v => setFilters(f => ({ ...f, searchWordForms: v }))} />
                                <FilterCheckbox label={term('search-english-gloss')}
                                    checked={filters.searchEnglishGloss} onChange={v => setFilters(f => ({ ...f, searchEnglishGloss: v }))} />
                                <FilterCheckbox label={term('include-suggested')}
                                    checked={filters.includeSuggested} onChange={v => setFilters(f => ({ ...f, includeSuggested: v }))} />
                                <FilterCheckbox label={term('include-pending')}
                                    checked={filters.includePending}
                                    onChange={v => setFilter('includePending', v)} />
                            </div>
                        </aside>
                    </div>

                    {/* Results list */}
                    <div className="flex-1 space-y-3 min-w-0 w-full">
                        {results.length === 0 && !loading && isSearchPerformed && (
                            <div className="bg-white/50 rounded-xl border border-white/40 shadow-sm p-10 text-left">
                                <p className="text-sm text-black mb-2">
                                    {submitted ? term('no-results-found', { q: submitted }) : term('no-results-found-empty')}
                                </p>
                                <p className="text-xs text-black/40 mt-1 mb-4">
                                    {term('include-suggested-desc')}
                                </p>
                                <p className="text-black/40 text-sm mb-6 max-w-md">
                                    {term('no-results-desc')}
                                </p>
                                <div className="flex items-center justify-end gap-3">
                                    <Link to={`/suggest?q=${submitted}`} className="flex items-center gap-2 px-4 py-2 bg-black text-white rounded-lg hover:bg-black/90 transition-colors text-sm font-medium">
                                        <MessageSquare size={16} />
                                        {term('suggest-entry')}
                                    </Link>
                                    <button
                                        onClick={handleRandom}
                                        className="inline-flex items-center gap-2 px-4 py-2 text-sm font-medium text-black bg-surface-soft hover:bg-hover border border-border rounded-full transition-colors"
                                    >
                                        <Shuffle size={16} />
                                        {term('random')}
                                    </button>
                                </div>
                            </div>
                        )}
                        {results.map((r, i) => (
                            <EntryCard key={r.id} result={r} index={i + 1} />
                        ))}

                        {loading && results.length === 0 && (
                            <div className="flex justify-center p-10">
                                <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-[#1034A6]"></div>
                            </div>
                        )}

                        {loading && results.length > 0 && (
                            <div className="flex justify-center p-4">
                                <div className="animate-spin rounded-full h-6 w-6 border-b-2 border-[#1034A6]"></div>
                            </div>
                        )}

                        {!loading && results.length > 0 && results.length < total && (
                            <div className="flex justify-center pt-4">
                                <button
                                    onClick={handleLoadMore}
                                    className="flex items-center gap-2 px-6 py-2.5 bg-white border border-black/10 rounded-full text-sm font-medium text-black hover:bg-black/5 transition-colors shadow-sm"
                                >
                                    <span>{term('show-more')}</span>
                                    <ChevronDown size={16} className="text-black/40" />
                                </button>
                            </div>
                        )}
                    </div>

                </div>
            </div>
        </div>
    );
}
