import { useEffect, useMemo, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { ArrowLeft, BookOpen, Info } from 'lucide-react';
import { Card } from '@/components/ui/Card';
import { useLinguisticMode } from '@/contexts/LinguisticModeContext';
import { apiGetSuffixCatalog, apiSearch, type SuffixCatalogItem } from '@/lib/api';
import { normalizeSuffixDisplay, resolveSuffixEntryMatch } from '@/lib/suffixMatching';
import { isTheoreticalSurface, isAutoGeneratedSurface } from '@/lib/theoreticalForms';
import type { SearchResult } from '@/types';

const CREAM_RGBA = 'rgba(244,243,240,0.88)';

function EntryCard({
    entry,
    term,
    suffix,
    kind,
}: {
    entry: SearchResult;
    term: (k: string) => string;
    suffix: string;
    kind: 'nominal' | 'derivational';
}) {
    const match = entry.suffix_match || resolveSuffixEntryMatch(entry as any, suffix, kind);
    if (!match) return null;
    const normalizedDisplayValue = match.displayValue?.trim() || '';
    const cardTitle = normalizedDisplayValue.startsWith('-') ? entry.headword : normalizedDisplayValue;

    return (
        <Link 
            to={`/entry/${entry.id}`}
            className="group block bg-white/40 hover:bg-white/80 backdrop-blur-sm border border-black/5 hover:border-link/30 p-6 rounded-2xl transition-all duration-300 hover:shadow-lg hover:shadow-link/10 hover:-translate-y-1"
        >
            <div className="mb-4">
                <div className="flex justify-between items-start mb-1">
                    <h3 className="font-serif text-2xl font-bold text-black group-hover:text-link transition-colors leading-tight">
                        {cardTitle || entry.headword}
                    </h3>
                    <span className="text-[10px] font-bold uppercase tracking-widest text-black/30 bg-black/5 px-2 py-0.5 rounded">
                        {entry.pos}
                    </span>
                </div>
                {cardTitle && cardTitle !== entry.headword && (
                    <div className="flex items-center gap-2">
                        <p className="text-xs text-black/40 font-medium italic">
                            Headword: <span className="text-black/60 group-hover:text-link/60 transition-colors">{entry.headword}</span>
                        </p>
                        <span className="text-[9px] font-bold uppercase tracking-tighter text-link/60 bg-link/5 px-1.5 py-px border border-link/10 rounded">
                            {match.role === 'dual'
                                ? (term('dual') || 'Dual')
                                : match.role === 'plural'
                                    ? (term('plural') || 'Plural')
                                    : (term('derivational') || 'Derivational')}
                        </span>
                    </div>
                )}
            </div>

            {entry.definition_en && (
                <p className="text-sm text-text-muted line-clamp-2 italic mb-4 opacity-70">
                    {entry.definition_en}
                </p>
            )}
            <div className="flex items-center gap-2 text-[10px] font-bold text-link opacity-0 group-hover:opacity-100 transition-opacity uppercase tracking-widest">
                {term('view-entry')} <ArrowLeft size={12} className="rotate-180" />
            </div>
        </Link>
    );
}

export function SuffixDetailPage() {
    const { term } = useLinguisticMode();
    const { kind, suffix } = useParams<{ kind: string; suffix: string }>();
    const [catalog, setCatalog] = useState<SuffixCatalogItem[]>([]);
    const [loadingCatalog, setLoadingCatalog] = useState(true);
    const [results, setResults] = useState<SearchResult[]>([]);
    const [loadingResults, setLoadingResults] = useState(true);
    const [total, setTotal] = useState(0);

    const normalizedKind = kind === 'nominal' || kind === 'derivational' ? kind : '';
    const normalizedSuffix = normalizeSuffixDisplay(suffix);

    const selectedItem = useMemo(() => {
        return catalog.find((item) => item.kind === normalizedKind && item.suffix === normalizedSuffix) ?? null;
    }, [catalog, normalizedKind, normalizedSuffix]);

    useEffect(() => {
        document.title = `${normalizedSuffix || term('browse-by-suffix')} | Il-Miġma'`;
    }, [normalizedSuffix, term]);

    useEffect(() => {
        let cancelled = false;

        setLoadingCatalog(true);
        apiGetSuffixCatalog()
            .then((items) => {
                if (!cancelled) setCatalog(items);
            })
            .catch((err) => {
                if (!cancelled) {
                    console.error('Failed to fetch suffix catalog:', err);
                    setCatalog([]);
                }
            })
            .finally(() => {
                if (!cancelled) setLoadingCatalog(false);
            });

        return () => {
            cancelled = true;
        };
    }, []);

    useEffect(() => {
        let cancelled = false;

        if (!selectedItem) {
            setResults([]);
            setTotal(0);
            setLoadingResults(false);
            return () => {
                cancelled = true;
            };
        }

        setLoadingResults(true);
        apiSearch('', {
            suffix: selectedItem.suffix,
            suffix_kind: selectedItem.kind,
            limit: 100,
            includePending: true,
            includeSuggested: false,
            })
            .then((res) => {
                if (cancelled) return;
                const filteredResults = res.results.filter((entry) => {
                    if (isTheoreticalSurface(entry.headword) || isAutoGeneratedSurface(entry.headword)) {
                        return false;
                    }

                    return Boolean(resolveSuffixEntryMatch(entry as any, selectedItem.suffix, selectedItem.kind));
                });
                setResults(filteredResults);
                setTotal(filteredResults.length);
                setLoadingResults(false);
            })
            .catch((err) => {
                if (cancelled) return;
                console.error('Failed to fetch suffix detail results:', err);
                setResults([]);
                setTotal(0);
                setLoadingResults(false);
            });

        return () => {
            cancelled = true;
        };
    }, [selectedItem?.kind, selectedItem?.suffix]);

    const kindLabel = normalizedKind === 'nominal'
        ? term('nominal-suffixes')
        : term('derivational-suffixes');

    const bgStyle = {
        background: `linear-gradient(${CREAM_RGBA}, ${CREAM_RGBA}), url("/bg-pattern.png") center/cover no-repeat`,
        minHeight: '100vh',
    };

    if (loadingCatalog) {
        return (
            <div style={bgStyle} className="flex justify-center items-center h-screen">
                <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-link"></div>
            </div>
        );
    }

    if (!selectedItem) {
        return (
            <div style={bgStyle} className="flex flex-col items-center justify-center h-screen px-4 text-center">
                <h2 className="font-serif text-2xl font-bold text-black mb-2">{term('error')}</h2>
                <p className="text-text-muted mb-6">Suffix not found</p>
                <Link to="/browse/suffix" className="text-link hover:underline flex items-center gap-2">
                    <ArrowLeft size={16} /> {term('back-to-browse')}
                </Link>
            </div>
        );
    }

    return (
        <div style={bgStyle} className="w-full">
            <div className="max-w-6xl mx-auto px-7 sm:px-8 py-10 pb-20">
                
                {/* Back Link */}
                <div className="mb-10">
                    <Link to="/browse/suffix" className="group text-sm text-black/40 hover:text-black flex items-center gap-1 transition-all">
                        <ArrowLeft size={16} className="group-hover:-translate-x-1 transition-transform" /> 
                        {term('back-to-browse')}
                    </Link>
                </div>

                {/* Header Section */}
                <div className="flex flex-col md:flex-row gap-10 items-start mb-16">
                    <div className="flex-1">
                        <div className="flex items-center gap-4 mb-2">
                            <span className="px-3 py-1 bg-link/10 text-link rounded-full text-[10px] font-bold uppercase tracking-widest border border-link/10">
                                {kindLabel}
                            </span>
                        </div>
                        <h1 className="font-serif font-bold text-[3.5rem] leading-none text-black tracking-tight mb-4">
                            {selectedItem.suffix}
                        </h1>
                        <p className="text-xl font-serif text-black/50 italic mb-6">
                            {selectedItem.label}
                        </p>
                        
                        {selectedItem.label && (
                            <div className="bg-white/40 backdrop-blur-sm border border-black/5 rounded-2xl p-6 relative group overflow-hidden">
                                <div className="absolute top-0 left-0 w-1 h-full bg-link/20" />
                                <div className="flex gap-3">
                                    <Info size={18} className="text-link mt-0.5 shrink-0" />
                                    <p className="text-sm text-black/80 leading-relaxed italic">
                                        This suffix is used to form {selectedItem.label.toLowerCase()} in Maltese.
                                    </p>
                                </div>
                            </div>
                        )}
                    </div>

                    {/* Metadata Card */}
                    <Card className="w-full md:w-80 border-black/5 bg-white/60 backdrop-blur-md p-8 rounded-3xl shadow-xl shadow-black/5">
                        <div className="space-y-6">
                            <div>
                                <h2 className="text-[10px] font-bold uppercase tracking-widest text-black/30 mb-3">Linguistic Kind</h2>
                                <div className="flex flex-wrap gap-2">
                                    <span className="px-2.5 py-1 bg-black/5 text-black/70 rounded-lg text-[11px] font-medium border border-black/5">
                                        {kindLabel}
                                    </span>
                                </div>
                            </div>

                            {selectedItem.sample_headword && (
                                <div>
                                    <h2 className="text-[10px] font-bold uppercase tracking-widest text-black/30 mb-2">Example Word</h2>
                                    <p className="font-serif text-lg text-black">{selectedItem.sample_headword}</p>
                                </div>
                            )}

                            <div className="pt-6 border-t border-black/5">
                                <div className="flex items-center justify-between text-xs text-black/40">
                                    <span>Entries Count</span>
                                    <span className="font-mono text-[10px] font-bold bg-black/5 px-2 py-0.5 rounded">{total}</span>
                                </div>
                            </div>
                        </div>
                    </Card>
                </div>

                {/* Entries List Section */}
                <div className="space-y-8">
                    <div className="flex items-center gap-4">
                        <h2 className="font-serif text-2xl font-bold text-black border-l-4 border-link pl-4">
                            {term('entries-using-this-suffix')}
                        </h2>
                        <div className="h-px flex-1 bg-black/5" />
                        <span className="text-xs font-bold text-black/30 uppercase tracking-widest bg-black/5 px-3 py-1 rounded-full">
                            {total} {term('entries')}
                        </span>
                    </div>

                    {loadingResults ? (
                        <div className="flex justify-center py-20">
                            <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-link" />
                        </div>
                    ) : results.length > 0 ? (
                        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                            {results.map((entry) => (
                                <EntryCard 
                                    key={entry.id} 
                                    entry={entry} 
                                    term={term} 
                                    suffix={normalizedSuffix} 
                                    kind={selectedItem.kind}
                                />
                            ))}
                        </div>
                    ) : (
                        <div className="py-16 text-center bg-black/5 rounded-3xl border border-dashed border-black/10">
                            <BookOpen size={40} className="mx-auto text-black/10 mb-4" />
                            <p className="text-black/30 font-medium">{term('no-entries-found')}</p>
                        </div>
                    )}
                </div>

            </div>
        </div>
    );
}
